# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    # High priority configuration for chain-selectors
    allow:
      - dependency-name: "github.com/smartcontractkit/chain-selectors"
    open-pull-requests-limit: 1
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
    # General Go module updates with lower priority
    ignore:
      - dependency-name: "github.com/smartcontractkit/chain-selectors"
    open-pull-requests-limit: 9
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
