// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package datastore

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockContractMetadataStore creates a new instance of MockContractMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContractMetadataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContractMetadataStore {
	mock := &MockContractMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContractMetadataStore is an autogenerated mock type for the ContractMetadataStore type
type MockContractMetadataStore struct {
	mock.Mock
}

type MockContractMetadataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContractMetadataStore) EXPECT() *MockContractMetadataStore_Expecter {
	return &MockContractMetadataStore_Expecter{mock: &_m.Mock}
}

// Fetch provides a mock function for the type MockContractMetadataStore
func (_mock *MockContractMetadataStore) Fetch() ([]ContractMetadata, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Fetch")
	}

	var r0 []ContractMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]ContractMetadata, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []ContractMetadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ContractMetadata)
		}
	}

	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContractMetadataStore_Fetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fetch'
type MockContractMetadataStore_Fetch_Call struct {
	*mock.Call
}

// Fetch is a helper method to define mock.On call
func (_e *MockContractMetadataStore_Expecter) Fetch() *MockContractMetadataStore_Fetch_Call {
	return &MockContractMetadataStore_Fetch_Call{Call: _e.mock.On("Fetch")}
}

func (_c *MockContractMetadataStore_Fetch_Call) Run(run func()) *MockContractMetadataStore_Fetch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockContractMetadataStore_Fetch_Call) Return(metadata []ContractMetadata, err error) *MockContractMetadataStore_Fetch_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockContractMetadataStore_Fetch_Call) RunAndReturn(run func() ([]ContractMetadata, error)) *MockContractMetadataStore_Fetch_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockContractMetadataStore
func (_mock *MockContractMetadataStore) Get(key ContractMetadataKey) (ContractMetadata, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 ContractMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ContractMetadataKey) (ContractMetadata, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(ContractMetadataKey) ContractMetadata); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Get(0).(ContractMetadata)
	}

	if returnFunc, ok := ret.Get(1).(func(ContractMetadataKey) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContractMetadataStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContractMetadataStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key ContractMetadataKey
func (_e *MockContractMetadataStore_Expecter) Get(key interface{}) *MockContractMetadataStore_Get_Call {
	return &MockContractMetadataStore_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContractMetadataStore_Get_Call) Run(run func(key ContractMetadataKey)) *MockContractMetadataStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ContractMetadataKey))
	})
	return _c
}

func (_c *MockContractMetadataStore_Get_Call) Return(metadata ContractMetadata, err error) *MockContractMetadataStore_Get_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockContractMetadataStore_Get_Call) RunAndReturn(run func(ContractMetadataKey) (ContractMetadata, error)) *MockContractMetadataStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockContractMetadataStore
func (_mock *MockContractMetadataStore) Filter(filters ...FilterFunc[ContractMetadataKey, ContractMetadata]) []ContractMetadata {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []ContractMetadata
	if returnFunc, ok := ret.Get(0).(func(...FilterFunc[ContractMetadataKey, ContractMetadata]) []ContractMetadata); ok {
		r0 = returnFunc(filters...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ContractMetadata)
		}
	}
	return r0
}

// MockContractMetadataStore_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockContractMetadataStore_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - filters ...FilterFunc[ContractMetadataKey, ContractMetadata]
func (_e *MockContractMetadataStore_Expecter) Filter(filters interface{}) *MockContractMetadataStore_Filter_Call {
	return &MockContractMetadataStore_Filter_Call{Call: _e.mock.On("Filter", filters)}
}

func (_c *MockContractMetadataStore_Filter_Call) Run(run func(filters ...FilterFunc[ContractMetadataKey, ContractMetadata])) *MockContractMetadataStore_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]FilterFunc[ContractMetadataKey, ContractMetadata], len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(FilterFunc[ContractMetadataKey, ContractMetadata])
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockContractMetadataStore_Filter_Call) Return(metadata []ContractMetadata) *MockContractMetadataStore_Filter_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockContractMetadataStore_Filter_Call) RunAndReturn(run func(...FilterFunc[ContractMetadataKey, ContractMetadata]) []ContractMetadata) *MockContractMetadataStore_Filter_Call {
	_c.Call.Return(run)
	return _c
}

