all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/provider:
    config:
      all: false
    interfaces:
      ContractCaller:
  github.com/smartcontractkit/chainlink-deployments-framework/chain/internal/kms:
    config:
      all: false
      pkgname: "kmsmocks"
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      Client:
  github.com/smartcontractkit/chainlink-deployments-framework/offchain:
    config:
      all: false
      pkgname: "mocks"
      dir: "engine/cld/offchain/internal/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      Provider:
      Client:
  golang.org/x/oauth2:
    config:
      all: false
      pkgname: "mocks"
      dir: "engine/cld/offchain/internal/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      TokenSource:
  github.com/smartcontractkit/chainlink-deployments-framework/engine/test/internal/mcmsutils:
    config:
      all: false
      filename: "mock_{{.InterfaceName | snakecase}}_test.go"
      structname: '{{.Mock}}{{.InterfaceName | firstUpper }}'
    interfaces:
      mcmsExecutable:
      timelockExecutable:
  github.com/smartcontractkit/chainlink-deployments-framework/engine/test/runtime:
    config:
      all: false
      filename: "mock_{{.InterfaceName | snakecase}}_test.go"
      structname: '{{.Mock}}{{.InterfaceName | firstUpper }}'
    interfaces:
      Executable:
      proposalExecutor:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/job:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      JobServiceClient:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/csa:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      CSAServiceClient:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/node:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      NodeServiceClient:
