all: false
dir: "{{.InterfaceDir}}"
filename: "mocks_test.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "{{.Mock}}{{.InterfaceName}}"
pkgname: "{{.SrcPackageName}}"
recursive: false
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/provider:
    config:
      all: false
    interfaces:
      ContractCaller:
  github.com/smartcontractkit/chainlink-deployments-framework/chain/internal/kms:
    config:
      all: false
      pkgname: "kmsmocks"
      dir: "{{.InterfaceDir}}/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      Client:
  github.com/smartcontractkit/chainlink-deployments-framework/offchain/jd:
    config:
      all: false
      pkgname: "mocks"
      dir: "offchain/jd/internal/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      CognitoClient:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/job:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      JobServiceClient:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/csa:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      CSAServiceClient:
  github.com/smartcontractkit/chainlink-protos/job-distributor/v1/node:
    config:
      all: false
      pkgname: "mocks"
      dir: "internal/testing/jd/mocks"
      filename: "mock_{{.InterfaceName | snakecase}}.go"
    interfaces:
      NodeServiceClient:
