# https://taskfile.dev

version: "3"

includes:
  generate:
    taskfile: ./taskfiles/generate/Taskfile.yml
    aliases: [gen]

  lint:
    taskfile: ./taskfiles/lint/Taskfile.yml

  test:
    taskfile: ./taskfiles/test/Taskfile.yml
