// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/smartcontractkit/chainlink-evm/gethwrappers/workflow/generated/workflow_registry_wrapper_v2"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkflowRegistryContract creates a new instance of MockWorkflowRegistryContract. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowRegistryContract(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowRegistryContract {
	mock := &MockWorkflowRegistryContract{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowRegistryContract is an autogenerated mock type for the WorkflowRegistryContract type
type MockWorkflowRegistryContract struct {
	mock.Mock
}

type MockWorkflowRegistryContract_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowRegistryContract) EXPECT() *MockWorkflowRegistryContract_Expecter {
	return &MockWorkflowRegistryContract_Expecter{mock: &_m.Mock}
}

// Address provides a mock function for the type MockWorkflowRegistryContract
func (_mock *MockWorkflowRegistryContract) Address() common.Address {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Address")
	}

	var r0 common.Address
	if returnFunc, ok := ret.Get(0).(func() common.Address); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Address)
		}
	}
	return r0
}

// MockWorkflowRegistryContract_Address_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Address'
type MockWorkflowRegistryContract_Address_Call struct {
	*mock.Call
}

// Address is a helper method to define mock.On call
func (_e *MockWorkflowRegistryContract_Expecter) Address() *MockWorkflowRegistryContract_Address_Call {
	return &MockWorkflowRegistryContract_Address_Call{Call: _e.mock.On("Address")}
}

func (_c *MockWorkflowRegistryContract_Address_Call) Run(run func()) *MockWorkflowRegistryContract_Address_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWorkflowRegistryContract_Address_Call) Return(address common.Address) *MockWorkflowRegistryContract_Address_Call {
	_c.Call.Return(address)
	return _c
}

func (_c *MockWorkflowRegistryContract_Address_Call) RunAndReturn(run func() common.Address) *MockWorkflowRegistryContract_Address_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowById provides a mock function for the type MockWorkflowRegistryContract
func (_mock *MockWorkflowRegistryContract) GetWorkflowById(opts *bind.CallOpts, workflowId [32]byte) (workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView, error) {
	ret := _mock.Called(opts, workflowId)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowById")
	}

	var r0 workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, [32]byte) (workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView, error)); ok {
		return returnFunc(opts, workflowId)
	}
	if returnFunc, ok := ret.Get(0).(func(*bind.CallOpts, [32]byte) workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView); ok {
		r0 = returnFunc(opts, workflowId)
	} else {
		r0 = ret.Get(0).(workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView)
	}
	if returnFunc, ok := ret.Get(1).(func(*bind.CallOpts, [32]byte) error); ok {
		r1 = returnFunc(opts, workflowId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkflowRegistryContract_GetWorkflowById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowById'
type MockWorkflowRegistryContract_GetWorkflowById_Call struct {
	*mock.Call
}

// GetWorkflowById is a helper method to define mock.On call
//   - opts *bind.CallOpts
//   - workflowId [32]byte
func (_e *MockWorkflowRegistryContract_Expecter) GetWorkflowById(opts interface{}, workflowId interface{}) *MockWorkflowRegistryContract_GetWorkflowById_Call {
	return &MockWorkflowRegistryContract_GetWorkflowById_Call{Call: _e.mock.On("GetWorkflowById", opts, workflowId)}
}

func (_c *MockWorkflowRegistryContract_GetWorkflowById_Call) Run(run func(opts *bind.CallOpts, workflowId [32]byte)) *MockWorkflowRegistryContract_GetWorkflowById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bind.CallOpts
		if args[0] != nil {
			arg0 = args[0].(*bind.CallOpts)
		}
		var arg1 [32]byte
		if args[1] != nil {
			arg1 = args[1].([32]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkflowRegistryContract_GetWorkflowById_Call) Return(workflowRegistryWorkflowMetadataView workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView, err error) *MockWorkflowRegistryContract_GetWorkflowById_Call {
	_c.Call.Return(workflowRegistryWorkflowMetadataView, err)
	return _c
}

func (_c *MockWorkflowRegistryContract_GetWorkflowById_Call) RunAndReturn(run func(opts *bind.CallOpts, workflowId [32]byte) (workflow_registry_wrapper_v2.WorkflowRegistryWorkflowMetadataView, error)) *MockWorkflowRegistryContract_GetWorkflowById_Call {
	_c.Call.Return(run)
	return _c
}
