// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package otter_verify

import (
	"fmt"

	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
)

var InitializeDiscriminator = []byte{175, 175, 109, 31, 13, 152, 155, 237}

// Initialize is the `Initialize` instruction.
type Initialize struct {
	// [0] = [WRITE] BuildParams
	// [1] = [WRITE, SIGNER] Authority
	// [2] = [] ProgramAddress
	// [3] = [] SystemProgram
	ag_solanago.AccountMetaSlice `bin:"-" borsh_skip:"true"`
	Params InputParams
}

// NewInitializeInstructionBuilder creates a new `Initialize` instruction builder.
func NewInitializeInstructionBuilder() *Initialize {
	nd := &Initialize{}
	nd.AccountMetaSlice = make(ag_solanago.AccountMetaSlice, 4)
	return nd
}

// SetParams sets the "params" parameter.
func (inst *Initialize) SetParams(params InputParams) *Initialize {
	inst.Params = params
	return inst
}

// SetBuildParamsAccount sets the "build_params" account.
func (inst *Initialize) SetBuildParamsAccount(buildParams ag_solanago.PublicKey) *Initialize {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(buildParams).WRITE()
	return inst
}

// GetBuildParamsAccount gets the "build_params" account.
func (inst *Initialize) GetBuildParamsAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[0]
}

// SetAuthorityAccount sets the "authority" account.
func (inst *Initialize) SetAuthorityAccount(authority ag_solanago.PublicKey) *Initialize {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(authority).SIGNER().WRITE()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
func (inst *Initialize) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[1]
}

// SetProgramAddressAccount sets the "program_address" account.
func (inst *Initialize) SetProgramAddressAccount(programAddress ag_solanago.PublicKey) *Initialize {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(programAddress)
	return inst
}

// GetProgramAddressAccount gets the "program_address" account.
func (inst *Initialize) GetProgramAddressAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[2]
}

// SetSystemProgramAccount sets the "system_program" account.
func (inst *Initialize) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *Initialize {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "system_program" account.
func (inst *Initialize) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice[3]
}


func (inst Initialize) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: ag_binary.NoTypeIDDefaultID,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Initialize) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Initialize) Validate() error {
	if inst.AccountMetaSlice[0] == nil {
		return fmt.Errorf("accounts.BuildParams is not set")
	}
	if inst.AccountMetaSlice[1] == nil {
		return fmt.Errorf("accounts.Authority is not set")
	}
	if inst.AccountMetaSlice[2] == nil {
		return fmt.Errorf("accounts.ProgramAddress is not set")
	}
	if inst.AccountMetaSlice[3] == nil {
		return fmt.Errorf("accounts.SystemProgram is not set")
	}
	return nil
}

func (inst *Initialize) GetAccounts() (out []*ag_solanago.AccountMeta) {
	return inst.AccountMetaSlice
}

func (inst *Initialize) SetAccounts(accounts []*ag_solanago.AccountMeta) error {
	if len(accounts) < 4 {
		return fmt.Errorf("not enough accounts: expected at least 4, got %d", len(accounts))
	}
	inst.AccountMetaSlice = accounts[:4]
	return nil
}

func (inst *Initialize) MarshalWithEncoder(encoder *ag_binary.Encoder) error {
	{
		err := encoder.Encode([8]uint8([]byte{175, 175, 109, 31, 13, 152, 155, 237}))
		if err != nil {
			return err
		}
	}
	{
		err := encoder.Encode(inst.Params)
		if err != nil {
			return err
		}
	}
	return nil
}

func (inst *Initialize) UnmarshalWithDecoder(decoder *ag_binary.Decoder) error {
	{
		err := decoder.Decode(&inst.Params)
		if err != nil {
			return err
		}
	}
	return nil
}


