// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package otter_verify



type InputParams struct {
	Version string
	GitUrl string
	Commit string
	Args []string
	DeploySlot uint64
}


