// This code was AUTOGENERATED using the codama library.
// Please DO NOT EDIT THIS FILE, instead use visitors
// to add features, then rerun codama to update it.
//
// https://github.com/codama-idl/codama

package otter_verify

import (
	ag_solanago "github.com/gagliardetto/solana-go"
)

type OtterVerifyEvent struct {
	Signer ag_solanago.PublicKey
	Program ag_solanago.PublicKey
	Params InputParams
}


