// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/aptos-labs/aptos-go-sdk"
	"github.com/aptos-labs/aptos-go-sdk/api"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAptosRpcClient creates a new instance of MockAptosRpcClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAptosRpcClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAptosRpcClient {
	mock := &MockAptosRpcClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAptosRpcClient is an autogenerated mock type for the AptosRpcClient type
type MockAptosRpcClient struct {
	mock.Mock
}

type MockAptosRpcClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAptosRpcClient) EXPECT() *MockAptosRpcClient_Expecter {
	return &MockAptosRpcClient_Expecter{mock: &_m.Mock}
}

// Account provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) Account(address aptos.AccountAddress, ledgerVersion ...uint64) (aptos.AccountInfo, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Account")
	}

	var r0 aptos.AccountInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) (aptos.AccountInfo, error)); ok {
		return returnFunc(address, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) aptos.AccountInfo); ok {
		r0 = returnFunc(address, ledgerVersion...)
	} else {
		r0 = ret.Get(0).(aptos.AccountInfo)
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, ...uint64) error); ok {
		r1 = returnFunc(address, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_Account_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Account'
type MockAptosRpcClient_Account_Call struct {
	*mock.Call
}

// Account is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) Account(address interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_Account_Call {
	return &MockAptosRpcClient_Account_Call{Call: _e.mock.On("Account",
		append([]interface{}{address}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_Account_Call) Run(run func(address aptos.AccountAddress, ledgerVersion ...uint64)) *MockAptosRpcClient_Account_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 []uint64
		var variadicArgs []uint64
		if len(args) > 1 {
			variadicArgs = args[1].([]uint64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_Account_Call) Return(accountInfo aptos.AccountInfo, err error) *MockAptosRpcClient_Account_Call {
	_c.Call.Return(accountInfo, err)
	return _c
}

func (_c *MockAptosRpcClient_Account_Call) RunAndReturn(run func(address aptos.AccountAddress, ledgerVersion ...uint64) (aptos.AccountInfo, error)) *MockAptosRpcClient_Account_Call {
	_c.Call.Return(run)
	return _c
}

// AccountAPTBalance provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountAPTBalance(address aptos.AccountAddress, ledgerVersion ...uint64) (uint64, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccountAPTBalance")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) (uint64, error)); ok {
		return returnFunc(address, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) uint64); ok {
		r0 = returnFunc(address, ledgerVersion...)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, ...uint64) error); ok {
		r1 = returnFunc(address, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountAPTBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountAPTBalance'
type MockAptosRpcClient_AccountAPTBalance_Call struct {
	*mock.Call
}

// AccountAPTBalance is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) AccountAPTBalance(address interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_AccountAPTBalance_Call {
	return &MockAptosRpcClient_AccountAPTBalance_Call{Call: _e.mock.On("AccountAPTBalance",
		append([]interface{}{address}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_AccountAPTBalance_Call) Run(run func(address aptos.AccountAddress, ledgerVersion ...uint64)) *MockAptosRpcClient_AccountAPTBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 []uint64
		var variadicArgs []uint64
		if len(args) > 1 {
			variadicArgs = args[1].([]uint64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountAPTBalance_Call) Return(v uint64, err error) *MockAptosRpcClient_AccountAPTBalance_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountAPTBalance_Call) RunAndReturn(run func(address aptos.AccountAddress, ledgerVersion ...uint64) (uint64, error)) *MockAptosRpcClient_AccountAPTBalance_Call {
	_c.Call.Return(run)
	return _c
}

// AccountModule provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountModule(address aptos.AccountAddress, moduleName string, ledgerVersion ...uint64) (*api.MoveBytecode, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, moduleName, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address, moduleName)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccountModule")
	}

	var r0 *api.MoveBytecode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, ...uint64) (*api.MoveBytecode, error)); ok {
		return returnFunc(address, moduleName, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, ...uint64) *api.MoveBytecode); ok {
		r0 = returnFunc(address, moduleName, ledgerVersion...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.MoveBytecode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, string, ...uint64) error); ok {
		r1 = returnFunc(address, moduleName, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountModule'
type MockAptosRpcClient_AccountModule_Call struct {
	*mock.Call
}

// AccountModule is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - moduleName string
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) AccountModule(address interface{}, moduleName interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_AccountModule_Call {
	return &MockAptosRpcClient_AccountModule_Call{Call: _e.mock.On("AccountModule",
		append([]interface{}{address, moduleName}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_AccountModule_Call) Run(run func(address aptos.AccountAddress, moduleName string, ledgerVersion ...uint64)) *MockAptosRpcClient_AccountModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint64
		var variadicArgs []uint64
		if len(args) > 2 {
			variadicArgs = args[2].([]uint64)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountModule_Call) Return(moveBytecode *api.MoveBytecode, err error) *MockAptosRpcClient_AccountModule_Call {
	_c.Call.Return(moveBytecode, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountModule_Call) RunAndReturn(run func(address aptos.AccountAddress, moduleName string, ledgerVersion ...uint64) (*api.MoveBytecode, error)) *MockAptosRpcClient_AccountModule_Call {
	_c.Call.Return(run)
	return _c
}

// AccountResource provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountResource(address aptos.AccountAddress, resourceType string, ledgerVersion ...uint64) (map[string]any, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, resourceType, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address, resourceType)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccountResource")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, ...uint64) (map[string]any, error)); ok {
		return returnFunc(address, resourceType, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, ...uint64) map[string]any); ok {
		r0 = returnFunc(address, resourceType, ledgerVersion...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, string, ...uint64) error); ok {
		r1 = returnFunc(address, resourceType, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountResource'
type MockAptosRpcClient_AccountResource_Call struct {
	*mock.Call
}

// AccountResource is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - resourceType string
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) AccountResource(address interface{}, resourceType interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_AccountResource_Call {
	return &MockAptosRpcClient_AccountResource_Call{Call: _e.mock.On("AccountResource",
		append([]interface{}{address, resourceType}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_AccountResource_Call) Run(run func(address aptos.AccountAddress, resourceType string, ledgerVersion ...uint64)) *MockAptosRpcClient_AccountResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []uint64
		var variadicArgs []uint64
		if len(args) > 2 {
			variadicArgs = args[2].([]uint64)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountResource_Call) Return(stringToV map[string]any, err error) *MockAptosRpcClient_AccountResource_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountResource_Call) RunAndReturn(run func(address aptos.AccountAddress, resourceType string, ledgerVersion ...uint64) (map[string]any, error)) *MockAptosRpcClient_AccountResource_Call {
	_c.Call.Return(run)
	return _c
}

// AccountResources provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountResources(address aptos.AccountAddress, ledgerVersion ...uint64) ([]aptos.AccountResourceInfo, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccountResources")
	}

	var r0 []aptos.AccountResourceInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) ([]aptos.AccountResourceInfo, error)); ok {
		return returnFunc(address, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) []aptos.AccountResourceInfo); ok {
		r0 = returnFunc(address, ledgerVersion...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aptos.AccountResourceInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, ...uint64) error); ok {
		r1 = returnFunc(address, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountResources'
type MockAptosRpcClient_AccountResources_Call struct {
	*mock.Call
}

// AccountResources is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) AccountResources(address interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_AccountResources_Call {
	return &MockAptosRpcClient_AccountResources_Call{Call: _e.mock.On("AccountResources",
		append([]interface{}{address}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_AccountResources_Call) Run(run func(address aptos.AccountAddress, ledgerVersion ...uint64)) *MockAptosRpcClient_AccountResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 []uint64
		var variadicArgs []uint64
		if len(args) > 1 {
			variadicArgs = args[1].([]uint64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountResources_Call) Return(accountResourceInfos []aptos.AccountResourceInfo, err error) *MockAptosRpcClient_AccountResources_Call {
	_c.Call.Return(accountResourceInfos, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountResources_Call) RunAndReturn(run func(address aptos.AccountAddress, ledgerVersion ...uint64) ([]aptos.AccountResourceInfo, error)) *MockAptosRpcClient_AccountResources_Call {
	_c.Call.Return(run)
	return _c
}

// AccountResourcesBCS provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountResourcesBCS(address aptos.AccountAddress, ledgerVersion ...uint64) ([]aptos.AccountResourceRecord, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(address, ledgerVersion)
	} else {
		tmpRet = _mock.Called(address)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccountResourcesBCS")
	}

	var r0 []aptos.AccountResourceRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) ([]aptos.AccountResourceRecord, error)); ok {
		return returnFunc(address, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, ...uint64) []aptos.AccountResourceRecord); ok {
		r0 = returnFunc(address, ledgerVersion...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]aptos.AccountResourceRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, ...uint64) error); ok {
		r1 = returnFunc(address, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountResourcesBCS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountResourcesBCS'
type MockAptosRpcClient_AccountResourcesBCS_Call struct {
	*mock.Call
}

// AccountResourcesBCS is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) AccountResourcesBCS(address interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_AccountResourcesBCS_Call {
	return &MockAptosRpcClient_AccountResourcesBCS_Call{Call: _e.mock.On("AccountResourcesBCS",
		append([]interface{}{address}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_AccountResourcesBCS_Call) Run(run func(address aptos.AccountAddress, ledgerVersion ...uint64)) *MockAptosRpcClient_AccountResourcesBCS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 []uint64
		var variadicArgs []uint64
		if len(args) > 1 {
			variadicArgs = args[1].([]uint64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountResourcesBCS_Call) Return(accountResourceRecords []aptos.AccountResourceRecord, err error) *MockAptosRpcClient_AccountResourcesBCS_Call {
	_c.Call.Return(accountResourceRecords, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountResourcesBCS_Call) RunAndReturn(run func(address aptos.AccountAddress, ledgerVersion ...uint64) ([]aptos.AccountResourceRecord, error)) *MockAptosRpcClient_AccountResourcesBCS_Call {
	_c.Call.Return(run)
	return _c
}

// AccountTransactions provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) AccountTransactions(address aptos.AccountAddress, start *uint64, limit *uint64) ([]*api.CommittedTransaction, error) {
	ret := _mock.Called(address, start, limit)

	if len(ret) == 0 {
		panic("no return value specified for AccountTransactions")
	}

	var r0 []*api.CommittedTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, *uint64, *uint64) ([]*api.CommittedTransaction, error)); ok {
		return returnFunc(address, start, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, *uint64, *uint64) []*api.CommittedTransaction); ok {
		r0 = returnFunc(address, start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.CommittedTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, *uint64, *uint64) error); ok {
		r1 = returnFunc(address, start, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_AccountTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountTransactions'
type MockAptosRpcClient_AccountTransactions_Call struct {
	*mock.Call
}

// AccountTransactions is a helper method to define mock.On call
//   - address aptos.AccountAddress
//   - start *uint64
//   - limit *uint64
func (_e *MockAptosRpcClient_Expecter) AccountTransactions(address interface{}, start interface{}, limit interface{}) *MockAptosRpcClient_AccountTransactions_Call {
	return &MockAptosRpcClient_AccountTransactions_Call{Call: _e.mock.On("AccountTransactions", address, start, limit)}
}

func (_c *MockAptosRpcClient_AccountTransactions_Call) Run(run func(address aptos.AccountAddress, start *uint64, limit *uint64)) *MockAptosRpcClient_AccountTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_AccountTransactions_Call) Return(committedTransactions []*api.CommittedTransaction, err error) *MockAptosRpcClient_AccountTransactions_Call {
	_c.Call.Return(committedTransactions, err)
	return _c
}

func (_c *MockAptosRpcClient_AccountTransactions_Call) RunAndReturn(run func(address aptos.AccountAddress, start *uint64, limit *uint64) ([]*api.CommittedTransaction, error)) *MockAptosRpcClient_AccountTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// BatchSubmitTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BatchSubmitTransaction(signedTxns []*aptos.SignedTransaction) (*api.BatchSubmitTransactionResponse, error) {
	ret := _mock.Called(signedTxns)

	if len(ret) == 0 {
		panic("no return value specified for BatchSubmitTransaction")
	}

	var r0 *api.BatchSubmitTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]*aptos.SignedTransaction) (*api.BatchSubmitTransactionResponse, error)); ok {
		return returnFunc(signedTxns)
	}
	if returnFunc, ok := ret.Get(0).(func([]*aptos.SignedTransaction) *api.BatchSubmitTransactionResponse); ok {
		r0 = returnFunc(signedTxns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.BatchSubmitTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]*aptos.SignedTransaction) error); ok {
		r1 = returnFunc(signedTxns)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BatchSubmitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchSubmitTransaction'
type MockAptosRpcClient_BatchSubmitTransaction_Call struct {
	*mock.Call
}

// BatchSubmitTransaction is a helper method to define mock.On call
//   - signedTxns []*aptos.SignedTransaction
func (_e *MockAptosRpcClient_Expecter) BatchSubmitTransaction(signedTxns interface{}) *MockAptosRpcClient_BatchSubmitTransaction_Call {
	return &MockAptosRpcClient_BatchSubmitTransaction_Call{Call: _e.mock.On("BatchSubmitTransaction", signedTxns)}
}

func (_c *MockAptosRpcClient_BatchSubmitTransaction_Call) Run(run func(signedTxns []*aptos.SignedTransaction)) *MockAptosRpcClient_BatchSubmitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []*aptos.SignedTransaction
		if args[0] != nil {
			arg0 = args[0].([]*aptos.SignedTransaction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BatchSubmitTransaction_Call) Return(batchSubmitTransactionResponse *api.BatchSubmitTransactionResponse, err error) *MockAptosRpcClient_BatchSubmitTransaction_Call {
	_c.Call.Return(batchSubmitTransactionResponse, err)
	return _c
}

func (_c *MockAptosRpcClient_BatchSubmitTransaction_Call) RunAndReturn(run func(signedTxns []*aptos.SignedTransaction) (*api.BatchSubmitTransactionResponse, error)) *MockAptosRpcClient_BatchSubmitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// BlockByHeight provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BlockByHeight(blockHeight uint64, withTransactions bool) (*api.Block, error) {
	ret := _mock.Called(blockHeight, withTransactions)

	if len(ret) == 0 {
		panic("no return value specified for BlockByHeight")
	}

	var r0 *api.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, bool) (*api.Block, error)); ok {
		return returnFunc(blockHeight, withTransactions)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, bool) *api.Block); ok {
		r0 = returnFunc(blockHeight, withTransactions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, bool) error); ok {
		r1 = returnFunc(blockHeight, withTransactions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BlockByHeight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockByHeight'
type MockAptosRpcClient_BlockByHeight_Call struct {
	*mock.Call
}

// BlockByHeight is a helper method to define mock.On call
//   - blockHeight uint64
//   - withTransactions bool
func (_e *MockAptosRpcClient_Expecter) BlockByHeight(blockHeight interface{}, withTransactions interface{}) *MockAptosRpcClient_BlockByHeight_Call {
	return &MockAptosRpcClient_BlockByHeight_Call{Call: _e.mock.On("BlockByHeight", blockHeight, withTransactions)}
}

func (_c *MockAptosRpcClient_BlockByHeight_Call) Run(run func(blockHeight uint64, withTransactions bool)) *MockAptosRpcClient_BlockByHeight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BlockByHeight_Call) Return(block *api.Block, err error) *MockAptosRpcClient_BlockByHeight_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockAptosRpcClient_BlockByHeight_Call) RunAndReturn(run func(blockHeight uint64, withTransactions bool) (*api.Block, error)) *MockAptosRpcClient_BlockByHeight_Call {
	_c.Call.Return(run)
	return _c
}

// BlockByVersion provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BlockByVersion(ledgerVersion uint64, withTransactions bool) (*api.Block, error) {
	ret := _mock.Called(ledgerVersion, withTransactions)

	if len(ret) == 0 {
		panic("no return value specified for BlockByVersion")
	}

	var r0 *api.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64, bool) (*api.Block, error)); ok {
		return returnFunc(ledgerVersion, withTransactions)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, bool) *api.Block); ok {
		r0 = returnFunc(ledgerVersion, withTransactions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, bool) error); ok {
		r1 = returnFunc(ledgerVersion, withTransactions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BlockByVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockByVersion'
type MockAptosRpcClient_BlockByVersion_Call struct {
	*mock.Call
}

// BlockByVersion is a helper method to define mock.On call
//   - ledgerVersion uint64
//   - withTransactions bool
func (_e *MockAptosRpcClient_Expecter) BlockByVersion(ledgerVersion interface{}, withTransactions interface{}) *MockAptosRpcClient_BlockByVersion_Call {
	return &MockAptosRpcClient_BlockByVersion_Call{Call: _e.mock.On("BlockByVersion", ledgerVersion, withTransactions)}
}

func (_c *MockAptosRpcClient_BlockByVersion_Call) Run(run func(ledgerVersion uint64, withTransactions bool)) *MockAptosRpcClient_BlockByVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BlockByVersion_Call) Return(block *api.Block, err error) *MockAptosRpcClient_BlockByVersion_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockAptosRpcClient_BlockByVersion_Call) RunAndReturn(run func(ledgerVersion uint64, withTransactions bool) (*api.Block, error)) *MockAptosRpcClient_BlockByVersion_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSignAndSubmitTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BuildSignAndSubmitTransaction(sender aptos.TransactionSigner, payload aptos.TransactionPayload, options ...any) (*api.SubmitTransactionResponse, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(sender, payload, options)
	} else {
		tmpRet = _mock.Called(sender, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BuildSignAndSubmitTransaction")
	}

	var r0 *api.SubmitTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.TransactionSigner, aptos.TransactionPayload, ...any) (*api.SubmitTransactionResponse, error)); ok {
		return returnFunc(sender, payload, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.TransactionSigner, aptos.TransactionPayload, ...any) *api.SubmitTransactionResponse); ok {
		r0 = returnFunc(sender, payload, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SubmitTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.TransactionSigner, aptos.TransactionPayload, ...any) error); ok {
		r1 = returnFunc(sender, payload, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BuildSignAndSubmitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSignAndSubmitTransaction'
type MockAptosRpcClient_BuildSignAndSubmitTransaction_Call struct {
	*mock.Call
}

// BuildSignAndSubmitTransaction is a helper method to define mock.On call
//   - sender aptos.TransactionSigner
//   - payload aptos.TransactionPayload
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) BuildSignAndSubmitTransaction(sender interface{}, payload interface{}, options ...interface{}) *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call {
	return &MockAptosRpcClient_BuildSignAndSubmitTransaction_Call{Call: _e.mock.On("BuildSignAndSubmitTransaction",
		append([]interface{}{sender, payload}, options...)...)}
}

func (_c *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call) Run(run func(sender aptos.TransactionSigner, payload aptos.TransactionPayload, options ...any)) *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.TransactionSigner
		if args[0] != nil {
			arg0 = args[0].(aptos.TransactionSigner)
		}
		var arg1 aptos.TransactionPayload
		if args[1] != nil {
			arg1 = args[1].(aptos.TransactionPayload)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call) Return(v *api.SubmitTransactionResponse, err error) *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call) RunAndReturn(run func(sender aptos.TransactionSigner, payload aptos.TransactionPayload, options ...any) (*api.SubmitTransactionResponse, error)) *MockAptosRpcClient_BuildSignAndSubmitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// BuildTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BuildTransaction(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any) (*aptos.RawTransaction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(sender, payload, options)
	} else {
		tmpRet = _mock.Called(sender, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BuildTransaction")
	}

	var r0 *aptos.RawTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) (*aptos.RawTransaction, error)); ok {
		return returnFunc(sender, payload, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) *aptos.RawTransaction); ok {
		r0 = returnFunc(sender, payload, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aptos.RawTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) error); ok {
		r1 = returnFunc(sender, payload, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BuildTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildTransaction'
type MockAptosRpcClient_BuildTransaction_Call struct {
	*mock.Call
}

// BuildTransaction is a helper method to define mock.On call
//   - sender aptos.AccountAddress
//   - payload aptos.TransactionPayload
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) BuildTransaction(sender interface{}, payload interface{}, options ...interface{}) *MockAptosRpcClient_BuildTransaction_Call {
	return &MockAptosRpcClient_BuildTransaction_Call{Call: _e.mock.On("BuildTransaction",
		append([]interface{}{sender, payload}, options...)...)}
}

func (_c *MockAptosRpcClient_BuildTransaction_Call) Run(run func(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any)) *MockAptosRpcClient_BuildTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 aptos.TransactionPayload
		if args[1] != nil {
			arg1 = args[1].(aptos.TransactionPayload)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BuildTransaction_Call) Return(rawTransaction *aptos.RawTransaction, err error) *MockAptosRpcClient_BuildTransaction_Call {
	_c.Call.Return(rawTransaction, err)
	return _c
}

func (_c *MockAptosRpcClient_BuildTransaction_Call) RunAndReturn(run func(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any) (*aptos.RawTransaction, error)) *MockAptosRpcClient_BuildTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// BuildTransactionMultiAgent provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) BuildTransactionMultiAgent(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any) (*aptos.RawTransactionWithData, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(sender, payload, options)
	} else {
		tmpRet = _mock.Called(sender, payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BuildTransactionMultiAgent")
	}

	var r0 *aptos.RawTransactionWithData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) (*aptos.RawTransactionWithData, error)); ok {
		return returnFunc(sender, payload, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) *aptos.RawTransactionWithData); ok {
		r0 = returnFunc(sender, payload, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aptos.RawTransactionWithData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, aptos.TransactionPayload, ...any) error); ok {
		r1 = returnFunc(sender, payload, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_BuildTransactionMultiAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildTransactionMultiAgent'
type MockAptosRpcClient_BuildTransactionMultiAgent_Call struct {
	*mock.Call
}

// BuildTransactionMultiAgent is a helper method to define mock.On call
//   - sender aptos.AccountAddress
//   - payload aptos.TransactionPayload
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) BuildTransactionMultiAgent(sender interface{}, payload interface{}, options ...interface{}) *MockAptosRpcClient_BuildTransactionMultiAgent_Call {
	return &MockAptosRpcClient_BuildTransactionMultiAgent_Call{Call: _e.mock.On("BuildTransactionMultiAgent",
		append([]interface{}{sender, payload}, options...)...)}
}

func (_c *MockAptosRpcClient_BuildTransactionMultiAgent_Call) Run(run func(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any)) *MockAptosRpcClient_BuildTransactionMultiAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 aptos.TransactionPayload
		if args[1] != nil {
			arg1 = args[1].(aptos.TransactionPayload)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_BuildTransactionMultiAgent_Call) Return(rawTransactionWithData *aptos.RawTransactionWithData, err error) *MockAptosRpcClient_BuildTransactionMultiAgent_Call {
	_c.Call.Return(rawTransactionWithData, err)
	return _c
}

func (_c *MockAptosRpcClient_BuildTransactionMultiAgent_Call) RunAndReturn(run func(sender aptos.AccountAddress, payload aptos.TransactionPayload, options ...any) (*aptos.RawTransactionWithData, error)) *MockAptosRpcClient_BuildTransactionMultiAgent_Call {
	_c.Call.Return(run)
	return _c
}

// EntryFunctionWithArgs provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) EntryFunctionWithArgs(moduleAddress aptos.AccountAddress, moduleName string, functionName string, typeArgs []any, args []any, options ...any) (*aptos.EntryFunction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(moduleAddress, moduleName, functionName, typeArgs, args, options)
	} else {
		tmpRet = _mock.Called(moduleAddress, moduleName, functionName, typeArgs, args)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EntryFunctionWithArgs")
	}

	var r0 *aptos.EntryFunction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, []any, []any, ...any) (*aptos.EntryFunction, error)); ok {
		return returnFunc(moduleAddress, moduleName, functionName, typeArgs, args, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, []any, []any, ...any) *aptos.EntryFunction); ok {
		r0 = returnFunc(moduleAddress, moduleName, functionName, typeArgs, args, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*aptos.EntryFunction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, string, string, []any, []any, ...any) error); ok {
		r1 = returnFunc(moduleAddress, moduleName, functionName, typeArgs, args, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_EntryFunctionWithArgs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EntryFunctionWithArgs'
type MockAptosRpcClient_EntryFunctionWithArgs_Call struct {
	*mock.Call
}

// EntryFunctionWithArgs is a helper method to define mock.On call
//   - moduleAddress aptos.AccountAddress
//   - moduleName string
//   - functionName string
//   - typeArgs []any
//   - args []any
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) EntryFunctionWithArgs(moduleAddress interface{}, moduleName interface{}, functionName interface{}, typeArgs interface{}, args interface{}, options ...interface{}) *MockAptosRpcClient_EntryFunctionWithArgs_Call {
	return &MockAptosRpcClient_EntryFunctionWithArgs_Call{Call: _e.mock.On("EntryFunctionWithArgs",
		append([]interface{}{moduleAddress, moduleName, functionName, typeArgs, args}, options...)...)}
}

func (_c *MockAptosRpcClient_EntryFunctionWithArgs_Call) Run(run func(moduleAddress aptos.AccountAddress, moduleName string, functionName string, typeArgs []any, args []any, options ...any)) *MockAptosRpcClient_EntryFunctionWithArgs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		if args[3] != nil {
			arg3 = args[3].([]any)
		}
		var arg4 []any
		if args[4] != nil {
			arg4 = args[4].([]any)
		}
		var arg5 []any
		var variadicArgs []any
		if len(args) > 5 {
			variadicArgs = args[5].([]any)
		}
		arg5 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_EntryFunctionWithArgs_Call) Return(entryFunction *aptos.EntryFunction, err error) *MockAptosRpcClient_EntryFunctionWithArgs_Call {
	_c.Call.Return(entryFunction, err)
	return _c
}

func (_c *MockAptosRpcClient_EntryFunctionWithArgs_Call) RunAndReturn(run func(moduleAddress aptos.AccountAddress, moduleName string, functionName string, typeArgs []any, args []any, options ...any) (*aptos.EntryFunction, error)) *MockAptosRpcClient_EntryFunctionWithArgs_Call {
	_c.Call.Return(run)
	return _c
}

// EstimateGasPrice provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) EstimateGasPrice() (aptos.EstimateGasInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EstimateGasPrice")
	}

	var r0 aptos.EstimateGasInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (aptos.EstimateGasInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() aptos.EstimateGasInfo); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(aptos.EstimateGasInfo)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_EstimateGasPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGasPrice'
type MockAptosRpcClient_EstimateGasPrice_Call struct {
	*mock.Call
}

// EstimateGasPrice is a helper method to define mock.On call
func (_e *MockAptosRpcClient_Expecter) EstimateGasPrice() *MockAptosRpcClient_EstimateGasPrice_Call {
	return &MockAptosRpcClient_EstimateGasPrice_Call{Call: _e.mock.On("EstimateGasPrice")}
}

func (_c *MockAptosRpcClient_EstimateGasPrice_Call) Run(run func()) *MockAptosRpcClient_EstimateGasPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAptosRpcClient_EstimateGasPrice_Call) Return(estimateGasInfo aptos.EstimateGasInfo, err error) *MockAptosRpcClient_EstimateGasPrice_Call {
	_c.Call.Return(estimateGasInfo, err)
	return _c
}

func (_c *MockAptosRpcClient_EstimateGasPrice_Call) RunAndReturn(run func() (aptos.EstimateGasInfo, error)) *MockAptosRpcClient_EstimateGasPrice_Call {
	_c.Call.Return(run)
	return _c
}

// EventsByCreationNumber provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) EventsByCreationNumber(account aptos.AccountAddress, creationNumber string, start *uint64, limit *uint64) ([]*api.Event, error) {
	ret := _mock.Called(account, creationNumber, start, limit)

	if len(ret) == 0 {
		panic("no return value specified for EventsByCreationNumber")
	}

	var r0 []*api.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, *uint64, *uint64) ([]*api.Event, error)); ok {
		return returnFunc(account, creationNumber, start, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, *uint64, *uint64) []*api.Event); ok {
		r0 = returnFunc(account, creationNumber, start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, string, *uint64, *uint64) error); ok {
		r1 = returnFunc(account, creationNumber, start, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_EventsByCreationNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsByCreationNumber'
type MockAptosRpcClient_EventsByCreationNumber_Call struct {
	*mock.Call
}

// EventsByCreationNumber is a helper method to define mock.On call
//   - account aptos.AccountAddress
//   - creationNumber string
//   - start *uint64
//   - limit *uint64
func (_e *MockAptosRpcClient_Expecter) EventsByCreationNumber(account interface{}, creationNumber interface{}, start interface{}, limit interface{}) *MockAptosRpcClient_EventsByCreationNumber_Call {
	return &MockAptosRpcClient_EventsByCreationNumber_Call{Call: _e.mock.On("EventsByCreationNumber", account, creationNumber, start, limit)}
}

func (_c *MockAptosRpcClient_EventsByCreationNumber_Call) Run(run func(account aptos.AccountAddress, creationNumber string, start *uint64, limit *uint64)) *MockAptosRpcClient_EventsByCreationNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *uint64
		if args[2] != nil {
			arg2 = args[2].(*uint64)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_EventsByCreationNumber_Call) Return(events []*api.Event, err error) *MockAptosRpcClient_EventsByCreationNumber_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockAptosRpcClient_EventsByCreationNumber_Call) RunAndReturn(run func(account aptos.AccountAddress, creationNumber string, start *uint64, limit *uint64) ([]*api.Event, error)) *MockAptosRpcClient_EventsByCreationNumber_Call {
	_c.Call.Return(run)
	return _c
}

// EventsByHandle provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) EventsByHandle(account aptos.AccountAddress, eventHandle string, fieldName string, start *uint64, limit *uint64) ([]*api.Event, error) {
	ret := _mock.Called(account, eventHandle, fieldName, start, limit)

	if len(ret) == 0 {
		panic("no return value specified for EventsByHandle")
	}

	var r0 []*api.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, *uint64, *uint64) ([]*api.Event, error)); ok {
		return returnFunc(account, eventHandle, fieldName, start, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(aptos.AccountAddress, string, string, *uint64, *uint64) []*api.Event); ok {
		r0 = returnFunc(account, eventHandle, fieldName, start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(aptos.AccountAddress, string, string, *uint64, *uint64) error); ok {
		r1 = returnFunc(account, eventHandle, fieldName, start, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_EventsByHandle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventsByHandle'
type MockAptosRpcClient_EventsByHandle_Call struct {
	*mock.Call
}

// EventsByHandle is a helper method to define mock.On call
//   - account aptos.AccountAddress
//   - eventHandle string
//   - fieldName string
//   - start *uint64
//   - limit *uint64
func (_e *MockAptosRpcClient_Expecter) EventsByHandle(account interface{}, eventHandle interface{}, fieldName interface{}, start interface{}, limit interface{}) *MockAptosRpcClient_EventsByHandle_Call {
	return &MockAptosRpcClient_EventsByHandle_Call{Call: _e.mock.On("EventsByHandle", account, eventHandle, fieldName, start, limit)}
}

func (_c *MockAptosRpcClient_EventsByHandle_Call) Run(run func(account aptos.AccountAddress, eventHandle string, fieldName string, start *uint64, limit *uint64)) *MockAptosRpcClient_EventsByHandle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 aptos.AccountAddress
		if args[0] != nil {
			arg0 = args[0].(aptos.AccountAddress)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		var arg4 *uint64
		if args[4] != nil {
			arg4 = args[4].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_EventsByHandle_Call) Return(events []*api.Event, err error) *MockAptosRpcClient_EventsByHandle_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockAptosRpcClient_EventsByHandle_Call) RunAndReturn(run func(account aptos.AccountAddress, eventHandle string, fieldName string, start *uint64, limit *uint64) ([]*api.Event, error)) *MockAptosRpcClient_EventsByHandle_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainId provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) GetChainId() (uint8, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetChainId")
	}

	var r0 uint8
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (uint8, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() uint8); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint8)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_GetChainId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainId'
type MockAptosRpcClient_GetChainId_Call struct {
	*mock.Call
}

// GetChainId is a helper method to define mock.On call
func (_e *MockAptosRpcClient_Expecter) GetChainId() *MockAptosRpcClient_GetChainId_Call {
	return &MockAptosRpcClient_GetChainId_Call{Call: _e.mock.On("GetChainId")}
}

func (_c *MockAptosRpcClient_GetChainId_Call) Run(run func()) *MockAptosRpcClient_GetChainId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAptosRpcClient_GetChainId_Call) Return(v uint8, err error) *MockAptosRpcClient_GetChainId_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAptosRpcClient_GetChainId_Call) RunAndReturn(run func() (uint8, error)) *MockAptosRpcClient_GetChainId_Call {
	_c.Call.Return(run)
	return _c
}

// Info provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) Info() (aptos.NodeInfo, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Info")
	}

	var r0 aptos.NodeInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (aptos.NodeInfo, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() aptos.NodeInfo); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(aptos.NodeInfo)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockAptosRpcClient_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
func (_e *MockAptosRpcClient_Expecter) Info() *MockAptosRpcClient_Info_Call {
	return &MockAptosRpcClient_Info_Call{Call: _e.mock.On("Info")}
}

func (_c *MockAptosRpcClient_Info_Call) Run(run func()) *MockAptosRpcClient_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAptosRpcClient_Info_Call) Return(nodeInfo aptos.NodeInfo, err error) *MockAptosRpcClient_Info_Call {
	_c.Call.Return(nodeInfo, err)
	return _c
}

func (_c *MockAptosRpcClient_Info_Call) RunAndReturn(run func() (aptos.NodeInfo, error)) *MockAptosRpcClient_Info_Call {
	_c.Call.Return(run)
	return _c
}

// NodeAPIHealthCheck provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) NodeAPIHealthCheck(durationSecs ...uint64) (api.HealthCheckResponse, error) {
	var tmpRet mock.Arguments
	if len(durationSecs) > 0 {
		tmpRet = _mock.Called(durationSecs)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for NodeAPIHealthCheck")
	}

	var r0 api.HealthCheckResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(...uint64) (api.HealthCheckResponse, error)); ok {
		return returnFunc(durationSecs...)
	}
	if returnFunc, ok := ret.Get(0).(func(...uint64) api.HealthCheckResponse); ok {
		r0 = returnFunc(durationSecs...)
	} else {
		r0 = ret.Get(0).(api.HealthCheckResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(...uint64) error); ok {
		r1 = returnFunc(durationSecs...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_NodeAPIHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NodeAPIHealthCheck'
type MockAptosRpcClient_NodeAPIHealthCheck_Call struct {
	*mock.Call
}

// NodeAPIHealthCheck is a helper method to define mock.On call
//   - durationSecs ...uint64
func (_e *MockAptosRpcClient_Expecter) NodeAPIHealthCheck(durationSecs ...interface{}) *MockAptosRpcClient_NodeAPIHealthCheck_Call {
	return &MockAptosRpcClient_NodeAPIHealthCheck_Call{Call: _e.mock.On("NodeAPIHealthCheck",
		append([]interface{}{}, durationSecs...)...)}
}

func (_c *MockAptosRpcClient_NodeAPIHealthCheck_Call) Run(run func(durationSecs ...uint64)) *MockAptosRpcClient_NodeAPIHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		var variadicArgs []uint64
		if len(args) > 0 {
			variadicArgs = args[0].([]uint64)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_NodeAPIHealthCheck_Call) Return(healthCheckResponse api.HealthCheckResponse, err error) *MockAptosRpcClient_NodeAPIHealthCheck_Call {
	_c.Call.Return(healthCheckResponse, err)
	return _c
}

func (_c *MockAptosRpcClient_NodeAPIHealthCheck_Call) RunAndReturn(run func(durationSecs ...uint64) (api.HealthCheckResponse, error)) *MockAptosRpcClient_NodeAPIHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// PollForTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) PollForTransaction(hash string, options ...any) (*api.UserTransaction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(hash, options)
	} else {
		tmpRet = _mock.Called(hash)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PollForTransaction")
	}

	var r0 *api.UserTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*api.UserTransaction, error)); ok {
		return returnFunc(hash, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *api.UserTransaction); ok {
		r0 = returnFunc(hash, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.UserTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(hash, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_PollForTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollForTransaction'
type MockAptosRpcClient_PollForTransaction_Call struct {
	*mock.Call
}

// PollForTransaction is a helper method to define mock.On call
//   - hash string
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) PollForTransaction(hash interface{}, options ...interface{}) *MockAptosRpcClient_PollForTransaction_Call {
	return &MockAptosRpcClient_PollForTransaction_Call{Call: _e.mock.On("PollForTransaction",
		append([]interface{}{hash}, options...)...)}
}

func (_c *MockAptosRpcClient_PollForTransaction_Call) Run(run func(hash string, options ...any)) *MockAptosRpcClient_PollForTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_PollForTransaction_Call) Return(userTransaction *api.UserTransaction, err error) *MockAptosRpcClient_PollForTransaction_Call {
	_c.Call.Return(userTransaction, err)
	return _c
}

func (_c *MockAptosRpcClient_PollForTransaction_Call) RunAndReturn(run func(hash string, options ...any) (*api.UserTransaction, error)) *MockAptosRpcClient_PollForTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// PollForTransactions provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) PollForTransactions(txnHashes []string, options ...any) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(txnHashes, options)
	} else {
		tmpRet = _mock.Called(txnHashes)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PollForTransactions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, ...any) error); ok {
		r0 = returnFunc(txnHashes, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAptosRpcClient_PollForTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PollForTransactions'
type MockAptosRpcClient_PollForTransactions_Call struct {
	*mock.Call
}

// PollForTransactions is a helper method to define mock.On call
//   - txnHashes []string
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) PollForTransactions(txnHashes interface{}, options ...interface{}) *MockAptosRpcClient_PollForTransactions_Call {
	return &MockAptosRpcClient_PollForTransactions_Call{Call: _e.mock.On("PollForTransactions",
		append([]interface{}{txnHashes}, options...)...)}
}

func (_c *MockAptosRpcClient_PollForTransactions_Call) Run(run func(txnHashes []string, options ...any)) *MockAptosRpcClient_PollForTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_PollForTransactions_Call) Return(err error) *MockAptosRpcClient_PollForTransactions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAptosRpcClient_PollForTransactions_Call) RunAndReturn(run func(txnHashes []string, options ...any) error) *MockAptosRpcClient_PollForTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveHeader provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) RemoveHeader(key string) {
	_mock.Called(key)
	return
}

// MockAptosRpcClient_RemoveHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveHeader'
type MockAptosRpcClient_RemoveHeader_Call struct {
	*mock.Call
}

// RemoveHeader is a helper method to define mock.On call
//   - key string
func (_e *MockAptosRpcClient_Expecter) RemoveHeader(key interface{}) *MockAptosRpcClient_RemoveHeader_Call {
	return &MockAptosRpcClient_RemoveHeader_Call{Call: _e.mock.On("RemoveHeader", key)}
}

func (_c *MockAptosRpcClient_RemoveHeader_Call) Run(run func(key string)) *MockAptosRpcClient_RemoveHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_RemoveHeader_Call) Return() *MockAptosRpcClient_RemoveHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAptosRpcClient_RemoveHeader_Call) RunAndReturn(run func(key string)) *MockAptosRpcClient_RemoveHeader_Call {
	_c.Run(run)
	return _c
}

// SetHeader provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) SetHeader(key string, value string) {
	_mock.Called(key, value)
	return
}

// MockAptosRpcClient_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockAptosRpcClient_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockAptosRpcClient_Expecter) SetHeader(key interface{}, value interface{}) *MockAptosRpcClient_SetHeader_Call {
	return &MockAptosRpcClient_SetHeader_Call{Call: _e.mock.On("SetHeader", key, value)}
}

func (_c *MockAptosRpcClient_SetHeader_Call) Run(run func(key string, value string)) *MockAptosRpcClient_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_SetHeader_Call) Return() *MockAptosRpcClient_SetHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAptosRpcClient_SetHeader_Call) RunAndReturn(run func(key string, value string)) *MockAptosRpcClient_SetHeader_Call {
	_c.Run(run)
	return _c
}

// SetTimeout provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) SetTimeout(timeout time.Duration) {
	_mock.Called(timeout)
	return
}

// MockAptosRpcClient_SetTimeout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTimeout'
type MockAptosRpcClient_SetTimeout_Call struct {
	*mock.Call
}

// SetTimeout is a helper method to define mock.On call
//   - timeout time.Duration
func (_e *MockAptosRpcClient_Expecter) SetTimeout(timeout interface{}) *MockAptosRpcClient_SetTimeout_Call {
	return &MockAptosRpcClient_SetTimeout_Call{Call: _e.mock.On("SetTimeout", timeout)}
}

func (_c *MockAptosRpcClient_SetTimeout_Call) Run(run func(timeout time.Duration)) *MockAptosRpcClient_SetTimeout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Duration
		if args[0] != nil {
			arg0 = args[0].(time.Duration)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_SetTimeout_Call) Return() *MockAptosRpcClient_SetTimeout_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAptosRpcClient_SetTimeout_Call) RunAndReturn(run func(timeout time.Duration)) *MockAptosRpcClient_SetTimeout_Call {
	_c.Run(run)
	return _c
}

// SimulateTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) SimulateTransaction(rawTxn *aptos.RawTransaction, sender aptos.TransactionSigner, options ...any) ([]*api.UserTransaction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(rawTxn, sender, options)
	} else {
		tmpRet = _mock.Called(rawTxn, sender)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SimulateTransaction")
	}

	var r0 []*api.UserTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...any) ([]*api.UserTransaction, error)); ok {
		return returnFunc(rawTxn, sender, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...any) []*api.UserTransaction); ok {
		r0 = returnFunc(rawTxn, sender, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.UserTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*aptos.RawTransaction, aptos.TransactionSigner, ...any) error); ok {
		r1 = returnFunc(rawTxn, sender, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_SimulateTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateTransaction'
type MockAptosRpcClient_SimulateTransaction_Call struct {
	*mock.Call
}

// SimulateTransaction is a helper method to define mock.On call
//   - rawTxn *aptos.RawTransaction
//   - sender aptos.TransactionSigner
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) SimulateTransaction(rawTxn interface{}, sender interface{}, options ...interface{}) *MockAptosRpcClient_SimulateTransaction_Call {
	return &MockAptosRpcClient_SimulateTransaction_Call{Call: _e.mock.On("SimulateTransaction",
		append([]interface{}{rawTxn, sender}, options...)...)}
}

func (_c *MockAptosRpcClient_SimulateTransaction_Call) Run(run func(rawTxn *aptos.RawTransaction, sender aptos.TransactionSigner, options ...any)) *MockAptosRpcClient_SimulateTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aptos.RawTransaction
		if args[0] != nil {
			arg0 = args[0].(*aptos.RawTransaction)
		}
		var arg1 aptos.TransactionSigner
		if args[1] != nil {
			arg1 = args[1].(aptos.TransactionSigner)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_SimulateTransaction_Call) Return(userTransactions []*api.UserTransaction, err error) *MockAptosRpcClient_SimulateTransaction_Call {
	_c.Call.Return(userTransactions, err)
	return _c
}

func (_c *MockAptosRpcClient_SimulateTransaction_Call) RunAndReturn(run func(rawTxn *aptos.RawTransaction, sender aptos.TransactionSigner, options ...any) ([]*api.UserTransaction, error)) *MockAptosRpcClient_SimulateTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SimulateTransactionMultiAgent provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) SimulateTransactionMultiAgent(rawTxn *aptos.RawTransactionWithData, sender aptos.TransactionSigner, options ...any) ([]*api.UserTransaction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(rawTxn, sender, options)
	} else {
		tmpRet = _mock.Called(rawTxn, sender)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SimulateTransactionMultiAgent")
	}

	var r0 []*api.UserTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*aptos.RawTransactionWithData, aptos.TransactionSigner, ...any) ([]*api.UserTransaction, error)); ok {
		return returnFunc(rawTxn, sender, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(*aptos.RawTransactionWithData, aptos.TransactionSigner, ...any) []*api.UserTransaction); ok {
		r0 = returnFunc(rawTxn, sender, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.UserTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*aptos.RawTransactionWithData, aptos.TransactionSigner, ...any) error); ok {
		r1 = returnFunc(rawTxn, sender, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_SimulateTransactionMultiAgent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulateTransactionMultiAgent'
type MockAptosRpcClient_SimulateTransactionMultiAgent_Call struct {
	*mock.Call
}

// SimulateTransactionMultiAgent is a helper method to define mock.On call
//   - rawTxn *aptos.RawTransactionWithData
//   - sender aptos.TransactionSigner
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) SimulateTransactionMultiAgent(rawTxn interface{}, sender interface{}, options ...interface{}) *MockAptosRpcClient_SimulateTransactionMultiAgent_Call {
	return &MockAptosRpcClient_SimulateTransactionMultiAgent_Call{Call: _e.mock.On("SimulateTransactionMultiAgent",
		append([]interface{}{rawTxn, sender}, options...)...)}
}

func (_c *MockAptosRpcClient_SimulateTransactionMultiAgent_Call) Run(run func(rawTxn *aptos.RawTransactionWithData, sender aptos.TransactionSigner, options ...any)) *MockAptosRpcClient_SimulateTransactionMultiAgent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aptos.RawTransactionWithData
		if args[0] != nil {
			arg0 = args[0].(*aptos.RawTransactionWithData)
		}
		var arg1 aptos.TransactionSigner
		if args[1] != nil {
			arg1 = args[1].(aptos.TransactionSigner)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_SimulateTransactionMultiAgent_Call) Return(userTransactions []*api.UserTransaction, err error) *MockAptosRpcClient_SimulateTransactionMultiAgent_Call {
	_c.Call.Return(userTransactions, err)
	return _c
}

func (_c *MockAptosRpcClient_SimulateTransactionMultiAgent_Call) RunAndReturn(run func(rawTxn *aptos.RawTransactionWithData, sender aptos.TransactionSigner, options ...any) ([]*api.UserTransaction, error)) *MockAptosRpcClient_SimulateTransactionMultiAgent_Call {
	_c.Call.Return(run)
	return _c
}

// SubmitTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) SubmitTransaction(signedTransaction *aptos.SignedTransaction) (*api.SubmitTransactionResponse, error) {
	ret := _mock.Called(signedTransaction)

	if len(ret) == 0 {
		panic("no return value specified for SubmitTransaction")
	}

	var r0 *api.SubmitTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*aptos.SignedTransaction) (*api.SubmitTransactionResponse, error)); ok {
		return returnFunc(signedTransaction)
	}
	if returnFunc, ok := ret.Get(0).(func(*aptos.SignedTransaction) *api.SubmitTransactionResponse); ok {
		r0 = returnFunc(signedTransaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.SubmitTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*aptos.SignedTransaction) error); ok {
		r1 = returnFunc(signedTransaction)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_SubmitTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitTransaction'
type MockAptosRpcClient_SubmitTransaction_Call struct {
	*mock.Call
}

// SubmitTransaction is a helper method to define mock.On call
//   - signedTransaction *aptos.SignedTransaction
func (_e *MockAptosRpcClient_Expecter) SubmitTransaction(signedTransaction interface{}) *MockAptosRpcClient_SubmitTransaction_Call {
	return &MockAptosRpcClient_SubmitTransaction_Call{Call: _e.mock.On("SubmitTransaction", signedTransaction)}
}

func (_c *MockAptosRpcClient_SubmitTransaction_Call) Run(run func(signedTransaction *aptos.SignedTransaction)) *MockAptosRpcClient_SubmitTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aptos.SignedTransaction
		if args[0] != nil {
			arg0 = args[0].(*aptos.SignedTransaction)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_SubmitTransaction_Call) Return(v *api.SubmitTransactionResponse, err error) *MockAptosRpcClient_SubmitTransaction_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockAptosRpcClient_SubmitTransaction_Call) RunAndReturn(run func(signedTransaction *aptos.SignedTransaction) (*api.SubmitTransactionResponse, error)) *MockAptosRpcClient_SubmitTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionByHash provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) TransactionByHash(txnHash string) (*api.Transaction, error) {
	ret := _mock.Called(txnHash)

	if len(ret) == 0 {
		panic("no return value specified for TransactionByHash")
	}

	var r0 *api.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*api.Transaction, error)); ok {
		return returnFunc(txnHash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *api.Transaction); ok {
		r0 = returnFunc(txnHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(txnHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_TransactionByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionByHash'
type MockAptosRpcClient_TransactionByHash_Call struct {
	*mock.Call
}

// TransactionByHash is a helper method to define mock.On call
//   - txnHash string
func (_e *MockAptosRpcClient_Expecter) TransactionByHash(txnHash interface{}) *MockAptosRpcClient_TransactionByHash_Call {
	return &MockAptosRpcClient_TransactionByHash_Call{Call: _e.mock.On("TransactionByHash", txnHash)}
}

func (_c *MockAptosRpcClient_TransactionByHash_Call) Run(run func(txnHash string)) *MockAptosRpcClient_TransactionByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_TransactionByHash_Call) Return(transaction *api.Transaction, err error) *MockAptosRpcClient_TransactionByHash_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockAptosRpcClient_TransactionByHash_Call) RunAndReturn(run func(txnHash string) (*api.Transaction, error)) *MockAptosRpcClient_TransactionByHash_Call {
	_c.Call.Return(run)
	return _c
}

// TransactionByVersion provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) TransactionByVersion(version uint64) (*api.CommittedTransaction, error) {
	ret := _mock.Called(version)

	if len(ret) == 0 {
		panic("no return value specified for TransactionByVersion")
	}

	var r0 *api.CommittedTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(uint64) (*api.CommittedTransaction, error)); ok {
		return returnFunc(version)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *api.CommittedTransaction); ok {
		r0 = returnFunc(version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.CommittedTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) error); ok {
		r1 = returnFunc(version)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_TransactionByVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransactionByVersion'
type MockAptosRpcClient_TransactionByVersion_Call struct {
	*mock.Call
}

// TransactionByVersion is a helper method to define mock.On call
//   - version uint64
func (_e *MockAptosRpcClient_Expecter) TransactionByVersion(version interface{}) *MockAptosRpcClient_TransactionByVersion_Call {
	return &MockAptosRpcClient_TransactionByVersion_Call{Call: _e.mock.On("TransactionByVersion", version)}
}

func (_c *MockAptosRpcClient_TransactionByVersion_Call) Run(run func(version uint64)) *MockAptosRpcClient_TransactionByVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_TransactionByVersion_Call) Return(committedTransaction *api.CommittedTransaction, err error) *MockAptosRpcClient_TransactionByVersion_Call {
	_c.Call.Return(committedTransaction, err)
	return _c
}

func (_c *MockAptosRpcClient_TransactionByVersion_Call) RunAndReturn(run func(version uint64) (*api.CommittedTransaction, error)) *MockAptosRpcClient_TransactionByVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Transactions provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) Transactions(start *uint64, limit *uint64) ([]*api.CommittedTransaction, error) {
	ret := _mock.Called(start, limit)

	if len(ret) == 0 {
		panic("no return value specified for Transactions")
	}

	var r0 []*api.CommittedTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) ([]*api.CommittedTransaction, error)); ok {
		return returnFunc(start, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(*uint64, *uint64) []*api.CommittedTransaction); ok {
		r0 = returnFunc(start, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*api.CommittedTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*uint64, *uint64) error); ok {
		r1 = returnFunc(start, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_Transactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transactions'
type MockAptosRpcClient_Transactions_Call struct {
	*mock.Call
}

// Transactions is a helper method to define mock.On call
//   - start *uint64
//   - limit *uint64
func (_e *MockAptosRpcClient_Expecter) Transactions(start interface{}, limit interface{}) *MockAptosRpcClient_Transactions_Call {
	return &MockAptosRpcClient_Transactions_Call{Call: _e.mock.On("Transactions", start, limit)}
}

func (_c *MockAptosRpcClient_Transactions_Call) Run(run func(start *uint64, limit *uint64)) *MockAptosRpcClient_Transactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *uint64
		if args[0] != nil {
			arg0 = args[0].(*uint64)
		}
		var arg1 *uint64
		if args[1] != nil {
			arg1 = args[1].(*uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_Transactions_Call) Return(committedTransactions []*api.CommittedTransaction, err error) *MockAptosRpcClient_Transactions_Call {
	_c.Call.Return(committedTransactions, err)
	return _c
}

func (_c *MockAptosRpcClient_Transactions_Call) RunAndReturn(run func(start *uint64, limit *uint64) ([]*api.CommittedTransaction, error)) *MockAptosRpcClient_Transactions_Call {
	_c.Call.Return(run)
	return _c
}

// View provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) View(payload *aptos.ViewPayload, ledgerVersion ...uint64) ([]any, error) {
	var tmpRet mock.Arguments
	if len(ledgerVersion) > 0 {
		tmpRet = _mock.Called(payload, ledgerVersion)
	} else {
		tmpRet = _mock.Called(payload)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for View")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*aptos.ViewPayload, ...uint64) ([]any, error)); ok {
		return returnFunc(payload, ledgerVersion...)
	}
	if returnFunc, ok := ret.Get(0).(func(*aptos.ViewPayload, ...uint64) []any); ok {
		r0 = returnFunc(payload, ledgerVersion...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*aptos.ViewPayload, ...uint64) error); ok {
		r1 = returnFunc(payload, ledgerVersion...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_View_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'View'
type MockAptosRpcClient_View_Call struct {
	*mock.Call
}

// View is a helper method to define mock.On call
//   - payload *aptos.ViewPayload
//   - ledgerVersion ...uint64
func (_e *MockAptosRpcClient_Expecter) View(payload interface{}, ledgerVersion ...interface{}) *MockAptosRpcClient_View_Call {
	return &MockAptosRpcClient_View_Call{Call: _e.mock.On("View",
		append([]interface{}{payload}, ledgerVersion...)...)}
}

func (_c *MockAptosRpcClient_View_Call) Run(run func(payload *aptos.ViewPayload, ledgerVersion ...uint64)) *MockAptosRpcClient_View_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *aptos.ViewPayload
		if args[0] != nil {
			arg0 = args[0].(*aptos.ViewPayload)
		}
		var arg1 []uint64
		var variadicArgs []uint64
		if len(args) > 1 {
			variadicArgs = args[1].([]uint64)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_View_Call) Return(vs []any, err error) *MockAptosRpcClient_View_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockAptosRpcClient_View_Call) RunAndReturn(run func(payload *aptos.ViewPayload, ledgerVersion ...uint64) ([]any, error)) *MockAptosRpcClient_View_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForTransaction provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) WaitForTransaction(txnHash string, options ...any) (*api.UserTransaction, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(txnHash, options)
	} else {
		tmpRet = _mock.Called(txnHash)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WaitForTransaction")
	}

	var r0 *api.UserTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...any) (*api.UserTransaction, error)); ok {
		return returnFunc(txnHash, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...any) *api.UserTransaction); ok {
		r0 = returnFunc(txnHash, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.UserTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...any) error); ok {
		r1 = returnFunc(txnHash, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_WaitForTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForTransaction'
type MockAptosRpcClient_WaitForTransaction_Call struct {
	*mock.Call
}

// WaitForTransaction is a helper method to define mock.On call
//   - txnHash string
//   - options ...any
func (_e *MockAptosRpcClient_Expecter) WaitForTransaction(txnHash interface{}, options ...interface{}) *MockAptosRpcClient_WaitForTransaction_Call {
	return &MockAptosRpcClient_WaitForTransaction_Call{Call: _e.mock.On("WaitForTransaction",
		append([]interface{}{txnHash}, options...)...)}
}

func (_c *MockAptosRpcClient_WaitForTransaction_Call) Run(run func(txnHash string, options ...any)) *MockAptosRpcClient_WaitForTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_WaitForTransaction_Call) Return(userTransaction *api.UserTransaction, err error) *MockAptosRpcClient_WaitForTransaction_Call {
	_c.Call.Return(userTransaction, err)
	return _c
}

func (_c *MockAptosRpcClient_WaitForTransaction_Call) RunAndReturn(run func(txnHash string, options ...any) (*api.UserTransaction, error)) *MockAptosRpcClient_WaitForTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// WaitTransactionByHash provides a mock function for the type MockAptosRpcClient
func (_mock *MockAptosRpcClient) WaitTransactionByHash(txnHash string) (*api.Transaction, error) {
	ret := _mock.Called(txnHash)

	if len(ret) == 0 {
		panic("no return value specified for WaitTransactionByHash")
	}

	var r0 *api.Transaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*api.Transaction, error)); ok {
		return returnFunc(txnHash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *api.Transaction); ok {
		r0 = returnFunc(txnHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.Transaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(txnHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAptosRpcClient_WaitTransactionByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitTransactionByHash'
type MockAptosRpcClient_WaitTransactionByHash_Call struct {
	*mock.Call
}

// WaitTransactionByHash is a helper method to define mock.On call
//   - txnHash string
func (_e *MockAptosRpcClient_Expecter) WaitTransactionByHash(txnHash interface{}) *MockAptosRpcClient_WaitTransactionByHash_Call {
	return &MockAptosRpcClient_WaitTransactionByHash_Call{Call: _e.mock.On("WaitTransactionByHash", txnHash)}
}

func (_c *MockAptosRpcClient_WaitTransactionByHash_Call) Run(run func(txnHash string)) *MockAptosRpcClient_WaitTransactionByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAptosRpcClient_WaitTransactionByHash_Call) Return(transaction *api.Transaction, err error) *MockAptosRpcClient_WaitTransactionByHash_Call {
	_c.Call.Return(transaction, err)
	return _c
}

func (_c *MockAptosRpcClient_WaitTransactionByHash_Call) RunAndReturn(run func(txnHash string) (*api.Transaction, error)) *MockAptosRpcClient_WaitTransactionByHash_Call {
	_c.Call.Return(run)
	return _c
}
