// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/aptos-labs/aptos-go-sdk"
	"github.com/aptos-labs/aptos-go-sdk/crypto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTransactionSigner creates a new instance of MockTransactionSigner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionSigner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionSigner {
	mock := &MockTransactionSigner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionSigner is an autogenerated mock type for the TransactionSigner type
type MockTransactionSigner struct {
	mock.Mock
}

type MockTransactionSigner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionSigner) EXPECT() *MockTransactionSigner_Expecter {
	return &MockTransactionSigner_Expecter{mock: &_m.Mock}
}

// AccountAddress provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) AccountAddress() aptos.AccountAddress {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AccountAddress")
	}

	var r0 aptos.AccountAddress
	if returnFunc, ok := ret.Get(0).(func() aptos.AccountAddress); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(aptos.AccountAddress)
		}
	}
	return r0
}

// MockTransactionSigner_AccountAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccountAddress'
type MockTransactionSigner_AccountAddress_Call struct {
	*mock.Call
}

// AccountAddress is a helper method to define mock.On call
func (_e *MockTransactionSigner_Expecter) AccountAddress() *MockTransactionSigner_AccountAddress_Call {
	return &MockTransactionSigner_AccountAddress_Call{Call: _e.mock.On("AccountAddress")}
}

func (_c *MockTransactionSigner_AccountAddress_Call) Run(run func()) *MockTransactionSigner_AccountAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionSigner_AccountAddress_Call) Return(v aptos.AccountAddress) *MockTransactionSigner_AccountAddress_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockTransactionSigner_AccountAddress_Call) RunAndReturn(run func() aptos.AccountAddress) *MockTransactionSigner_AccountAddress_Call {
	_c.Call.Return(run)
	return _c
}

// AuthKey provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) AuthKey() *crypto.AuthenticationKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthKey")
	}

	var r0 *crypto.AuthenticationKey
	if returnFunc, ok := ret.Get(0).(func() *crypto.AuthenticationKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.AuthenticationKey)
		}
	}
	return r0
}

// MockTransactionSigner_AuthKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthKey'
type MockTransactionSigner_AuthKey_Call struct {
	*mock.Call
}

// AuthKey is a helper method to define mock.On call
func (_e *MockTransactionSigner_Expecter) AuthKey() *MockTransactionSigner_AuthKey_Call {
	return &MockTransactionSigner_AuthKey_Call{Call: _e.mock.On("AuthKey")}
}

func (_c *MockTransactionSigner_AuthKey_Call) Run(run func()) *MockTransactionSigner_AuthKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionSigner_AuthKey_Call) Return(authenticationKey *crypto.AuthenticationKey) *MockTransactionSigner_AuthKey_Call {
	_c.Call.Return(authenticationKey)
	return _c
}

func (_c *MockTransactionSigner_AuthKey_Call) RunAndReturn(run func() *crypto.AuthenticationKey) *MockTransactionSigner_AuthKey_Call {
	_c.Call.Return(run)
	return _c
}

// PubKey provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) PubKey() crypto.PublicKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PubKey")
	}

	var r0 crypto.PublicKey
	if returnFunc, ok := ret.Get(0).(func() crypto.PublicKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PublicKey)
		}
	}
	return r0
}

// MockTransactionSigner_PubKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PubKey'
type MockTransactionSigner_PubKey_Call struct {
	*mock.Call
}

// PubKey is a helper method to define mock.On call
func (_e *MockTransactionSigner_Expecter) PubKey() *MockTransactionSigner_PubKey_Call {
	return &MockTransactionSigner_PubKey_Call{Call: _e.mock.On("PubKey")}
}

func (_c *MockTransactionSigner_PubKey_Call) Run(run func()) *MockTransactionSigner_PubKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionSigner_PubKey_Call) Return(publicKey crypto.PublicKey) *MockTransactionSigner_PubKey_Call {
	_c.Call.Return(publicKey)
	return _c
}

func (_c *MockTransactionSigner_PubKey_Call) RunAndReturn(run func() crypto.PublicKey) *MockTransactionSigner_PubKey_Call {
	_c.Call.Return(run)
	return _c
}

// Sign provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) Sign(msg []byte) (*crypto.AccountAuthenticator, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for Sign")
	}

	var r0 *crypto.AccountAuthenticator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (*crypto.AccountAuthenticator, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) *crypto.AccountAuthenticator); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.AccountAuthenticator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionSigner_Sign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sign'
type MockTransactionSigner_Sign_Call struct {
	*mock.Call
}

// Sign is a helper method to define mock.On call
//   - msg []byte
func (_e *MockTransactionSigner_Expecter) Sign(msg interface{}) *MockTransactionSigner_Sign_Call {
	return &MockTransactionSigner_Sign_Call{Call: _e.mock.On("Sign", msg)}
}

func (_c *MockTransactionSigner_Sign_Call) Run(run func(msg []byte)) *MockTransactionSigner_Sign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionSigner_Sign_Call) Return(authenticator *crypto.AccountAuthenticator, err error) *MockTransactionSigner_Sign_Call {
	_c.Call.Return(authenticator, err)
	return _c
}

func (_c *MockTransactionSigner_Sign_Call) RunAndReturn(run func(msg []byte) (*crypto.AccountAuthenticator, error)) *MockTransactionSigner_Sign_Call {
	_c.Call.Return(run)
	return _c
}

// SignMessage provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) SignMessage(msg []byte) (crypto.Signature, error) {
	ret := _mock.Called(msg)

	if len(ret) == 0 {
		panic("no return value specified for SignMessage")
	}

	var r0 crypto.Signature
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (crypto.Signature, error)); ok {
		return returnFunc(msg)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) crypto.Signature); ok {
		r0 = returnFunc(msg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.Signature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(msg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransactionSigner_SignMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignMessage'
type MockTransactionSigner_SignMessage_Call struct {
	*mock.Call
}

// SignMessage is a helper method to define mock.On call
//   - msg []byte
func (_e *MockTransactionSigner_Expecter) SignMessage(msg interface{}) *MockTransactionSigner_SignMessage_Call {
	return &MockTransactionSigner_SignMessage_Call{Call: _e.mock.On("SignMessage", msg)}
}

func (_c *MockTransactionSigner_SignMessage_Call) Run(run func(msg []byte)) *MockTransactionSigner_SignMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransactionSigner_SignMessage_Call) Return(signature crypto.Signature, err error) *MockTransactionSigner_SignMessage_Call {
	_c.Call.Return(signature, err)
	return _c
}

func (_c *MockTransactionSigner_SignMessage_Call) RunAndReturn(run func(msg []byte) (crypto.Signature, error)) *MockTransactionSigner_SignMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SimulationAuthenticator provides a mock function for the type MockTransactionSigner
func (_mock *MockTransactionSigner) SimulationAuthenticator() *crypto.AccountAuthenticator {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SimulationAuthenticator")
	}

	var r0 *crypto.AccountAuthenticator
	if returnFunc, ok := ret.Get(0).(func() *crypto.AccountAuthenticator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*crypto.AccountAuthenticator)
		}
	}
	return r0
}

// MockTransactionSigner_SimulationAuthenticator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulationAuthenticator'
type MockTransactionSigner_SimulationAuthenticator_Call struct {
	*mock.Call
}

// SimulationAuthenticator is a helper method to define mock.On call
func (_e *MockTransactionSigner_Expecter) SimulationAuthenticator() *MockTransactionSigner_SimulationAuthenticator_Call {
	return &MockTransactionSigner_SimulationAuthenticator_Call{Call: _e.mock.On("SimulationAuthenticator")}
}

func (_c *MockTransactionSigner_SimulationAuthenticator_Call) Run(run func()) *MockTransactionSigner_SimulationAuthenticator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTransactionSigner_SimulationAuthenticator_Call) Return(accountAuthenticator *crypto.AccountAuthenticator) *MockTransactionSigner_SimulationAuthenticator_Call {
	_c.Call.Return(accountAuthenticator)
	return _c
}

func (_c *MockTransactionSigner_SimulationAuthenticator_Call) RunAndReturn(run func() *crypto.AccountAuthenticator) *MockTransactionSigner_SimulationAuthenticator_Call {
	_c.Call.Return(run)
	return _c
}
