// Code generated by operations-gen. DO NOT EDIT.

package fee_quoter

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	gobindings "github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/testdata/evm/gobindings/v1_0_0/fee_quoter"
)

var ContractType cldf_deployment.ContractType = "FeeQuoter"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type ConstructorArgs struct {
	StaticConfig                   gobindings.FeeQuoterStaticConfig                     `json:"staticConfig"`
	PriceUpdaters                  []common.Address                                     `json:"priceUpdaters"`
	FeeTokens                      []common.Address                                     `json:"feeTokens"`
	TokenPriceFeeds                []gobindings.FeeQuoterTokenPriceFeedUpdate           `json:"tokenPriceFeeds"`
	TokenTransferFeeConfigArgs     []gobindings.FeeQuoterTokenTransferFeeConfigArgs     `json:"tokenTransferFeeConfigArgs"`
	PremiumMultiplierWeiPerEthArgs []gobindings.FeeQuoterPremiumMultiplierWeiPerEthArgs `json:"premiumMultiplierWeiPerEthArgs"`
	DestChainConfigArgs            []gobindings.FeeQuoterDestChainConfigArgs            `json:"destChainConfigArgs"`
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "fee-quoter:deploy",
	Version:          Version,
	Description:      "Deploys the FeeQuoter contract",
	ContractMetadata: gobindings.FeeQuoterMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM: common.FromHex(gobindings.FeeQuoterMetaData.Bin),
		},
	},
})

func NewWriteUpdatePrices(c gobindings.FeeQuoterInterface) *cld_ops.Operation[contract.FunctionInput[gobindings.InternalPriceUpdates], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[gobindings.InternalPriceUpdates, gobindings.FeeQuoterInterface]{
		Name:         "fee-quoter:update-prices",
		Version:      Version,
		Description:  "Calls updatePrices on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.FeeQuoterMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.FeeQuoterInterface, opts *bind.CallOpts, caller common.Address, args gobindings.InternalPriceUpdates) (bool, error) {
			return contract.IsAuthorizedCaller(c, opts, caller)
		},
		CallContract: func(
			c gobindings.FeeQuoterInterface,
			opts *bind.TransactOpts,
			args gobindings.InternalPriceUpdates,
		) (*types.Transaction, error) {
			return c.UpdatePrices(opts, args)
		},
	})
}
