// Code generated by operations-gen. DO NOT EDIT.

package many_chain_multi_sig

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	gobindings "github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/testdata/evm/gobindings/v1_0_0/many_chain_multi_sig"
)

var ContractType cldf_deployment.ContractType = "ManyChainMultiSig"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type SetConfigArgs struct {
	SignerAddresses []common.Address `json:"signerAddresses"`
	SignerGroups    []uint8          `json:"signerGroups"`
	GroupQuorums    [32]uint8        `json:"groupQuorums"`
	GroupParents    [32]uint8        `json:"groupParents"`
	ClearRoot       bool             `json:"clearRoot"`
}

type SetRootArgs struct {
	Root          [32]byte                                 `json:"root"`
	ValidUntil    uint32                                   `json:"validUntil"`
	Metadata      gobindings.ManyChainMultiSigRootMetadata `json:"metadata"`
	MetadataProof [][32]byte                               `json:"metadataProof"`
	Signatures    []gobindings.ManyChainMultiSigSignature  `json:"signatures"`
}

type ConstructorArgs = struct{}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "many-chain-multi-sig:deploy",
	Version:          Version,
	Description:      "Deploys the ManyChainMultiSig contract",
	ContractMetadata: gobindings.ManyChainMultiSigMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM: common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
		},
	},
})

func NewReadOwner(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, common.Address, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:owner",
		Version:      Version,
		Description:  "Calls owner on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, args struct{}) (common.Address, error) {
			return c.Owner(opts)
		},
	})
}

func NewReadGetRoot(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], gobindings.GetRoot, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, gobindings.GetRoot, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:get-root",
		Version:      Version,
		Description:  "Calls getRoot on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, args struct{}) (gobindings.GetRoot, error) {
			return c.GetRoot(opts)
		},
	})
}

func NewWriteSetConfig(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[SetConfigArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetConfigArgs, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:set-config",
		Version:      Version,
		Description:  "Calls setConfig on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.ManyChainMultiSigMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, caller common.Address, args SetConfigArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.ManyChainMultiSigInterface,
			opts *bind.TransactOpts,
			args SetConfigArgs,
		) (*types.Transaction, error) {
			return c.SetConfig(opts, args.SignerAddresses, args.SignerGroups, args.GroupQuorums, args.GroupParents, args.ClearRoot)
		},
	})
}

func NewWriteSetRoot(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[SetRootArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetRootArgs, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:set-root",
		Version:      Version,
		Description:  "Calls setRoot on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.ManyChainMultiSigMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, caller common.Address, args SetRootArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.ManyChainMultiSigInterface,
			opts *bind.TransactOpts,
			args SetRootArgs,
		) (*types.Transaction, error) {
			return c.SetRoot(opts, args.Root, args.ValidUntil, args.Metadata, args.MetadataProof, args.Signatures)
		},
	})
}

func NewWriteAcceptOwnership(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[struct{}], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[struct{}, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:accept-ownership",
		Version:      Version,
		Description:  "Calls acceptOwnership on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.ManyChainMultiSigMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, caller common.Address, args struct{}) (bool, error) {
			return false, nil
		},
		CallContract: func(
			c gobindings.ManyChainMultiSigInterface,
			opts *bind.TransactOpts,
			args struct{},
		) (*types.Transaction, error) {
			return c.AcceptOwnership(opts)
		},
	})
}
