// Code generated by operations-gen. DO NOT EDIT.

package rbac_timelock

import (
	"math/big"

	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	"github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/contract"
	gobindings "github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/testdata/evm/gobindings/v1_0_0/rbac_timelock"
)

var ContractType cldf_deployment.ContractType = "RBACTimelock"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type ScheduleBatchArgs struct {
	Calls       []gobindings.RBACTimelockCall `json:"calls"`
	Predecessor [32]byte                      `json:"predecessor"`
	Salt        [32]byte                      `json:"salt"`
	Delay       *big.Int                      `json:"delay"`
}

type ConstructorArgs struct {
	MinDelay   *big.Int         `json:"minDelay"`
	Admin      common.Address   `json:"admin"`
	Proposers  []common.Address `json:"proposers"`
	Executors  []common.Address `json:"executors"`
	Cancellers []common.Address `json:"cancellers"`
	Bypassers  []common.Address `json:"bypassers"`
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "rbac-timelock:deploy",
	Version:          Version,
	Description:      "Deploys the RBACTimelock contract",
	ContractMetadata: gobindings.RBACTimelockMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM: common.FromHex(gobindings.RBACTimelockMetaData.Bin),
		},
	},
})

func NewWriteScheduleBatch(c gobindings.RBACTimelockInterface) *cld_ops.Operation[contract.FunctionInput[ScheduleBatchArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[ScheduleBatchArgs, gobindings.RBACTimelockInterface]{
		Name:         "rbac-timelock:schedule-batch",
		Version:      Version,
		Description:  "Calls scheduleBatch on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.RBACTimelockMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.RBACTimelockInterface, opts *bind.CallOpts, caller common.Address, args ScheduleBatchArgs) (bool, error) {
			return contract.HasRole(c, opts, [32]byte{0xb0, 0x9a, 0xa5, 0xae, 0xb3, 0x70, 0x2c, 0xfd, 0x50, 0xb6, 0xb6, 0x2b, 0xc4, 0x53, 0x26, 0x04, 0x93, 0x8f, 0x21, 0x24, 0x8a, 0x27, 0xa1, 0xd5, 0xca, 0x73, 0x60, 0x82, 0xb6, 0x81, 0x9c, 0xc1}, caller)
		},
		CallContract: func(
			c gobindings.RBACTimelockInterface,
			opts *bind.TransactOpts,
			args ScheduleBatchArgs,
		) (*types.Transaction, error) {
			return c.ScheduleBatch(opts, args.Calls, args.Predecessor, args.Salt, args.Delay)
		},
	})
}
