// Code generated by operations-gen. DO NOT EDIT.

package rbac_timelock

import (
	"math/big"

	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"

	gobindings "github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/testdata/evm/gobindings/v1_0_0/rbac_timelock"
)

var ContractType cldf_deployment.ContractType = "RBACTimelock"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type ExecuteBatchArgs struct {
	Calls       []geth_bindings.RBACTimelockCall
	Predecessor [32]byte
	Salt        [32]byte
}

type ConstructorArgs struct {
	MinDelay   *big.Int
	Admin      common.Address
	Proposers  []common.Address
	Executors  []common.Address
	Cancellers []common.Address
	Bypassers  []common.Address
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "rbac-timelock:deploy",
	Version:          Version,
	Description:      "Deploys the RBACTimelock contract",
	ContractMetadata: gobindings.RBACTimelockMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM: common.FromHex(gobindings.RBACTimelockMetaData.Bin),
		},
	},
	Validate: func(ConstructorArgs) error { return nil },
})

func NewWriteExecuteBatch(c gobindings.RBACTimelockInterface) *cld_ops.Operation[contract.FunctionInput[ExecuteBatchArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[ExecuteBatchArgs, gobindings.RBACTimelockInterface]{
		Name:         "rbac-timelock:execute-batch",
		Version:      Version,
		Description:  "Calls executeBatch on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.RBACTimelockMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.RBACTimelockInterface, opts *bind.CallOpts, caller common.Address, args ExecuteBatchArgs) (bool, error) {
			return contract.HasRole(c, opts, [32]byte{0xd8, 0xaa, 0x0f, 0x31, 0x94, 0x97, 0x1a, 0x2a, 0x11, 0x66, 0x79, 0xf7, 0xc2, 0x09, 0x0f, 0x69, 0x39, 0xc8, 0xd4, 0xe0, 0x1a, 0x2a, 0x8d, 0x7e, 0x41, 0xd5, 0x5e, 0x53, 0x51, 0x46, 0x9e, 0x63}, caller)
		},
		Validate: func(ExecuteBatchArgs) error { return nil },
		CallContract: func(
			c gobindings.RBACTimelockInterface,
			opts *bind.TransactOpts,
			args ExecuteBatchArgs,
		) (*types.Transaction, error) {
			return c.ExecuteBatch(opts, args.Calls, args.Predecessor, args.Salt)
		},
	})
}
