// Code generated by operations-gen. DO NOT EDIT.

package workflow_registry

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	gobindings "github.com/smartcontractkit/chainlink-deployments-framework/tools/operations-gen/testdata/evm/gobindings/v2_0_0/workflow_registry"
)

var ContractType cldf_deployment.ContractType = "WorkflowRegistry"
var Version = semver.MustParse("2.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type UpsertWorkflowArgs struct {
	WorkflowName string   `json:"workflowName"`
	Tag          string   `json:"tag"`
	WorkflowId   [32]byte `json:"workflowId"`
	Status       uint8    `json:"status"`
	DonFamily    string   `json:"donFamily"`
	BinaryUrl    string   `json:"binaryUrl"`
	ConfigUrl    string   `json:"configUrl"`
	Attributes   []byte   `json:"attributes"`
	KeepAlive    bool     `json:"keepAlive"`
}

type ActivateWorkflowArgs struct {
	WorkflowId [32]byte `json:"workflowId"`
	DonFamily  string   `json:"donFamily"`
}

type BatchActivateWorkflowsArgs struct {
	WorkflowIds [][32]byte `json:"workflowIds"`
	DonFamily   string     `json:"donFamily"`
}

func NewWriteUpsertWorkflow(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[UpsertWorkflowArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[UpsertWorkflowArgs, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:upsert-workflow",
		Version:      Version,
		Description:  "Calls upsertWorkflow on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args UpsertWorkflowArgs) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, [][32]byte{args.WorkflowId})
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args UpsertWorkflowArgs,
		) (*types.Transaction, error) {
			return c.UpsertWorkflow(opts, args.WorkflowName, args.Tag, args.WorkflowId, args.Status, args.DonFamily, args.BinaryUrl, args.ConfigUrl, args.Attributes, args.KeepAlive)
		},
	})
}

func NewWriteActivateWorkflow(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[ActivateWorkflowArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[ActivateWorkflowArgs, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:activate-workflow",
		Version:      Version,
		Description:  "Calls activateWorkflow on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args ActivateWorkflowArgs) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, [][32]byte{args.WorkflowId})
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args ActivateWorkflowArgs,
		) (*types.Transaction, error) {
			return c.ActivateWorkflow(opts, args.WorkflowId, args.DonFamily)
		},
	})
}

func NewWritePauseWorkflow(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[[32]byte], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[[32]byte, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:pause-workflow",
		Version:      Version,
		Description:  "Calls pauseWorkflow on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args [32]byte) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, [][32]byte{args})
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args [32]byte,
		) (*types.Transaction, error) {
			return c.PauseWorkflow(opts, args)
		},
	})
}

func NewWriteBatchPauseWorkflows(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[[][32]byte], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[[][32]byte, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:batch-pause-workflows",
		Version:      Version,
		Description:  "Calls batchPauseWorkflows on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args [][32]byte) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args [][32]byte,
		) (*types.Transaction, error) {
			return c.BatchPauseWorkflows(opts, args)
		},
	})
}

func NewWriteBatchActivateWorkflows(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[BatchActivateWorkflowsArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[BatchActivateWorkflowsArgs, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:batch-activate-workflows",
		Version:      Version,
		Description:  "Calls batchActivateWorkflows on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args BatchActivateWorkflowsArgs) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, args.WorkflowIds)
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args BatchActivateWorkflowsArgs,
		) (*types.Transaction, error) {
			return c.BatchActivateWorkflows(opts, args.WorkflowIds, args.DonFamily)
		},
	})
}

func NewWriteDeleteWorkflow(c gobindings.WorkflowRegistryInterface) *cld_ops.Operation[contract.FunctionInput[[32]byte], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[[32]byte, gobindings.WorkflowRegistryInterface]{
		Name:         "workflow-registry:delete-workflow",
		Version:      Version,
		Description:  "Calls deleteWorkflow on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.WorkflowRegistryMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.WorkflowRegistryInterface, opts *bind.CallOpts, caller common.Address, args [32]byte) (bool, error) {
			return contract.IsWorkflowsOwner(c, opts, caller, [][32]byte{args})
		},
		CallContract: func(
			c gobindings.WorkflowRegistryInterface,
			opts *bind.TransactOpts,
			args [32]byte,
		) (*types.Transaction, error) {
			return c.DeleteWorkflow(opts, args)
		},
	})
}
