// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/analyzer"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/analyzer/annotated"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/analyzer/annotation"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAnalyzedProposal creates a new instance of MockAnalyzedProposal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAnalyzedProposal(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAnalyzedProposal {
	mock := &MockAnalyzedProposal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAnalyzedProposal is an autogenerated mock type for the AnalyzedProposal type
type MockAnalyzedProposal struct {
	mock.Mock
}

type MockAnalyzedProposal_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAnalyzedProposal) EXPECT() *MockAnalyzedProposal_Expecter {
	return &MockAnalyzedProposal_Expecter{mock: &_m.Mock}
}

// Annotations provides a mock function for the type MockAnalyzedProposal
func (_mock *MockAnalyzedProposal) Annotations() annotation.Annotations {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Annotations")
	}

	var r0 annotation.Annotations
	if returnFunc, ok := ret.Get(0).(func() annotation.Annotations); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(annotation.Annotations)
		}
	}
	return r0
}

// MockAnalyzedProposal_Annotations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Annotations'
type MockAnalyzedProposal_Annotations_Call struct {
	*mock.Call
}

// Annotations is a helper method to define mock.On call
func (_e *MockAnalyzedProposal_Expecter) Annotations() *MockAnalyzedProposal_Annotations_Call {
	return &MockAnalyzedProposal_Annotations_Call{Call: _e.mock.On("Annotations")}
}

func (_c *MockAnalyzedProposal_Annotations_Call) Run(run func()) *MockAnalyzedProposal_Annotations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnalyzedProposal_Annotations_Call) Return(annotations annotation.Annotations) *MockAnalyzedProposal_Annotations_Call {
	_c.Call.Return(annotations)
	return _c
}

func (_c *MockAnalyzedProposal_Annotations_Call) RunAndReturn(run func() annotation.Annotations) *MockAnalyzedProposal_Annotations_Call {
	_c.Call.Return(run)
	return _c
}

// BatchOperations provides a mock function for the type MockAnalyzedProposal
func (_mock *MockAnalyzedProposal) BatchOperations() analyzer.AnalyzedBatchOperations {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BatchOperations")
	}

	var r0 analyzer.AnalyzedBatchOperations
	if returnFunc, ok := ret.Get(0).(func() analyzer.AnalyzedBatchOperations); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyzer.AnalyzedBatchOperations)
		}
	}
	return r0
}

// MockAnalyzedProposal_BatchOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchOperations'
type MockAnalyzedProposal_BatchOperations_Call struct {
	*mock.Call
}

// BatchOperations is a helper method to define mock.On call
func (_e *MockAnalyzedProposal_Expecter) BatchOperations() *MockAnalyzedProposal_BatchOperations_Call {
	return &MockAnalyzedProposal_BatchOperations_Call{Call: _e.mock.On("BatchOperations")}
}

func (_c *MockAnalyzedProposal_BatchOperations_Call) Run(run func()) *MockAnalyzedProposal_BatchOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAnalyzedProposal_BatchOperations_Call) Return(analyzedBatchOperations analyzer.AnalyzedBatchOperations) *MockAnalyzedProposal_BatchOperations_Call {
	_c.Call.Return(analyzedBatchOperations)
	return _c
}

func (_c *MockAnalyzedProposal_BatchOperations_Call) RunAndReturn(run func() analyzer.AnalyzedBatchOperations) *MockAnalyzedProposal_BatchOperations_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockAnalyzedProposal
func (_mock *MockAnalyzedProposal) Filter(preds ...annotated.AnnotationPredicate) annotation.Annotations {
	var tmpRet mock.Arguments
	if len(preds) > 0 {
		tmpRet = _mock.Called(preds)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 annotation.Annotations
	if returnFunc, ok := ret.Get(0).(func(...annotated.AnnotationPredicate) annotation.Annotations); ok {
		r0 = returnFunc(preds...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(annotation.Annotations)
		}
	}
	return r0
}

// MockAnalyzedProposal_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockAnalyzedProposal_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - preds ...annotated.AnnotationPredicate
func (_e *MockAnalyzedProposal_Expecter) Filter(preds ...interface{}) *MockAnalyzedProposal_Filter_Call {
	return &MockAnalyzedProposal_Filter_Call{Call: _e.mock.On("Filter",
		append([]interface{}{}, preds...)...)}
}

func (_c *MockAnalyzedProposal_Filter_Call) Run(run func(preds ...annotated.AnnotationPredicate)) *MockAnalyzedProposal_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []annotated.AnnotationPredicate
		var variadicArgs []annotated.AnnotationPredicate
		if len(args) > 0 {
			variadicArgs = args[0].([]annotated.AnnotationPredicate)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockAnalyzedProposal_Filter_Call) Return(annotations annotation.Annotations) *MockAnalyzedProposal_Filter_Call {
	_c.Call.Return(annotations)
	return _c
}

func (_c *MockAnalyzedProposal_Filter_Call) RunAndReturn(run func(preds ...annotated.AnnotationPredicate) annotation.Annotations) *MockAnalyzedProposal_Filter_Call {
	_c.Call.Return(run)
	return _c
}
