// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/analyzer"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/decoder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBatchOperationAnalyzer creates a new instance of MockBatchOperationAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBatchOperationAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBatchOperationAnalyzer {
	mock := &MockBatchOperationAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBatchOperationAnalyzer is an autogenerated mock type for the BatchOperationAnalyzer type
type MockBatchOperationAnalyzer struct {
	mock.Mock
}

type MockBatchOperationAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBatchOperationAnalyzer) EXPECT() *MockBatchOperationAnalyzer_Expecter {
	return &MockBatchOperationAnalyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function for the type MockBatchOperationAnalyzer
func (_mock *MockBatchOperationAnalyzer) Analyze(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation) (analyzer.Annotations, error) {
	ret := _mock.Called(ctx, req, operation)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 analyzer.Annotations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest, decoder.DecodedBatchOperation) (analyzer.Annotations, error)); ok {
		return returnFunc(ctx, req, operation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest, decoder.DecodedBatchOperation) analyzer.Annotations); ok {
		r0 = returnFunc(ctx, req, operation)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(analyzer.Annotations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, analyzer.AnalyzeRequest, decoder.DecodedBatchOperation) error); ok {
		r1 = returnFunc(ctx, req, operation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBatchOperationAnalyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type MockBatchOperationAnalyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest
//   - operation decoder.DecodedBatchOperation
func (_e *MockBatchOperationAnalyzer_Expecter) Analyze(ctx interface{}, req interface{}, operation interface{}) *MockBatchOperationAnalyzer_Analyze_Call {
	return &MockBatchOperationAnalyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, req, operation)}
}

func (_c *MockBatchOperationAnalyzer_Analyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation)) *MockBatchOperationAnalyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest)
		}
		var arg2 decoder.DecodedBatchOperation
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedBatchOperation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchOperationAnalyzer_Analyze_Call) Return(annotations analyzer.Annotations, err error) *MockBatchOperationAnalyzer_Analyze_Call {
	_c.Call.Return(annotations, err)
	return _c
}

func (_c *MockBatchOperationAnalyzer_Analyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation) (analyzer.Annotations, error)) *MockBatchOperationAnalyzer_Analyze_Call {
	_c.Call.Return(run)
	return _c
}

// CanAnalyze provides a mock function for the type MockBatchOperationAnalyzer
func (_mock *MockBatchOperationAnalyzer) CanAnalyze(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation) bool {
	ret := _mock.Called(ctx, req, operation)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyze")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest, decoder.DecodedBatchOperation) bool); ok {
		r0 = returnFunc(ctx, req, operation)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockBatchOperationAnalyzer_CanAnalyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyze'
type MockBatchOperationAnalyzer_CanAnalyze_Call struct {
	*mock.Call
}

// CanAnalyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest
//   - operation decoder.DecodedBatchOperation
func (_e *MockBatchOperationAnalyzer_Expecter) CanAnalyze(ctx interface{}, req interface{}, operation interface{}) *MockBatchOperationAnalyzer_CanAnalyze_Call {
	return &MockBatchOperationAnalyzer_CanAnalyze_Call{Call: _e.mock.On("CanAnalyze", ctx, req, operation)}
}

func (_c *MockBatchOperationAnalyzer_CanAnalyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation)) *MockBatchOperationAnalyzer_CanAnalyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest)
		}
		var arg2 decoder.DecodedBatchOperation
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedBatchOperation)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBatchOperationAnalyzer_CanAnalyze_Call) Return(b bool) *MockBatchOperationAnalyzer_CanAnalyze_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockBatchOperationAnalyzer_CanAnalyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest, operation decoder.DecodedBatchOperation) bool) *MockBatchOperationAnalyzer_CanAnalyze_Call {
	_c.Call.Return(run)
	return _c
}

// Dependencies provides a mock function for the type MockBatchOperationAnalyzer
func (_mock *MockBatchOperationAnalyzer) Dependencies() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockBatchOperationAnalyzer_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type MockBatchOperationAnalyzer_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *MockBatchOperationAnalyzer_Expecter) Dependencies() *MockBatchOperationAnalyzer_Dependencies_Call {
	return &MockBatchOperationAnalyzer_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *MockBatchOperationAnalyzer_Dependencies_Call) Run(run func()) *MockBatchOperationAnalyzer_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchOperationAnalyzer_Dependencies_Call) Return(strings []string) *MockBatchOperationAnalyzer_Dependencies_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockBatchOperationAnalyzer_Dependencies_Call) RunAndReturn(run func() []string) *MockBatchOperationAnalyzer_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBatchOperationAnalyzer
func (_mock *MockBatchOperationAnalyzer) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBatchOperationAnalyzer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBatchOperationAnalyzer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBatchOperationAnalyzer_Expecter) ID() *MockBatchOperationAnalyzer_ID_Call {
	return &MockBatchOperationAnalyzer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBatchOperationAnalyzer_ID_Call) Run(run func()) *MockBatchOperationAnalyzer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBatchOperationAnalyzer_ID_Call) Return(s string) *MockBatchOperationAnalyzer_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBatchOperationAnalyzer_ID_Call) RunAndReturn(run func() string) *MockBatchOperationAnalyzer_ID_Call {
	_c.Call.Return(run)
	return _c
}
