// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cremocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockClientRunner creates a new instance of MockClientRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClientRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClientRunner {
	mock := &MockClientRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClientRunner is an autogenerated mock type for the ClientRunner type
type MockClientRunner struct {
	mock.Mock
}

type MockClientRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClientRunner) EXPECT() *MockClientRunner_Expecter {
	return &MockClientRunner_Expecter{mock: &_m.Mock}
}
