// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cremocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/cre"
	mock "github.com/stretchr/testify/mock"
)

// NewMockWorkflowAPI creates a new instance of MockWorkflowAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkflowAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkflowAPI {
	mock := &MockWorkflowAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWorkflowAPI is an autogenerated mock type for the WorkflowAPI type
type MockWorkflowAPI struct {
	mock.Mock
}

type MockWorkflowAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkflowAPI) EXPECT() *MockWorkflowAPI_Expecter {
	return &MockWorkflowAPI_Expecter{mock: &_m.Mock}
}

// DeployWorkflow provides a mock function for the type MockWorkflowAPI
func (_mock *MockWorkflowAPI) DeployWorkflow(ctx context.Context, cfg cre.DeployWorkflowConfig) error {
	ret := _mock.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for DeployWorkflow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cre.DeployWorkflowConfig) error); ok {
		r0 = returnFunc(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkflowAPI_DeployWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeployWorkflow'
type MockWorkflowAPI_DeployWorkflow_Call struct {
	*mock.Call
}

// DeployWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg cre.DeployWorkflowConfig
func (_e *MockWorkflowAPI_Expecter) DeployWorkflow(ctx interface{}, cfg interface{}) *MockWorkflowAPI_DeployWorkflow_Call {
	return &MockWorkflowAPI_DeployWorkflow_Call{Call: _e.mock.On("DeployWorkflow", ctx, cfg)}
}

func (_c *MockWorkflowAPI_DeployWorkflow_Call) Run(run func(ctx context.Context, cfg cre.DeployWorkflowConfig)) *MockWorkflowAPI_DeployWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cre.DeployWorkflowConfig
		if args[1] != nil {
			arg1 = args[1].(cre.DeployWorkflowConfig)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWorkflowAPI_DeployWorkflow_Call) Return(err error) *MockWorkflowAPI_DeployWorkflow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWorkflowAPI_DeployWorkflow_Call) RunAndReturn(run func(ctx context.Context, cfg cre.DeployWorkflowConfig) error) *MockWorkflowAPI_DeployWorkflow_Call {
	_c.Call.Return(run)
	return _c
}
