// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cremocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/cre"
	"github.com/smartcontractkit/chainlink-deployments-framework/cre/cliconfig"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCLIRunner creates a new instance of MockCLIRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCLIRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCLIRunner {
	mock := &MockCLIRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCLIRunner is an autogenerated mock type for the CLIRunner type
type MockCLIRunner struct {
	mock.Mock
}

type MockCLIRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCLIRunner) EXPECT() *MockCLIRunner_Expecter {
	return &MockCLIRunner_Expecter{mock: &_m.Mock}
}

// ContextRegistries provides a mock function for the type MockCLIRunner
func (_mock *MockCLIRunner) ContextRegistries() []cliconfig.ContextRegistryEntry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContextRegistries")
	}

	var r0 []cliconfig.ContextRegistryEntry
	if returnFunc, ok := ret.Get(0).(func() []cliconfig.ContextRegistryEntry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cliconfig.ContextRegistryEntry)
		}
	}
	return r0
}

// MockCLIRunner_ContextRegistries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContextRegistries'
type MockCLIRunner_ContextRegistries_Call struct {
	*mock.Call
}

// ContextRegistries is a helper method to define mock.On call
func (_e *MockCLIRunner_Expecter) ContextRegistries() *MockCLIRunner_ContextRegistries_Call {
	return &MockCLIRunner_ContextRegistries_Call{Call: _e.mock.On("ContextRegistries")}
}

func (_c *MockCLIRunner_ContextRegistries_Call) Run(run func()) *MockCLIRunner_ContextRegistries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCLIRunner_ContextRegistries_Call) Return(contextRegistryEntrys []cliconfig.ContextRegistryEntry) *MockCLIRunner_ContextRegistries_Call {
	_c.Call.Return(contextRegistryEntrys)
	return _c
}

func (_c *MockCLIRunner_ContextRegistries_Call) RunAndReturn(run func() []cliconfig.ContextRegistryEntry) *MockCLIRunner_ContextRegistries_Call {
	_c.Call.Return(run)
	return _c
}

// Run provides a mock function for the type MockCLIRunner
func (_mock *MockCLIRunner) Run(ctx context.Context, args ...string) (*cre.CallResult, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 *cre.CallResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (*cre.CallResult, error)); ok {
		return returnFunc(ctx, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) *cre.CallResult); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cre.CallResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCLIRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCLIRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...string
func (_e *MockCLIRunner_Expecter) Run(ctx interface{}, args ...interface{}) *MockCLIRunner_Run_Call {
	return &MockCLIRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockCLIRunner_Run_Call) Run(run func(ctx context.Context, args ...string)) *MockCLIRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockCLIRunner_Run_Call) Return(callResult *cre.CallResult, err error) *MockCLIRunner_Run_Call {
	_c.Call.Return(callResult, err)
	return _c
}

func (_c *MockCLIRunner_Run_Call) RunAndReturn(run func(ctx context.Context, args ...string) (*cre.CallResult, error)) *MockCLIRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
