// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cremocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/cre"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Call provides a mock function for the type MockRunner
func (_mock *MockRunner) Call(ctx context.Context, args ...string) (*cre.CallResult, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, args)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 *cre.CallResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) (*cre.CallResult, error)); ok {
		return returnFunc(ctx, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) *cre.CallResult); ok {
		r0 = returnFunc(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cre.CallResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRunner_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type MockRunner_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...string
func (_e *MockRunner_Expecter) Call(ctx interface{}, args ...interface{}) *MockRunner_Call_Call {
	return &MockRunner_Call_Call{Call: _e.mock.On("Call",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockRunner_Call_Call) Run(run func(ctx context.Context, args ...string)) *MockRunner_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRunner_Call_Call) Return(callResult *cre.CallResult, err error) *MockRunner_Call_Call {
	_c.Call.Return(callResult, err)
	return _c
}

func (_c *MockRunner_Call_Call) RunAndReturn(run func(ctx context.Context, args ...string) (*cre.CallResult, error)) *MockRunner_Call_Call {
	_c.Call.Return(run)
	return _c
}
