// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer/annotation"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/decoder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProposalAnalyzer creates a new instance of MockProposalAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProposalAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProposalAnalyzer {
	mock := &MockProposalAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProposalAnalyzer is an autogenerated mock type for the ProposalAnalyzer type
type MockProposalAnalyzer struct {
	mock.Mock
}

type MockProposalAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProposalAnalyzer) EXPECT() *MockProposalAnalyzer_Expecter {
	return &MockProposalAnalyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function for the type MockProposalAnalyzer
func (_mock *MockProposalAnalyzer) Analyze(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal) (annotation.Annotations, error) {
	ret := _mock.Called(ctx, req, proposal)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 annotation.Annotations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.ProposalAnalyzeRequest, decoder.DecodedTimelockProposal) (annotation.Annotations, error)); ok {
		return returnFunc(ctx, req, proposal)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.ProposalAnalyzeRequest, decoder.DecodedTimelockProposal) annotation.Annotations); ok {
		r0 = returnFunc(ctx, req, proposal)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(annotation.Annotations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, analyzer.ProposalAnalyzeRequest, decoder.DecodedTimelockProposal) error); ok {
		r1 = returnFunc(ctx, req, proposal)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProposalAnalyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type MockProposalAnalyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.ProposalAnalyzeRequest
//   - proposal decoder.DecodedTimelockProposal
func (_e *MockProposalAnalyzer_Expecter) Analyze(ctx interface{}, req interface{}, proposal interface{}) *MockProposalAnalyzer_Analyze_Call {
	return &MockProposalAnalyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, req, proposal)}
}

func (_c *MockProposalAnalyzer_Analyze_Call) Run(run func(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal)) *MockProposalAnalyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.ProposalAnalyzeRequest
		if args[1] != nil {
			arg1 = args[1].(analyzer.ProposalAnalyzeRequest)
		}
		var arg2 decoder.DecodedTimelockProposal
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedTimelockProposal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProposalAnalyzer_Analyze_Call) Return(annotations annotation.Annotations, err error) *MockProposalAnalyzer_Analyze_Call {
	_c.Call.Return(annotations, err)
	return _c
}

func (_c *MockProposalAnalyzer_Analyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal) (annotation.Annotations, error)) *MockProposalAnalyzer_Analyze_Call {
	_c.Call.Return(run)
	return _c
}

// CanAnalyze provides a mock function for the type MockProposalAnalyzer
func (_mock *MockProposalAnalyzer) CanAnalyze(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal) bool {
	ret := _mock.Called(ctx, req, proposal)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyze")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.ProposalAnalyzeRequest, decoder.DecodedTimelockProposal) bool); ok {
		r0 = returnFunc(ctx, req, proposal)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProposalAnalyzer_CanAnalyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyze'
type MockProposalAnalyzer_CanAnalyze_Call struct {
	*mock.Call
}

// CanAnalyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.ProposalAnalyzeRequest
//   - proposal decoder.DecodedTimelockProposal
func (_e *MockProposalAnalyzer_Expecter) CanAnalyze(ctx interface{}, req interface{}, proposal interface{}) *MockProposalAnalyzer_CanAnalyze_Call {
	return &MockProposalAnalyzer_CanAnalyze_Call{Call: _e.mock.On("CanAnalyze", ctx, req, proposal)}
}

func (_c *MockProposalAnalyzer_CanAnalyze_Call) Run(run func(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal)) *MockProposalAnalyzer_CanAnalyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.ProposalAnalyzeRequest
		if args[1] != nil {
			arg1 = args[1].(analyzer.ProposalAnalyzeRequest)
		}
		var arg2 decoder.DecodedTimelockProposal
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedTimelockProposal)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProposalAnalyzer_CanAnalyze_Call) Return(b bool) *MockProposalAnalyzer_CanAnalyze_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProposalAnalyzer_CanAnalyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.ProposalAnalyzeRequest, proposal decoder.DecodedTimelockProposal) bool) *MockProposalAnalyzer_CanAnalyze_Call {
	_c.Call.Return(run)
	return _c
}

// Dependencies provides a mock function for the type MockProposalAnalyzer
func (_mock *MockProposalAnalyzer) Dependencies() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockProposalAnalyzer_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type MockProposalAnalyzer_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *MockProposalAnalyzer_Expecter) Dependencies() *MockProposalAnalyzer_Dependencies_Call {
	return &MockProposalAnalyzer_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *MockProposalAnalyzer_Dependencies_Call) Run(run func()) *MockProposalAnalyzer_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProposalAnalyzer_Dependencies_Call) Return(strings []string) *MockProposalAnalyzer_Dependencies_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockProposalAnalyzer_Dependencies_Call) RunAndReturn(run func() []string) *MockProposalAnalyzer_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockProposalAnalyzer
func (_mock *MockProposalAnalyzer) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProposalAnalyzer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockProposalAnalyzer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockProposalAnalyzer_Expecter) ID() *MockProposalAnalyzer_ID_Call {
	return &MockProposalAnalyzer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockProposalAnalyzer_ID_Call) Run(run func()) *MockProposalAnalyzer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProposalAnalyzer_ID_Call) Return(s string) *MockProposalAnalyzer_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProposalAnalyzer_ID_Call) RunAndReturn(run func() string) *MockProposalAnalyzer_ID_Call {
	_c.Call.Return(run)
	return _c
}
