// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer/annotation"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/decoder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCallAnalyzer creates a new instance of MockCallAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCallAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCallAnalyzer {
	mock := &MockCallAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCallAnalyzer is an autogenerated mock type for the CallAnalyzer type
type MockCallAnalyzer struct {
	mock.Mock
}

type MockCallAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCallAnalyzer) EXPECT() *MockCallAnalyzer_Expecter {
	return &MockCallAnalyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function for the type MockCallAnalyzer
func (_mock *MockCallAnalyzer) Analyze(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall) (annotation.Annotations, error) {
	ret := _mock.Called(ctx, req, call)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 annotation.Annotations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], decoder.DecodedCall) (annotation.Annotations, error)); ok {
		return returnFunc(ctx, req, call)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], decoder.DecodedCall) annotation.Annotations); ok {
		r0 = returnFunc(ctx, req, call)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(annotation.Annotations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], decoder.DecodedCall) error); ok {
		r1 = returnFunc(ctx, req, call)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCallAnalyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type MockCallAnalyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext]
//   - call decoder.DecodedCall
func (_e *MockCallAnalyzer_Expecter) Analyze(ctx interface{}, req interface{}, call interface{}) *MockCallAnalyzer_Analyze_Call {
	return &MockCallAnalyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, req, call)}
}

func (_c *MockCallAnalyzer_Analyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall)) *MockCallAnalyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext]
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext])
		}
		var arg2 decoder.DecodedCall
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedCall)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCallAnalyzer_Analyze_Call) Return(annotations annotation.Annotations, err error) *MockCallAnalyzer_Analyze_Call {
	_c.Call.Return(annotations, err)
	return _c
}

func (_c *MockCallAnalyzer_Analyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall) (annotation.Annotations, error)) *MockCallAnalyzer_Analyze_Call {
	_c.Call.Return(run)
	return _c
}

// CanAnalyze provides a mock function for the type MockCallAnalyzer
func (_mock *MockCallAnalyzer) CanAnalyze(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall) bool {
	ret := _mock.Called(ctx, req, call)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyze")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], decoder.DecodedCall) bool); ok {
		r0 = returnFunc(ctx, req, call)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockCallAnalyzer_CanAnalyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyze'
type MockCallAnalyzer_CanAnalyze_Call struct {
	*mock.Call
}

// CanAnalyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext]
//   - call decoder.DecodedCall
func (_e *MockCallAnalyzer_Expecter) CanAnalyze(ctx interface{}, req interface{}, call interface{}) *MockCallAnalyzer_CanAnalyze_Call {
	return &MockCallAnalyzer_CanAnalyze_Call{Call: _e.mock.On("CanAnalyze", ctx, req, call)}
}

func (_c *MockCallAnalyzer_CanAnalyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall)) *MockCallAnalyzer_CanAnalyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext]
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext])
		}
		var arg2 decoder.DecodedCall
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedCall)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCallAnalyzer_CanAnalyze_Call) Return(b bool) *MockCallAnalyzer_CanAnalyze_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockCallAnalyzer_CanAnalyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.CallAnalyzerContext], call decoder.DecodedCall) bool) *MockCallAnalyzer_CanAnalyze_Call {
	_c.Call.Return(run)
	return _c
}

// Dependencies provides a mock function for the type MockCallAnalyzer
func (_mock *MockCallAnalyzer) Dependencies() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockCallAnalyzer_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type MockCallAnalyzer_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *MockCallAnalyzer_Expecter) Dependencies() *MockCallAnalyzer_Dependencies_Call {
	return &MockCallAnalyzer_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *MockCallAnalyzer_Dependencies_Call) Run(run func()) *MockCallAnalyzer_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCallAnalyzer_Dependencies_Call) Return(strings []string) *MockCallAnalyzer_Dependencies_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockCallAnalyzer_Dependencies_Call) RunAndReturn(run func() []string) *MockCallAnalyzer_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCallAnalyzer
func (_mock *MockCallAnalyzer) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCallAnalyzer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCallAnalyzer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCallAnalyzer_Expecter) ID() *MockCallAnalyzer_ID_Call {
	return &MockCallAnalyzer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCallAnalyzer_ID_Call) Run(run func()) *MockCallAnalyzer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCallAnalyzer_ID_Call) Return(s string) *MockCallAnalyzer_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCallAnalyzer_ID_Call) RunAndReturn(run func() string) *MockCallAnalyzer_ID_Call {
	_c.Call.Return(run)
	return _c
}
