// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/analyzer/annotation"
	"github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/mcms/proposalanalysis/internal/decoder"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParameterAnalyzer creates a new instance of MockParameterAnalyzer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParameterAnalyzer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParameterAnalyzer {
	mock := &MockParameterAnalyzer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParameterAnalyzer is an autogenerated mock type for the ParameterAnalyzer type
type MockParameterAnalyzer struct {
	mock.Mock
}

type MockParameterAnalyzer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParameterAnalyzer) EXPECT() *MockParameterAnalyzer_Expecter {
	return &MockParameterAnalyzer_Expecter{mock: &_m.Mock}
}

// Analyze provides a mock function for the type MockParameterAnalyzer
func (_mock *MockParameterAnalyzer) Analyze(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter) (annotation.Annotations, error) {
	ret := _mock.Called(ctx, req, param)

	if len(ret) == 0 {
		panic("no return value specified for Analyze")
	}

	var r0 annotation.Annotations
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], decoder.DecodedParameter) (annotation.Annotations, error)); ok {
		return returnFunc(ctx, req, param)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], decoder.DecodedParameter) annotation.Annotations); ok {
		r0 = returnFunc(ctx, req, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(annotation.Annotations)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], decoder.DecodedParameter) error); ok {
		r1 = returnFunc(ctx, req, param)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParameterAnalyzer_Analyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Analyze'
type MockParameterAnalyzer_Analyze_Call struct {
	*mock.Call
}

// Analyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext]
//   - param decoder.DecodedParameter
func (_e *MockParameterAnalyzer_Expecter) Analyze(ctx interface{}, req interface{}, param interface{}) *MockParameterAnalyzer_Analyze_Call {
	return &MockParameterAnalyzer_Analyze_Call{Call: _e.mock.On("Analyze", ctx, req, param)}
}

func (_c *MockParameterAnalyzer_Analyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter)) *MockParameterAnalyzer_Analyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext]
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext])
		}
		var arg2 decoder.DecodedParameter
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedParameter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParameterAnalyzer_Analyze_Call) Return(annotations annotation.Annotations, err error) *MockParameterAnalyzer_Analyze_Call {
	_c.Call.Return(annotations, err)
	return _c
}

func (_c *MockParameterAnalyzer_Analyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter) (annotation.Annotations, error)) *MockParameterAnalyzer_Analyze_Call {
	_c.Call.Return(run)
	return _c
}

// CanAnalyze provides a mock function for the type MockParameterAnalyzer
func (_mock *MockParameterAnalyzer) CanAnalyze(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter) bool {
	ret := _mock.Called(ctx, req, param)

	if len(ret) == 0 {
		panic("no return value specified for CanAnalyze")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], decoder.DecodedParameter) bool); ok {
		r0 = returnFunc(ctx, req, param)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockParameterAnalyzer_CanAnalyze_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAnalyze'
type MockParameterAnalyzer_CanAnalyze_Call struct {
	*mock.Call
}

// CanAnalyze is a helper method to define mock.On call
//   - ctx context.Context
//   - req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext]
//   - param decoder.DecodedParameter
func (_e *MockParameterAnalyzer_Expecter) CanAnalyze(ctx interface{}, req interface{}, param interface{}) *MockParameterAnalyzer_CanAnalyze_Call {
	return &MockParameterAnalyzer_CanAnalyze_Call{Call: _e.mock.On("CanAnalyze", ctx, req, param)}
}

func (_c *MockParameterAnalyzer_CanAnalyze_Call) Run(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter)) *MockParameterAnalyzer_CanAnalyze_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext]
		if args[1] != nil {
			arg1 = args[1].(analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext])
		}
		var arg2 decoder.DecodedParameter
		if args[2] != nil {
			arg2 = args[2].(decoder.DecodedParameter)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParameterAnalyzer_CanAnalyze_Call) Return(b bool) *MockParameterAnalyzer_CanAnalyze_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockParameterAnalyzer_CanAnalyze_Call) RunAndReturn(run func(ctx context.Context, req analyzer.AnalyzeRequest[analyzer.ParameterAnalyzerContext], param decoder.DecodedParameter) bool) *MockParameterAnalyzer_CanAnalyze_Call {
	_c.Call.Return(run)
	return _c
}

// Dependencies provides a mock function for the type MockParameterAnalyzer
func (_mock *MockParameterAnalyzer) Dependencies() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Dependencies")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockParameterAnalyzer_Dependencies_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dependencies'
type MockParameterAnalyzer_Dependencies_Call struct {
	*mock.Call
}

// Dependencies is a helper method to define mock.On call
func (_e *MockParameterAnalyzer_Expecter) Dependencies() *MockParameterAnalyzer_Dependencies_Call {
	return &MockParameterAnalyzer_Dependencies_Call{Call: _e.mock.On("Dependencies")}
}

func (_c *MockParameterAnalyzer_Dependencies_Call) Run(run func()) *MockParameterAnalyzer_Dependencies_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterAnalyzer_Dependencies_Call) Return(strings []string) *MockParameterAnalyzer_Dependencies_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockParameterAnalyzer_Dependencies_Call) RunAndReturn(run func() []string) *MockParameterAnalyzer_Dependencies_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockParameterAnalyzer
func (_mock *MockParameterAnalyzer) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockParameterAnalyzer_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockParameterAnalyzer_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockParameterAnalyzer_Expecter) ID() *MockParameterAnalyzer_ID_Call {
	return &MockParameterAnalyzer_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockParameterAnalyzer_ID_Call) Run(run func()) *MockParameterAnalyzer_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockParameterAnalyzer_ID_Call) Return(s string) *MockParameterAnalyzer_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockParameterAnalyzer_ID_Call) RunAndReturn(run func() string) *MockParameterAnalyzer_ID_Call {
	_c.Call.Return(run)
	return _c
}
