// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package loaderv3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Close is the `Close` instruction.
type Close struct {

	// [0] = [WRITE] bufferOrProgramDataAccount
	// ··········· Buffer or ProgramData account to close.
	//
	// [1] = [WRITE] destinationAccount
	// ··········· Destination account for reclaimed lamports.
	//
	// [2] = [SIGNER] authority
	// ··········· Authority (optional).
	//
	// [3] = [] programAccount
	// ··········· Program account (optional).
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewCloseInstructionBuilder creates a new `Close` instruction builder.
func NewCloseInstructionBuilder() *Close {
	nd := &Close{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetBufferOrProgramDataAccountAccount sets the "bufferOrProgramDataAccount" account.
// Buffer or ProgramData account to close.
func (inst *Close) SetBufferOrProgramDataAccountAccount(bufferOrProgramDataAccount ag_solanago.PublicKey) *Close {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(bufferOrProgramDataAccount).WRITE()
	return inst
}

// GetBufferOrProgramDataAccountAccount gets the "bufferOrProgramDataAccount" account.
// Buffer or ProgramData account to close.
func (inst *Close) GetBufferOrProgramDataAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetDestinationAccountAccount sets the "destinationAccount" account.
// Destination account for reclaimed lamports.
func (inst *Close) SetDestinationAccountAccount(destinationAccount ag_solanago.PublicKey) *Close {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(destinationAccount).WRITE()
	return inst
}

// GetDestinationAccountAccount gets the "destinationAccount" account.
// Destination account for reclaimed lamports.
func (inst *Close) GetDestinationAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetAuthorityAccount sets the "authority" account.
// Authority (optional).
func (inst *Close) SetAuthorityAccount(authority ag_solanago.PublicKey) *Close {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(authority).SIGNER()
	return inst
}

// GetAuthorityAccount gets the "authority" account.
// Authority (optional).
func (inst *Close) GetAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetProgramAccountAccount sets the "programAccount" account.
// Program account (optional).
func (inst *Close) SetProgramAccountAccount(programAccount ag_solanago.PublicKey) *Close {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(programAccount)
	return inst
}

// GetProgramAccountAccount gets the "programAccount" account.
// Program account (optional).
func (inst *Close) GetProgramAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst Close) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Close,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Close) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Close) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.BufferOrProgramDataAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.DestinationAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.Authority is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.ProgramAccount is not set")
		}
	}
	return nil
}

func (inst *Close) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Close")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("bufferOrProgramData", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("        destination", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          authority", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("            program", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj Close) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *Close) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewCloseInstruction declares a new Close instruction with the provided parameters and accounts.
func NewCloseInstruction(
	// Accounts:
	bufferOrProgramDataAccount ag_solanago.PublicKey,
	destinationAccount ag_solanago.PublicKey,
	authority ag_solanago.PublicKey,
	programAccount ag_solanago.PublicKey) *Close {
	return NewCloseInstructionBuilder().
		SetBufferOrProgramDataAccountAccount(bufferOrProgramDataAccount).
		SetDestinationAccountAccount(destinationAccount).
		SetAuthorityAccount(authority).
		SetProgramAccountAccount(programAccount)
}
