// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package loaderv3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// ExtendProgram is the `ExtendProgram` instruction.
type ExtendProgram struct {
	AdditionalBytes *uint32

	// [0] = [WRITE] programDataAccount
	// ··········· ProgramData account.
	//
	// [1] = [WRITE] programAccount
	// ··········· Program account.
	//
	// [2] = [] systemProgram
	// ··········· System program (optional).
	//
	// [3] = [WRITE, SIGNER] payer
	// ··········· Payer.
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewExtendProgramInstructionBuilder creates a new `ExtendProgram` instruction builder.
func NewExtendProgramInstructionBuilder() *ExtendProgram {
	nd := &ExtendProgram{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 4),
	}
	return nd
}

// SetAdditionalBytes sets the "additionalBytes" parameter.
func (inst *ExtendProgram) SetAdditionalBytes(additionalBytes uint32) *ExtendProgram {
	inst.AdditionalBytes = &additionalBytes
	return inst
}

// SetProgramDataAccountAccount sets the "programDataAccount" account.
// ProgramData account.
func (inst *ExtendProgram) SetProgramDataAccountAccount(programDataAccount ag_solanago.PublicKey) *ExtendProgram {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(programDataAccount).WRITE()
	return inst
}

// GetProgramDataAccountAccount gets the "programDataAccount" account.
// ProgramData account.
func (inst *ExtendProgram) GetProgramDataAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetProgramAccountAccount sets the "programAccount" account.
// Program account.
func (inst *ExtendProgram) SetProgramAccountAccount(programAccount ag_solanago.PublicKey) *ExtendProgram {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(programAccount).WRITE()
	return inst
}

// GetProgramAccountAccount gets the "programAccount" account.
// Program account.
func (inst *ExtendProgram) GetProgramAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetSystemProgramAccount sets the "systemProgram" account.
// System program (optional).
func (inst *ExtendProgram) SetSystemProgramAccount(systemProgram ag_solanago.PublicKey) *ExtendProgram {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(systemProgram)
	return inst
}

// GetSystemProgramAccount gets the "systemProgram" account.
// System program (optional).
func (inst *ExtendProgram) GetSystemProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetPayerAccount sets the "payer" account.
// Payer.
func (inst *ExtendProgram) SetPayerAccount(payer ag_solanago.PublicKey) *ExtendProgram {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(payer).WRITE().SIGNER()
	return inst
}

// GetPayerAccount gets the "payer" account.
// Payer.
func (inst *ExtendProgram) GetPayerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

func (inst ExtendProgram) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_ExtendProgram,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst ExtendProgram) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *ExtendProgram) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.AdditionalBytes == nil {
			return errors.New("AdditionalBytes parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.ProgramDataAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.ProgramAccount is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.SystemProgram is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.Payer is not set")
		}
	}
	return nil
}

func (inst *ExtendProgram) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("ExtendProgram")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=1]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("AdditionalBytes", *inst.AdditionalBytes))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=4]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("  programData", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      program", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("systemProgram", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("        payer", inst.AccountMetaSlice.Get(3)))
					})
				})
		})
}

func (obj ExtendProgram) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `AdditionalBytes` param:
	err = encoder.Encode(obj.AdditionalBytes)
	if err != nil {
		return err
	}
	return nil
}
func (obj *ExtendProgram) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `AdditionalBytes`:
	err = decoder.Decode(&obj.AdditionalBytes)
	if err != nil {
		return err
	}
	return nil
}

// NewExtendProgramInstruction declares a new ExtendProgram instruction with the provided parameters and accounts.
func NewExtendProgramInstruction(
	// Parameters:
	additionalBytes uint32,
	// Accounts:
	programDataAccount ag_solanago.PublicKey,
	programAccount ag_solanago.PublicKey,
	systemProgram ag_solanago.PublicKey,
	payer ag_solanago.PublicKey) *ExtendProgram {
	return NewExtendProgramInstructionBuilder().
		SetAdditionalBytes(additionalBytes).
		SetProgramDataAccountAccount(programDataAccount).
		SetProgramAccountAccount(programAccount).
		SetSystemProgramAccount(systemProgram).
		SetPayerAccount(payer)
}
