// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package loaderv3

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// Write is the `Write` instruction.
type Write struct {
	Offset *uint32
	Bytes  *[]byte

	// [0] = [WRITE] bufferAccount
	// ··········· Buffer account.
	//
	// [1] = [SIGNER] bufferAuthority
	// ··········· Buffer authority.
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWriteInstructionBuilder creates a new `Write` instruction builder.
func NewWriteInstructionBuilder() *Write {
	nd := &Write{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 2),
	}
	return nd
}

// SetOffset sets the "offset" parameter.
func (inst *Write) SetOffset(offset uint32) *Write {
	inst.Offset = &offset
	return inst
}

// SetBytes sets the "bytes" parameter.
func (inst *Write) SetBytes(bytes []byte) *Write {
	inst.Bytes = &bytes
	return inst
}

// SetBufferAccountAccount sets the "bufferAccount" account.
// Buffer account.
func (inst *Write) SetBufferAccountAccount(bufferAccount ag_solanago.PublicKey) *Write {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(bufferAccount).WRITE()
	return inst
}

// GetBufferAccountAccount gets the "bufferAccount" account.
// Buffer account.
func (inst *Write) GetBufferAccountAccount() *ag_solanago.AccountMeta {
	return inst.Get(0)
}

// SetBufferAuthorityAccount sets the "bufferAuthority" account.
// Buffer authority.
func (inst *Write) SetBufferAuthorityAccount(bufferAuthority ag_solanago.PublicKey) *Write {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(bufferAuthority).SIGNER()
	return inst
}

// GetBufferAuthorityAccount gets the "bufferAuthority" account.
// Buffer authority.
func (inst *Write) GetBufferAuthorityAccount() *ag_solanago.AccountMeta {
	return inst.Get(1)
}

func (inst Write) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_Write,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst Write) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *Write) Validate() error {
	// Check whether all (required) parameters are set:
	{
		if inst.Offset == nil {
			return errors.New("offset parameter is not set")
		}
		if inst.Bytes == nil {
			return errors.New("bytes parameter is not set")
		}
	}

	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.BufferAccount is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.BufferAuthority is not set")
		}
	}
	return nil
}

func (inst *Write) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("Write")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=2]").ParentFunc(func(paramsBranch ag_treeout.Branches) {
						paramsBranch.Child(ag_format.Param("Offset", *inst.Offset))
						paramsBranch.Child(ag_format.Param(" Bytes", *inst.Bytes))
					})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=2]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("         buffer", inst.Get(0)))
						accountsBranch.Child(ag_format.Meta("bufferAuthority", inst.Get(1)))
					})
				})
		})
}

func (obj Write) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	// Serialize `Offset` param:
	err = encoder.Encode(obj.Offset)
	if err != nil {
		return err
	}
	// Serialize `Bytes` param:
	err = encoder.Encode(obj.Bytes)
	if err != nil {
		return err
	}
	return nil
}
func (obj *Write) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	// Deserialize `Offset`:
	err = decoder.Decode(&obj.Offset)
	if err != nil {
		return err
	}
	// Deserialize `Bytes`:
	err = decoder.Decode(&obj.Bytes)
	if err != nil {
		return err
	}
	return nil
}

// NewWriteInstruction declares a new Write instruction with the provided parameters and accounts.
func NewWriteInstruction(
	// Parameters:
	offset uint32,
	bytes []byte,
	// Accounts:
	bufferAccount ag_solanago.PublicKey,
	bufferAuthority ag_solanago.PublicKey) *Write {
	return NewWriteInstructionBuilder().
		SetOffset(offset).
		SetBytes(bytes).
		SetBufferAccountAccount(bufferAccount).
		SetBufferAuthorityAccount(bufferAuthority)
}
