// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"math/big"

	"github.com/block-vision/sui-go-sdk/pb/sui/rpc/v2"
	"github.com/block-vision/sui-go-sdk/signer"
	"github.com/block-vision/sui-go-sdk/transaction"
	"github.com/smartcontractkit/chainlink-sui/relayer/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBindingsClient creates a new instance of MockBindingsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBindingsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBindingsClient {
	mock := &MockBindingsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBindingsClient is an autogenerated mock type for the BindingsClient type
type MockBindingsClient struct {
	mock.Mock
}

type MockBindingsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBindingsClient) EXPECT() *MockBindingsClient_Expecter {
	return &MockBindingsClient_Expecter{mock: &_m.Mock}
}

// FinishPTBAndSend provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) FinishPTBAndSend(ctx context.Context, signer1 *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error) {
	ret := _mock.Called(ctx, signer1, tx, requestType)

	if len(ret) == 0 {
		panic("no return value specified for FinishPTBAndSend")
	}

	var r0 *v2.ExecuteTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error)); ok {
		return returnFunc(ctx, signer1, tx, requestType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) *v2.ExecuteTransactionResponse); ok {
		r0 = returnFunc(ctx, signer1, tx, requestType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ExecuteTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) error); ok {
		r1 = returnFunc(ctx, signer1, tx, requestType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_FinishPTBAndSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishPTBAndSend'
type MockBindingsClient_FinishPTBAndSend_Call struct {
	*mock.Call
}

// FinishPTBAndSend is a helper method to define mock.On call
//   - ctx context.Context
//   - signer1 *signer.Signer
//   - tx *transaction.Transaction
//   - requestType client.TransactionRequestType
func (_e *MockBindingsClient_Expecter) FinishPTBAndSend(ctx interface{}, signer1 interface{}, tx interface{}, requestType interface{}) *MockBindingsClient_FinishPTBAndSend_Call {
	return &MockBindingsClient_FinishPTBAndSend_Call{Call: _e.mock.On("FinishPTBAndSend", ctx, signer1, tx, requestType)}
}

func (_c *MockBindingsClient_FinishPTBAndSend_Call) Run(run func(ctx context.Context, signer1 *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType)) *MockBindingsClient_FinishPTBAndSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *signer.Signer
		if args[1] != nil {
			arg1 = args[1].(*signer.Signer)
		}
		var arg2 *transaction.Transaction
		if args[2] != nil {
			arg2 = args[2].(*transaction.Transaction)
		}
		var arg3 client.TransactionRequestType
		if args[3] != nil {
			arg3 = args[3].(client.TransactionRequestType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBindingsClient_FinishPTBAndSend_Call) Return(executeTransactionResponse *v2.ExecuteTransactionResponse, err error) *MockBindingsClient_FinishPTBAndSend_Call {
	_c.Call.Return(executeTransactionResponse, err)
	return _c
}

func (_c *MockBindingsClient_FinishPTBAndSend_Call) RunAndReturn(run func(ctx context.Context, signer1 *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error)) *MockBindingsClient_FinishPTBAndSend_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceGasPrice provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) GetReferenceGasPrice(ctx context.Context) (*big.Int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceGasPrice")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_GetReferenceGasPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceGasPrice'
type MockBindingsClient_GetReferenceGasPrice_Call struct {
	*mock.Call
}

// GetReferenceGasPrice is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBindingsClient_Expecter) GetReferenceGasPrice(ctx interface{}) *MockBindingsClient_GetReferenceGasPrice_Call {
	return &MockBindingsClient_GetReferenceGasPrice_Call{Call: _e.mock.On("GetReferenceGasPrice", ctx)}
}

func (_c *MockBindingsClient_GetReferenceGasPrice_Call) Run(run func(ctx context.Context)) *MockBindingsClient_GetReferenceGasPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBindingsClient_GetReferenceGasPrice_Call) Return(intParam *big.Int, err error) *MockBindingsClient_GetReferenceGasPrice_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockBindingsClient_GetReferenceGasPrice_Call) RunAndReturn(run func(ctx context.Context) (*big.Int, error)) *MockBindingsClient_GetReferenceGasPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionStatus provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) GetTransactionStatus(ctx context.Context, digest string) (client.TransactionResult, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStatus")
	}

	var r0 client.TransactionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.TransactionResult, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.TransactionResult); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		r0 = ret.Get(0).(client.TransactionResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_GetTransactionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionStatus'
type MockBindingsClient_GetTransactionStatus_Call struct {
	*mock.Call
}

// GetTransactionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
func (_e *MockBindingsClient_Expecter) GetTransactionStatus(ctx interface{}, digest interface{}) *MockBindingsClient_GetTransactionStatus_Call {
	return &MockBindingsClient_GetTransactionStatus_Call{Call: _e.mock.On("GetTransactionStatus", ctx, digest)}
}

func (_c *MockBindingsClient_GetTransactionStatus_Call) Run(run func(ctx context.Context, digest string)) *MockBindingsClient_GetTransactionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBindingsClient_GetTransactionStatus_Call) Return(transactionResult client.TransactionResult, err error) *MockBindingsClient_GetTransactionStatus_Call {
	_c.Call.Return(transactionResult, err)
	return _c
}

func (_c *MockBindingsClient_GetTransactionStatus_Call) RunAndReturn(run func(ctx context.Context, digest string) (client.TransactionResult, error)) *MockBindingsClient_GetTransactionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCoinsByAddress provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) QueryCoinsByAddress(ctx context.Context, address string, coinType string) ([]*v2.Object, error) {
	ret := _mock.Called(ctx, address, coinType)

	if len(ret) == 0 {
		panic("no return value specified for QueryCoinsByAddress")
	}

	var r0 []*v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*v2.Object, error)); ok {
		return returnFunc(ctx, address, coinType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*v2.Object); ok {
		r0 = returnFunc(ctx, address, coinType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, address, coinType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_QueryCoinsByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCoinsByAddress'
type MockBindingsClient_QueryCoinsByAddress_Call struct {
	*mock.Call
}

// QueryCoinsByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - coinType string
func (_e *MockBindingsClient_Expecter) QueryCoinsByAddress(ctx interface{}, address interface{}, coinType interface{}) *MockBindingsClient_QueryCoinsByAddress_Call {
	return &MockBindingsClient_QueryCoinsByAddress_Call{Call: _e.mock.On("QueryCoinsByAddress", ctx, address, coinType)}
}

func (_c *MockBindingsClient_QueryCoinsByAddress_Call) Run(run func(ctx context.Context, address string, coinType string)) *MockBindingsClient_QueryCoinsByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBindingsClient_QueryCoinsByAddress_Call) Return(objects []*v2.Object, err error) *MockBindingsClient_QueryCoinsByAddress_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MockBindingsClient_QueryCoinsByAddress_Call) RunAndReturn(run func(ctx context.Context, address string, coinType string) ([]*v2.Object, error)) *MockBindingsClient_QueryCoinsByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// ReadObjectId provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) ReadObjectId(ctx context.Context, objectId string) (*v2.Object, error) {
	ret := _mock.Called(ctx, objectId)

	if len(ret) == 0 {
		panic("no return value specified for ReadObjectId")
	}

	var r0 *v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v2.Object, error)); ok {
		return returnFunc(ctx, objectId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v2.Object); ok {
		r0 = returnFunc(ctx, objectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_ReadObjectId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadObjectId'
type MockBindingsClient_ReadObjectId_Call struct {
	*mock.Call
}

// ReadObjectId is a helper method to define mock.On call
//   - ctx context.Context
//   - objectId string
func (_e *MockBindingsClient_Expecter) ReadObjectId(ctx interface{}, objectId interface{}) *MockBindingsClient_ReadObjectId_Call {
	return &MockBindingsClient_ReadObjectId_Call{Call: _e.mock.On("ReadObjectId", ctx, objectId)}
}

func (_c *MockBindingsClient_ReadObjectId_Call) Run(run func(ctx context.Context, objectId string)) *MockBindingsClient_ReadObjectId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBindingsClient_ReadObjectId_Call) Return(object *v2.Object, err error) *MockBindingsClient_ReadObjectId_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockBindingsClient_ReadObjectId_Call) RunAndReturn(run func(ctx context.Context, objectId string) (*v2.Object, error)) *MockBindingsClient_ReadObjectId_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) SendTransaction(ctx context.Context, req *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 *v2.ExecuteTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.ExecuteTransactionRequest) *v2.ExecuteTransactionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ExecuteTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.ExecuteTransactionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type MockBindingsClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - req *v2.ExecuteTransactionRequest
func (_e *MockBindingsClient_Expecter) SendTransaction(ctx interface{}, req interface{}) *MockBindingsClient_SendTransaction_Call {
	return &MockBindingsClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, req)}
}

func (_c *MockBindingsClient_SendTransaction_Call) Run(run func(ctx context.Context, req *v2.ExecuteTransactionRequest)) *MockBindingsClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.ExecuteTransactionRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.ExecuteTransactionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBindingsClient_SendTransaction_Call) Return(executeTransactionResponse *v2.ExecuteTransactionResponse, err error) *MockBindingsClient_SendTransaction_Call {
	_c.Call.Return(executeTransactionResponse, err)
	return _c
}

func (_c *MockBindingsClient_SendTransaction_Call) RunAndReturn(run func(ctx context.Context, req *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error)) *MockBindingsClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SimulatePTB provides a mock function for the type MockBindingsClient
func (_mock *MockBindingsClient) SimulatePTB(ctx context.Context, bcsBytes []byte) ([]any, error) {
	ret := _mock.Called(ctx, bcsBytes)

	if len(ret) == 0 {
		panic("no return value specified for SimulatePTB")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]any, error)); ok {
		return returnFunc(ctx, bcsBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []any); ok {
		r0 = returnFunc(ctx, bcsBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, bcsBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBindingsClient_SimulatePTB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulatePTB'
type MockBindingsClient_SimulatePTB_Call struct {
	*mock.Call
}

// SimulatePTB is a helper method to define mock.On call
//   - ctx context.Context
//   - bcsBytes []byte
func (_e *MockBindingsClient_Expecter) SimulatePTB(ctx interface{}, bcsBytes interface{}) *MockBindingsClient_SimulatePTB_Call {
	return &MockBindingsClient_SimulatePTB_Call{Call: _e.mock.On("SimulatePTB", ctx, bcsBytes)}
}

func (_c *MockBindingsClient_SimulatePTB_Call) Run(run func(ctx context.Context, bcsBytes []byte)) *MockBindingsClient_SimulatePTB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBindingsClient_SimulatePTB_Call) Return(vs []any, err error) *MockBindingsClient_SimulatePTB_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockBindingsClient_SimulatePTB_Call) RunAndReturn(run func(ctx context.Context, bcsBytes []byte) ([]any, error)) *MockBindingsClient_SimulatePTB_Call {
	_c.Call.Return(run)
	return _c
}
