// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"math/big"

	"github.com/block-vision/sui-go-sdk/models"
	"github.com/block-vision/sui-go-sdk/pb/sui/rpc/v2"
	"github.com/block-vision/sui-go-sdk/signer"
	"github.com/block-vision/sui-go-sdk/transaction"
	"github.com/patrickmn/go-cache"
	"github.com/smartcontractkit/chainlink-sui/relayer/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSuiPTBClient creates a new instance of MockSuiPTBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSuiPTBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSuiPTBClient {
	mock := &MockSuiPTBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSuiPTBClient is an autogenerated mock type for the SuiPTBClient type
type MockSuiPTBClient struct {
	mock.Mock
}

type MockSuiPTBClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSuiPTBClient) EXPECT() *MockSuiPTBClient_Expecter {
	return &MockSuiPTBClient_Expecter{mock: &_m.Mock}
}

// EstimateGas provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) EstimateGas(ctx context.Context, tx *transaction.Transaction) (uint64, error) {
	ret := _mock.Called(ctx, tx)

	if len(ret) == 0 {
		panic("no return value specified for EstimateGas")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) (uint64, error)); ok {
		return returnFunc(ctx, tx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *transaction.Transaction) uint64); ok {
		r0 = returnFunc(ctx, tx)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *transaction.Transaction) error); ok {
		r1 = returnFunc(ctx, tx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_EstimateGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EstimateGas'
type MockSuiPTBClient_EstimateGas_Call struct {
	*mock.Call
}

// EstimateGas is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *transaction.Transaction
func (_e *MockSuiPTBClient_Expecter) EstimateGas(ctx interface{}, tx interface{}) *MockSuiPTBClient_EstimateGas_Call {
	return &MockSuiPTBClient_EstimateGas_Call{Call: _e.mock.On("EstimateGas", ctx, tx)}
}

func (_c *MockSuiPTBClient_EstimateGas_Call) Run(run func(ctx context.Context, tx *transaction.Transaction)) *MockSuiPTBClient_EstimateGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *transaction.Transaction
		if args[1] != nil {
			arg1 = args[1].(*transaction.Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_EstimateGas_Call) Return(v uint64, err error) *MockSuiPTBClient_EstimateGas_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSuiPTBClient_EstimateGas_Call) RunAndReturn(run func(ctx context.Context, tx *transaction.Transaction) (uint64, error)) *MockSuiPTBClient_EstimateGas_Call {
	_c.Call.Return(run)
	return _c
}

// FinishPTBAndSend provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) FinishPTBAndSend(ctx context.Context, txnSigner *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error) {
	ret := _mock.Called(ctx, txnSigner, tx, requestType)

	if len(ret) == 0 {
		panic("no return value specified for FinishPTBAndSend")
	}

	var r0 *v2.ExecuteTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error)); ok {
		return returnFunc(ctx, txnSigner, tx, requestType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) *v2.ExecuteTransactionResponse); ok {
		r0 = returnFunc(ctx, txnSigner, tx, requestType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ExecuteTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *signer.Signer, *transaction.Transaction, client.TransactionRequestType) error); ok {
		r1 = returnFunc(ctx, txnSigner, tx, requestType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_FinishPTBAndSend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishPTBAndSend'
type MockSuiPTBClient_FinishPTBAndSend_Call struct {
	*mock.Call
}

// FinishPTBAndSend is a helper method to define mock.On call
//   - ctx context.Context
//   - txnSigner *signer.Signer
//   - tx *transaction.Transaction
//   - requestType client.TransactionRequestType
func (_e *MockSuiPTBClient_Expecter) FinishPTBAndSend(ctx interface{}, txnSigner interface{}, tx interface{}, requestType interface{}) *MockSuiPTBClient_FinishPTBAndSend_Call {
	return &MockSuiPTBClient_FinishPTBAndSend_Call{Call: _e.mock.On("FinishPTBAndSend", ctx, txnSigner, tx, requestType)}
}

func (_c *MockSuiPTBClient_FinishPTBAndSend_Call) Run(run func(ctx context.Context, txnSigner *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType)) *MockSuiPTBClient_FinishPTBAndSend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *signer.Signer
		if args[1] != nil {
			arg1 = args[1].(*signer.Signer)
		}
		var arg2 *transaction.Transaction
		if args[2] != nil {
			arg2 = args[2].(*transaction.Transaction)
		}
		var arg3 client.TransactionRequestType
		if args[3] != nil {
			arg3 = args[3].(client.TransactionRequestType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_FinishPTBAndSend_Call) Return(executeTransactionResponse *v2.ExecuteTransactionResponse, err error) *MockSuiPTBClient_FinishPTBAndSend_Call {
	_c.Call.Return(executeTransactionResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_FinishPTBAndSend_Call) RunAndReturn(run func(ctx context.Context, txnSigner *signer.Signer, tx *transaction.Transaction, requestType client.TransactionRequestType) (*v2.ExecuteTransactionResponse, error)) *MockSuiPTBClient_FinishPTBAndSend_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockById provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetBlockById(ctx context.Context, checkpointDigest string) (*v2.Checkpoint, error) {
	ret := _mock.Called(ctx, checkpointDigest)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockById")
	}

	var r0 *v2.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v2.Checkpoint, error)); ok {
		return returnFunc(ctx, checkpointDigest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v2.Checkpoint); ok {
		r0 = returnFunc(ctx, checkpointDigest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Checkpoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, checkpointDigest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetBlockById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockById'
type MockSuiPTBClient_GetBlockById_Call struct {
	*mock.Call
}

// GetBlockById is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpointDigest string
func (_e *MockSuiPTBClient_Expecter) GetBlockById(ctx interface{}, checkpointDigest interface{}) *MockSuiPTBClient_GetBlockById_Call {
	return &MockSuiPTBClient_GetBlockById_Call{Call: _e.mock.On("GetBlockById", ctx, checkpointDigest)}
}

func (_c *MockSuiPTBClient_GetBlockById_Call) Run(run func(ctx context.Context, checkpointDigest string)) *MockSuiPTBClient_GetBlockById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetBlockById_Call) Return(checkpoint *v2.Checkpoint, err error) *MockSuiPTBClient_GetBlockById_Call {
	_c.Call.Return(checkpoint, err)
	return _c
}

func (_c *MockSuiPTBClient_GetBlockById_Call) RunAndReturn(run func(ctx context.Context, checkpointDigest string) (*v2.Checkpoint, error)) *MockSuiPTBClient_GetBlockById_Call {
	_c.Call.Return(run)
	return _c
}

// GetCCIPPackageID provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCCIPPackageID(ctx context.Context, offRampPackageID string) (string, error) {
	ret := _mock.Called(ctx, offRampPackageID)

	if len(ret) == 0 {
		panic("no return value specified for GetCCIPPackageID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, offRampPackageID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, offRampPackageID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, offRampPackageID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCCIPPackageID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCCIPPackageID'
type MockSuiPTBClient_GetCCIPPackageID_Call struct {
	*mock.Call
}

// GetCCIPPackageID is a helper method to define mock.On call
//   - ctx context.Context
//   - offRampPackageID string
func (_e *MockSuiPTBClient_Expecter) GetCCIPPackageID(ctx interface{}, offRampPackageID interface{}) *MockSuiPTBClient_GetCCIPPackageID_Call {
	return &MockSuiPTBClient_GetCCIPPackageID_Call{Call: _e.mock.On("GetCCIPPackageID", ctx, offRampPackageID)}
}

func (_c *MockSuiPTBClient_GetCCIPPackageID_Call) Run(run func(ctx context.Context, offRampPackageID string)) *MockSuiPTBClient_GetCCIPPackageID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCCIPPackageID_Call) Return(s string, err error) *MockSuiPTBClient_GetCCIPPackageID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSuiPTBClient_GetCCIPPackageID_Call) RunAndReturn(run func(ctx context.Context, offRampPackageID string) (string, error)) *MockSuiPTBClient_GetCCIPPackageID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCache provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCache() *cache.Cache {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCache")
	}

	var r0 *cache.Cache
	if returnFunc, ok := ret.Get(0).(func() *cache.Cache); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cache.Cache)
		}
	}
	return r0
}

// MockSuiPTBClient_GetCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCache'
type MockSuiPTBClient_GetCache_Call struct {
	*mock.Call
}

// GetCache is a helper method to define mock.On call
func (_e *MockSuiPTBClient_Expecter) GetCache() *MockSuiPTBClient_GetCache_Call {
	return &MockSuiPTBClient_GetCache_Call{Call: _e.mock.On("GetCache")}
}

func (_c *MockSuiPTBClient_GetCache_Call) Run(run func()) *MockSuiPTBClient_GetCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCache_Call) Return(cache1 *cache.Cache) *MockSuiPTBClient_GetCache_Call {
	_c.Call.Return(cache1)
	return _c
}

func (_c *MockSuiPTBClient_GetCache_Call) RunAndReturn(run func() *cache.Cache) *MockSuiPTBClient_GetCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachedValue provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCachedValue(key string) (any, bool) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetCachedValue")
	}

	var r0 any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (any, bool)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCachedValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachedValue'
type MockSuiPTBClient_GetCachedValue_Call struct {
	*mock.Call
}

// GetCachedValue is a helper method to define mock.On call
//   - key string
func (_e *MockSuiPTBClient_Expecter) GetCachedValue(key interface{}) *MockSuiPTBClient_GetCachedValue_Call {
	return &MockSuiPTBClient_GetCachedValue_Call{Call: _e.mock.On("GetCachedValue", key)}
}

func (_c *MockSuiPTBClient_GetCachedValue_Call) Run(run func(key string)) *MockSuiPTBClient_GetCachedValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCachedValue_Call) Return(v any, b bool) *MockSuiPTBClient_GetCachedValue_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockSuiPTBClient_GetCachedValue_Call) RunAndReturn(run func(key string) (any, bool)) *MockSuiPTBClient_GetCachedValue_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachedValues provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCachedValues(keys []string) (map[string]any, bool) {
	ret := _mock.Called(keys)

	if len(ret) == 0 {
		panic("no return value specified for GetCachedValues")
	}

	var r0 map[string]any
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func([]string) (map[string]any, bool)); ok {
		return returnFunc(keys)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) map[string]any); ok {
		r0 = returnFunc(keys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) bool); ok {
		r1 = returnFunc(keys)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCachedValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachedValues'
type MockSuiPTBClient_GetCachedValues_Call struct {
	*mock.Call
}

// GetCachedValues is a helper method to define mock.On call
//   - keys []string
func (_e *MockSuiPTBClient_Expecter) GetCachedValues(keys interface{}) *MockSuiPTBClient_GetCachedValues_Call {
	return &MockSuiPTBClient_GetCachedValues_Call{Call: _e.mock.On("GetCachedValues", keys)}
}

func (_c *MockSuiPTBClient_GetCachedValues_Call) Run(run func(keys []string)) *MockSuiPTBClient_GetCachedValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCachedValues_Call) Return(stringToV map[string]any, b bool) *MockSuiPTBClient_GetCachedValues_Call {
	_c.Call.Return(stringToV, b)
	return _c
}

func (_c *MockSuiPTBClient_GetCachedValues_Call) RunAndReturn(run func(keys []string) (map[string]any, bool)) *MockSuiPTBClient_GetCachedValues_Call {
	_c.Call.Return(run)
	return _c
}

// GetCheckpointData provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCheckpointData(ctx context.Context, checkpointSequenceNumber uint64) (*client.CheckpointData, error) {
	ret := _mock.Called(ctx, checkpointSequenceNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckpointData")
	}

	var r0 *client.CheckpointData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) (*client.CheckpointData, error)); ok {
		return returnFunc(ctx, checkpointSequenceNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) *client.CheckpointData); ok {
		r0 = returnFunc(ctx, checkpointSequenceNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.CheckpointData)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = returnFunc(ctx, checkpointSequenceNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCheckpointData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckpointData'
type MockSuiPTBClient_GetCheckpointData_Call struct {
	*mock.Call
}

// GetCheckpointData is a helper method to define mock.On call
//   - ctx context.Context
//   - checkpointSequenceNumber uint64
func (_e *MockSuiPTBClient_Expecter) GetCheckpointData(ctx interface{}, checkpointSequenceNumber interface{}) *MockSuiPTBClient_GetCheckpointData_Call {
	return &MockSuiPTBClient_GetCheckpointData_Call{Call: _e.mock.On("GetCheckpointData", ctx, checkpointSequenceNumber)}
}

func (_c *MockSuiPTBClient_GetCheckpointData_Call) Run(run func(ctx context.Context, checkpointSequenceNumber uint64)) *MockSuiPTBClient_GetCheckpointData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCheckpointData_Call) Return(checkpointData *client.CheckpointData, err error) *MockSuiPTBClient_GetCheckpointData_Call {
	_c.Call.Return(checkpointData, err)
	return _c
}

func (_c *MockSuiPTBClient_GetCheckpointData_Call) RunAndReturn(run func(ctx context.Context, checkpointSequenceNumber uint64) (*client.CheckpointData, error)) *MockSuiPTBClient_GetCheckpointData_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinMetadata provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCoinMetadata(ctx context.Context, coinType string) (models.CoinMetadataResponse, error) {
	ret := _mock.Called(ctx, coinType)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinMetadata")
	}

	var r0 models.CoinMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (models.CoinMetadataResponse, error)); ok {
		return returnFunc(ctx, coinType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) models.CoinMetadataResponse); ok {
		r0 = returnFunc(ctx, coinType)
	} else {
		r0 = ret.Get(0).(models.CoinMetadataResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, coinType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCoinMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinMetadata'
type MockSuiPTBClient_GetCoinMetadata_Call struct {
	*mock.Call
}

// GetCoinMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - coinType string
func (_e *MockSuiPTBClient_Expecter) GetCoinMetadata(ctx interface{}, coinType interface{}) *MockSuiPTBClient_GetCoinMetadata_Call {
	return &MockSuiPTBClient_GetCoinMetadata_Call{Call: _e.mock.On("GetCoinMetadata", ctx, coinType)}
}

func (_c *MockSuiPTBClient_GetCoinMetadata_Call) Run(run func(ctx context.Context, coinType string)) *MockSuiPTBClient_GetCoinMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCoinMetadata_Call) Return(coinMetadataResponse models.CoinMetadataResponse, err error) *MockSuiPTBClient_GetCoinMetadata_Call {
	_c.Call.Return(coinMetadataResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_GetCoinMetadata_Call) RunAndReturn(run func(ctx context.Context, coinType string) (models.CoinMetadataResponse, error)) *MockSuiPTBClient_GetCoinMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoinsByAddress provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetCoinsByAddress(ctx context.Context, address string) ([]*v2.Object, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetCoinsByAddress")
	}

	var r0 []*v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]*v2.Object, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []*v2.Object); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetCoinsByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoinsByAddress'
type MockSuiPTBClient_GetCoinsByAddress_Call struct {
	*mock.Call
}

// GetCoinsByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockSuiPTBClient_Expecter) GetCoinsByAddress(ctx interface{}, address interface{}) *MockSuiPTBClient_GetCoinsByAddress_Call {
	return &MockSuiPTBClient_GetCoinsByAddress_Call{Call: _e.mock.On("GetCoinsByAddress", ctx, address)}
}

func (_c *MockSuiPTBClient_GetCoinsByAddress_Call) Run(run func(ctx context.Context, address string)) *MockSuiPTBClient_GetCoinsByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetCoinsByAddress_Call) Return(objects []*v2.Object, err error) *MockSuiPTBClient_GetCoinsByAddress_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MockSuiPTBClient_GetCoinsByAddress_Call) RunAndReturn(run func(ctx context.Context, address string) ([]*v2.Object, error)) *MockSuiPTBClient_GetCoinsByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestCheckpoint provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetLatestCheckpoint(ctx context.Context) (*v2.Checkpoint, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestCheckpoint")
	}

	var r0 *v2.Checkpoint
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v2.Checkpoint, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v2.Checkpoint); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Checkpoint)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetLatestCheckpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestCheckpoint'
type MockSuiPTBClient_GetLatestCheckpoint_Call struct {
	*mock.Call
}

// GetLatestCheckpoint is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSuiPTBClient_Expecter) GetLatestCheckpoint(ctx interface{}) *MockSuiPTBClient_GetLatestCheckpoint_Call {
	return &MockSuiPTBClient_GetLatestCheckpoint_Call{Call: _e.mock.On("GetLatestCheckpoint", ctx)}
}

func (_c *MockSuiPTBClient_GetLatestCheckpoint_Call) Run(run func(ctx context.Context)) *MockSuiPTBClient_GetLatestCheckpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetLatestCheckpoint_Call) Return(checkpoint *v2.Checkpoint, err error) *MockSuiPTBClient_GetLatestCheckpoint_Call {
	_c.Call.Return(checkpoint, err)
	return _c
}

func (_c *MockSuiPTBClient_GetLatestCheckpoint_Call) RunAndReturn(run func(ctx context.Context) (*v2.Checkpoint, error)) *MockSuiPTBClient_GetLatestCheckpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestEpoch provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetLatestEpoch(ctx context.Context) (*v2.Epoch, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestEpoch")
	}

	var r0 *v2.Epoch
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*v2.Epoch, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *v2.Epoch); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Epoch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetLatestEpoch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestEpoch'
type MockSuiPTBClient_GetLatestEpoch_Call struct {
	*mock.Call
}

// GetLatestEpoch is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSuiPTBClient_Expecter) GetLatestEpoch(ctx interface{}) *MockSuiPTBClient_GetLatestEpoch_Call {
	return &MockSuiPTBClient_GetLatestEpoch_Call{Call: _e.mock.On("GetLatestEpoch", ctx)}
}

func (_c *MockSuiPTBClient_GetLatestEpoch_Call) Run(run func(ctx context.Context)) *MockSuiPTBClient_GetLatestEpoch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetLatestEpoch_Call) Return(epoch *v2.Epoch, err error) *MockSuiPTBClient_GetLatestEpoch_Call {
	_c.Call.Return(epoch, err)
	return _c
}

func (_c *MockSuiPTBClient_GetLatestEpoch_Call) RunAndReturn(run func(ctx context.Context) (*v2.Epoch, error)) *MockSuiPTBClient_GetLatestEpoch_Call {
	_c.Call.Return(run)
	return _c
}

// GetLatestPackageId provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetLatestPackageId(ctx context.Context, packageId string, module string) (string, error) {
	ret := _mock.Called(ctx, packageId, module)

	if len(ret) == 0 {
		panic("no return value specified for GetLatestPackageId")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, packageId, module)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, packageId, module)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, packageId, module)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetLatestPackageId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLatestPackageId'
type MockSuiPTBClient_GetLatestPackageId_Call struct {
	*mock.Call
}

// GetLatestPackageId is a helper method to define mock.On call
//   - ctx context.Context
//   - packageId string
//   - module string
func (_e *MockSuiPTBClient_Expecter) GetLatestPackageId(ctx interface{}, packageId interface{}, module interface{}) *MockSuiPTBClient_GetLatestPackageId_Call {
	return &MockSuiPTBClient_GetLatestPackageId_Call{Call: _e.mock.On("GetLatestPackageId", ctx, packageId, module)}
}

func (_c *MockSuiPTBClient_GetLatestPackageId_Call) Run(run func(ctx context.Context, packageId string, module string)) *MockSuiPTBClient_GetLatestPackageId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetLatestPackageId_Call) Return(s string, err error) *MockSuiPTBClient_GetLatestPackageId_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSuiPTBClient_GetLatestPackageId_Call) RunAndReturn(run func(ctx context.Context, packageId string, module string) (string, error)) *MockSuiPTBClient_GetLatestPackageId_Call {
	_c.Call.Return(run)
	return _c
}

// GetNormalizedModule provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetNormalizedModule(ctx context.Context, packageId string, moduleId string) (models.GetNormalizedMoveModuleResponse, error) {
	ret := _mock.Called(ctx, packageId, moduleId)

	if len(ret) == 0 {
		panic("no return value specified for GetNormalizedModule")
	}

	var r0 models.GetNormalizedMoveModuleResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (models.GetNormalizedMoveModuleResponse, error)); ok {
		return returnFunc(ctx, packageId, moduleId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) models.GetNormalizedMoveModuleResponse); ok {
		r0 = returnFunc(ctx, packageId, moduleId)
	} else {
		r0 = ret.Get(0).(models.GetNormalizedMoveModuleResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, packageId, moduleId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetNormalizedModule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNormalizedModule'
type MockSuiPTBClient_GetNormalizedModule_Call struct {
	*mock.Call
}

// GetNormalizedModule is a helper method to define mock.On call
//   - ctx context.Context
//   - packageId string
//   - moduleId string
func (_e *MockSuiPTBClient_Expecter) GetNormalizedModule(ctx interface{}, packageId interface{}, moduleId interface{}) *MockSuiPTBClient_GetNormalizedModule_Call {
	return &MockSuiPTBClient_GetNormalizedModule_Call{Call: _e.mock.On("GetNormalizedModule", ctx, packageId, moduleId)}
}

func (_c *MockSuiPTBClient_GetNormalizedModule_Call) Run(run func(ctx context.Context, packageId string, moduleId string)) *MockSuiPTBClient_GetNormalizedModule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetNormalizedModule_Call) Return(getNormalizedMoveModuleResponse models.GetNormalizedMoveModuleResponse, err error) *MockSuiPTBClient_GetNormalizedModule_Call {
	_c.Call.Return(getNormalizedMoveModuleResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_GetNormalizedModule_Call) RunAndReturn(run func(ctx context.Context, packageId string, moduleId string) (models.GetNormalizedMoveModuleResponse, error)) *MockSuiPTBClient_GetNormalizedModule_Call {
	_c.Call.Return(run)
	return _c
}

// GetParentObjectID provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetParentObjectID(ctx context.Context, packageID string, moduleID string, pointerObjectName string) (string, error) {
	ret := _mock.Called(ctx, packageID, moduleID, pointerObjectName)

	if len(ret) == 0 {
		panic("no return value specified for GetParentObjectID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (string, error)); ok {
		return returnFunc(ctx, packageID, moduleID, pointerObjectName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) string); ok {
		r0 = returnFunc(ctx, packageID, moduleID, pointerObjectName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, packageID, moduleID, pointerObjectName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetParentObjectID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParentObjectID'
type MockSuiPTBClient_GetParentObjectID_Call struct {
	*mock.Call
}

// GetParentObjectID is a helper method to define mock.On call
//   - ctx context.Context
//   - packageID string
//   - moduleID string
//   - pointerObjectName string
func (_e *MockSuiPTBClient_Expecter) GetParentObjectID(ctx interface{}, packageID interface{}, moduleID interface{}, pointerObjectName interface{}) *MockSuiPTBClient_GetParentObjectID_Call {
	return &MockSuiPTBClient_GetParentObjectID_Call{Call: _e.mock.On("GetParentObjectID", ctx, packageID, moduleID, pointerObjectName)}
}

func (_c *MockSuiPTBClient_GetParentObjectID_Call) Run(run func(ctx context.Context, packageID string, moduleID string, pointerObjectName string)) *MockSuiPTBClient_GetParentObjectID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetParentObjectID_Call) Return(s string, err error) *MockSuiPTBClient_GetParentObjectID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSuiPTBClient_GetParentObjectID_Call) RunAndReturn(run func(ctx context.Context, packageID string, moduleID string, pointerObjectName string) (string, error)) *MockSuiPTBClient_GetParentObjectID_Call {
	_c.Call.Return(run)
	return _c
}

// GetReferenceGasPrice provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetReferenceGasPrice(ctx context.Context) (*big.Int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetReferenceGasPrice")
	}

	var r0 *big.Int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*big.Int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *big.Int); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetReferenceGasPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferenceGasPrice'
type MockSuiPTBClient_GetReferenceGasPrice_Call struct {
	*mock.Call
}

// GetReferenceGasPrice is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSuiPTBClient_Expecter) GetReferenceGasPrice(ctx interface{}) *MockSuiPTBClient_GetReferenceGasPrice_Call {
	return &MockSuiPTBClient_GetReferenceGasPrice_Call{Call: _e.mock.On("GetReferenceGasPrice", ctx)}
}

func (_c *MockSuiPTBClient_GetReferenceGasPrice_Call) Run(run func(ctx context.Context)) *MockSuiPTBClient_GetReferenceGasPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetReferenceGasPrice_Call) Return(intParam *big.Int, err error) *MockSuiPTBClient_GetReferenceGasPrice_Call {
	_c.Call.Return(intParam, err)
	return _c
}

func (_c *MockSuiPTBClient_GetReferenceGasPrice_Call) RunAndReturn(run func(ctx context.Context) (*big.Int, error)) *MockSuiPTBClient_GetReferenceGasPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetSUIBalance provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetSUIBalance(ctx context.Context, address string) (*v2.Balance, error) {
	ret := _mock.Called(ctx, address)

	if len(ret) == 0 {
		panic("no return value specified for GetSUIBalance")
	}

	var r0 *v2.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v2.Balance, error)); ok {
		return returnFunc(ctx, address)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v2.Balance); ok {
		r0 = returnFunc(ctx, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, address)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetSUIBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSUIBalance'
type MockSuiPTBClient_GetSUIBalance_Call struct {
	*mock.Call
}

// GetSUIBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
func (_e *MockSuiPTBClient_Expecter) GetSUIBalance(ctx interface{}, address interface{}) *MockSuiPTBClient_GetSUIBalance_Call {
	return &MockSuiPTBClient_GetSUIBalance_Call{Call: _e.mock.On("GetSUIBalance", ctx, address)}
}

func (_c *MockSuiPTBClient_GetSUIBalance_Call) Run(run func(ctx context.Context, address string)) *MockSuiPTBClient_GetSUIBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetSUIBalance_Call) Return(balance *v2.Balance, err error) *MockSuiPTBClient_GetSUIBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockSuiPTBClient_GetSUIBalance_Call) RunAndReturn(run func(ctx context.Context, address string) (*v2.Balance, error)) *MockSuiPTBClient_GetSUIBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransactionStatus provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetTransactionStatus(ctx context.Context, digest string) (client.TransactionResult, error) {
	ret := _mock.Called(ctx, digest)

	if len(ret) == 0 {
		panic("no return value specified for GetTransactionStatus")
	}

	var r0 client.TransactionResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (client.TransactionResult, error)); ok {
		return returnFunc(ctx, digest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) client.TransactionResult); ok {
		r0 = returnFunc(ctx, digest)
	} else {
		r0 = ret.Get(0).(client.TransactionResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, digest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetTransactionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransactionStatus'
type MockSuiPTBClient_GetTransactionStatus_Call struct {
	*mock.Call
}

// GetTransactionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - digest string
func (_e *MockSuiPTBClient_Expecter) GetTransactionStatus(ctx interface{}, digest interface{}) *MockSuiPTBClient_GetTransactionStatus_Call {
	return &MockSuiPTBClient_GetTransactionStatus_Call{Call: _e.mock.On("GetTransactionStatus", ctx, digest)}
}

func (_c *MockSuiPTBClient_GetTransactionStatus_Call) Run(run func(ctx context.Context, digest string)) *MockSuiPTBClient_GetTransactionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetTransactionStatus_Call) Return(transactionResult client.TransactionResult, err error) *MockSuiPTBClient_GetTransactionStatus_Call {
	_c.Call.Return(transactionResult, err)
	return _c
}

func (_c *MockSuiPTBClient_GetTransactionStatus_Call) RunAndReturn(run func(ctx context.Context, digest string) (client.TransactionResult, error)) *MockSuiPTBClient_GetTransactionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetValuesFromPackageOwnedObjectField provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) GetValuesFromPackageOwnedObjectField(ctx context.Context, packageID string, moduleID string, objectName string, fieldKeys []string) (map[string]string, error) {
	ret := _mock.Called(ctx, packageID, moduleID, objectName, fieldKeys)

	if len(ret) == 0 {
		panic("no return value specified for GetValuesFromPackageOwnedObjectField")
	}

	var r0 map[string]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) (map[string]string, error)); ok {
		return returnFunc(ctx, packageID, moduleID, objectName, fieldKeys)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string) map[string]string); ok {
		r0 = returnFunc(ctx, packageID, moduleID, objectName, fieldKeys)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []string) error); ok {
		r1 = returnFunc(ctx, packageID, moduleID, objectName, fieldKeys)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetValuesFromPackageOwnedObjectField'
type MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call struct {
	*mock.Call
}

// GetValuesFromPackageOwnedObjectField is a helper method to define mock.On call
//   - ctx context.Context
//   - packageID string
//   - moduleID string
//   - objectName string
//   - fieldKeys []string
func (_e *MockSuiPTBClient_Expecter) GetValuesFromPackageOwnedObjectField(ctx interface{}, packageID interface{}, moduleID interface{}, objectName interface{}, fieldKeys interface{}) *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call {
	return &MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call{Call: _e.mock.On("GetValuesFromPackageOwnedObjectField", ctx, packageID, moduleID, objectName, fieldKeys)}
}

func (_c *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call) Run(run func(ctx context.Context, packageID string, moduleID string, objectName string, fieldKeys []string)) *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call) Return(stringToString map[string]string, err error) *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call {
	_c.Call.Return(stringToString, err)
	return _c
}

func (_c *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call) RunAndReturn(run func(ctx context.Context, packageID string, moduleID string, objectName string, fieldKeys []string) (map[string]string, error)) *MockSuiPTBClient_GetValuesFromPackageOwnedObjectField_Call {
	_c.Call.Return(run)
	return _c
}

// HashTxBytes provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) HashTxBytes(txBytes []byte) []byte {
	ret := _mock.Called(txBytes)

	if len(ret) == 0 {
		panic("no return value specified for HashTxBytes")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func([]byte) []byte); ok {
		r0 = returnFunc(txBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockSuiPTBClient_HashTxBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashTxBytes'
type MockSuiPTBClient_HashTxBytes_Call struct {
	*mock.Call
}

// HashTxBytes is a helper method to define mock.On call
//   - txBytes []byte
func (_e *MockSuiPTBClient_Expecter) HashTxBytes(txBytes interface{}) *MockSuiPTBClient_HashTxBytes_Call {
	return &MockSuiPTBClient_HashTxBytes_Call{Call: _e.mock.On("HashTxBytes", txBytes)}
}

func (_c *MockSuiPTBClient_HashTxBytes_Call) Run(run func(txBytes []byte)) *MockSuiPTBClient_HashTxBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_HashTxBytes_Call) Return(bytes []byte) *MockSuiPTBClient_HashTxBytes_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockSuiPTBClient_HashTxBytes_Call) RunAndReturn(run func(txBytes []byte) []byte) *MockSuiPTBClient_HashTxBytes_Call {
	_c.Call.Return(run)
	return _c
}

// LoadModulePackageIds provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) LoadModulePackageIds(ctx context.Context, packageId string, module string) ([]string, error) {
	ret := _mock.Called(ctx, packageId, module)

	if len(ret) == 0 {
		panic("no return value specified for LoadModulePackageIds")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]string, error)); ok {
		return returnFunc(ctx, packageId, module)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []string); ok {
		r0 = returnFunc(ctx, packageId, module)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, packageId, module)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_LoadModulePackageIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadModulePackageIds'
type MockSuiPTBClient_LoadModulePackageIds_Call struct {
	*mock.Call
}

// LoadModulePackageIds is a helper method to define mock.On call
//   - ctx context.Context
//   - packageId string
//   - module string
func (_e *MockSuiPTBClient_Expecter) LoadModulePackageIds(ctx interface{}, packageId interface{}, module interface{}) *MockSuiPTBClient_LoadModulePackageIds_Call {
	return &MockSuiPTBClient_LoadModulePackageIds_Call{Call: _e.mock.On("LoadModulePackageIds", ctx, packageId, module)}
}

func (_c *MockSuiPTBClient_LoadModulePackageIds_Call) Run(run func(ctx context.Context, packageId string, module string)) *MockSuiPTBClient_LoadModulePackageIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_LoadModulePackageIds_Call) Return(strings []string, err error) *MockSuiPTBClient_LoadModulePackageIds_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSuiPTBClient_LoadModulePackageIds_Call) RunAndReturn(run func(ctx context.Context, packageId string, module string) ([]string, error)) *MockSuiPTBClient_LoadModulePackageIds_Call {
	_c.Call.Return(run)
	return _c
}

// MoveCall provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) MoveCall(ctx context.Context, req client.MoveCallRequest) (client.TxnMetaData, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for MoveCall")
	}

	var r0 client.TxnMetaData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.MoveCallRequest) (client.TxnMetaData, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.MoveCallRequest) client.TxnMetaData); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(client.TxnMetaData)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.MoveCallRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_MoveCall_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveCall'
type MockSuiPTBClient_MoveCall_Call struct {
	*mock.Call
}

// MoveCall is a helper method to define mock.On call
//   - ctx context.Context
//   - req client.MoveCallRequest
func (_e *MockSuiPTBClient_Expecter) MoveCall(ctx interface{}, req interface{}) *MockSuiPTBClient_MoveCall_Call {
	return &MockSuiPTBClient_MoveCall_Call{Call: _e.mock.On("MoveCall", ctx, req)}
}

func (_c *MockSuiPTBClient_MoveCall_Call) Run(run func(ctx context.Context, req client.MoveCallRequest)) *MockSuiPTBClient_MoveCall_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.MoveCallRequest
		if args[1] != nil {
			arg1 = args[1].(client.MoveCallRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_MoveCall_Call) Return(txnMetaData client.TxnMetaData, err error) *MockSuiPTBClient_MoveCall_Call {
	_c.Call.Return(txnMetaData, err)
	return _c
}

func (_c *MockSuiPTBClient_MoveCall_Call) RunAndReturn(run func(ctx context.Context, req client.MoveCallRequest) (client.TxnMetaData, error)) *MockSuiPTBClient_MoveCall_Call {
	_c.Call.Return(run)
	return _c
}

// QueryCoinsByAddress provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) QueryCoinsByAddress(ctx context.Context, address string, coinType string) ([]*v2.Object, error) {
	ret := _mock.Called(ctx, address, coinType)

	if len(ret) == 0 {
		panic("no return value specified for QueryCoinsByAddress")
	}

	var r0 []*v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]*v2.Object, error)); ok {
		return returnFunc(ctx, address, coinType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []*v2.Object); ok {
		r0 = returnFunc(ctx, address, coinType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, address, coinType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_QueryCoinsByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryCoinsByAddress'
type MockSuiPTBClient_QueryCoinsByAddress_Call struct {
	*mock.Call
}

// QueryCoinsByAddress is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - coinType string
func (_e *MockSuiPTBClient_Expecter) QueryCoinsByAddress(ctx interface{}, address interface{}, coinType interface{}) *MockSuiPTBClient_QueryCoinsByAddress_Call {
	return &MockSuiPTBClient_QueryCoinsByAddress_Call{Call: _e.mock.On("QueryCoinsByAddress", ctx, address, coinType)}
}

func (_c *MockSuiPTBClient_QueryCoinsByAddress_Call) Run(run func(ctx context.Context, address string, coinType string)) *MockSuiPTBClient_QueryCoinsByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_QueryCoinsByAddress_Call) Return(objects []*v2.Object, err error) *MockSuiPTBClient_QueryCoinsByAddress_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MockSuiPTBClient_QueryCoinsByAddress_Call) RunAndReturn(run func(ctx context.Context, address string, coinType string) ([]*v2.Object, error)) *MockSuiPTBClient_QueryCoinsByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// QueryEvents provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) QueryEvents(ctx context.Context, filter client.EventFilterByMoveEventModule, limit *uint, cursor *client.EventId, sortOptions *client.QuerySortOptions) (*models.PaginatedEventsResponse, error) {
	ret := _mock.Called(ctx, filter, limit, cursor, sortOptions)

	if len(ret) == 0 {
		panic("no return value specified for QueryEvents")
	}

	var r0 *models.PaginatedEventsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.EventFilterByMoveEventModule, *uint, *client.EventId, *client.QuerySortOptions) (*models.PaginatedEventsResponse, error)); ok {
		return returnFunc(ctx, filter, limit, cursor, sortOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.EventFilterByMoveEventModule, *uint, *client.EventId, *client.QuerySortOptions) *models.PaginatedEventsResponse); ok {
		r0 = returnFunc(ctx, filter, limit, cursor, sortOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaginatedEventsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, client.EventFilterByMoveEventModule, *uint, *client.EventId, *client.QuerySortOptions) error); ok {
		r1 = returnFunc(ctx, filter, limit, cursor, sortOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_QueryEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryEvents'
type MockSuiPTBClient_QueryEvents_Call struct {
	*mock.Call
}

// QueryEvents is a helper method to define mock.On call
//   - ctx context.Context
//   - filter client.EventFilterByMoveEventModule
//   - limit *uint
//   - cursor *client.EventId
//   - sortOptions *client.QuerySortOptions
func (_e *MockSuiPTBClient_Expecter) QueryEvents(ctx interface{}, filter interface{}, limit interface{}, cursor interface{}, sortOptions interface{}) *MockSuiPTBClient_QueryEvents_Call {
	return &MockSuiPTBClient_QueryEvents_Call{Call: _e.mock.On("QueryEvents", ctx, filter, limit, cursor, sortOptions)}
}

func (_c *MockSuiPTBClient_QueryEvents_Call) Run(run func(ctx context.Context, filter client.EventFilterByMoveEventModule, limit *uint, cursor *client.EventId, sortOptions *client.QuerySortOptions)) *MockSuiPTBClient_QueryEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 client.EventFilterByMoveEventModule
		if args[1] != nil {
			arg1 = args[1].(client.EventFilterByMoveEventModule)
		}
		var arg2 *uint
		if args[2] != nil {
			arg2 = args[2].(*uint)
		}
		var arg3 *client.EventId
		if args[3] != nil {
			arg3 = args[3].(*client.EventId)
		}
		var arg4 *client.QuerySortOptions
		if args[4] != nil {
			arg4 = args[4].(*client.QuerySortOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_QueryEvents_Call) Return(paginatedEventsResponse *models.PaginatedEventsResponse, err error) *MockSuiPTBClient_QueryEvents_Call {
	_c.Call.Return(paginatedEventsResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_QueryEvents_Call) RunAndReturn(run func(ctx context.Context, filter client.EventFilterByMoveEventModule, limit *uint, cursor *client.EventId, sortOptions *client.QuerySortOptions) (*models.PaginatedEventsResponse, error)) *MockSuiPTBClient_QueryEvents_Call {
	_c.Call.Return(run)
	return _c
}

// QueryTransactions provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) QueryTransactions(ctx context.Context, fromAddress string, cursor *v2.Checkpoint, limit *uint64) ([]*v2.ExecutedTransaction, error) {
	ret := _mock.Called(ctx, fromAddress, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for QueryTransactions")
	}

	var r0 []*v2.ExecutedTransaction
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v2.Checkpoint, *uint64) ([]*v2.ExecutedTransaction, error)); ok {
		return returnFunc(ctx, fromAddress, cursor, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v2.Checkpoint, *uint64) []*v2.ExecutedTransaction); ok {
		r0 = returnFunc(ctx, fromAddress, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.ExecutedTransaction)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v2.Checkpoint, *uint64) error); ok {
		r1 = returnFunc(ctx, fromAddress, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_QueryTransactions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryTransactions'
type MockSuiPTBClient_QueryTransactions_Call struct {
	*mock.Call
}

// QueryTransactions is a helper method to define mock.On call
//   - ctx context.Context
//   - fromAddress string
//   - cursor *v2.Checkpoint
//   - limit *uint64
func (_e *MockSuiPTBClient_Expecter) QueryTransactions(ctx interface{}, fromAddress interface{}, cursor interface{}, limit interface{}) *MockSuiPTBClient_QueryTransactions_Call {
	return &MockSuiPTBClient_QueryTransactions_Call{Call: _e.mock.On("QueryTransactions", ctx, fromAddress, cursor, limit)}
}

func (_c *MockSuiPTBClient_QueryTransactions_Call) Run(run func(ctx context.Context, fromAddress string, cursor *v2.Checkpoint, limit *uint64)) *MockSuiPTBClient_QueryTransactions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v2.Checkpoint
		if args[2] != nil {
			arg2 = args[2].(*v2.Checkpoint)
		}
		var arg3 *uint64
		if args[3] != nil {
			arg3 = args[3].(*uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_QueryTransactions_Call) Return(executedTransactions []*v2.ExecutedTransaction, err error) *MockSuiPTBClient_QueryTransactions_Call {
	_c.Call.Return(executedTransactions, err)
	return _c
}

func (_c *MockSuiPTBClient_QueryTransactions_Call) RunAndReturn(run func(ctx context.Context, fromAddress string, cursor *v2.Checkpoint, limit *uint64) ([]*v2.ExecutedTransaction, error)) *MockSuiPTBClient_QueryTransactions_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFilterOwnedObjectIds provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) ReadFilterOwnedObjectIds(ctx context.Context, ownerAddress string, structType string, cursor []byte) ([]*v2.Object, error) {
	ret := _mock.Called(ctx, ownerAddress, structType, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ReadFilterOwnedObjectIds")
	}

	var r0 []*v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) ([]*v2.Object, error)); ok {
		return returnFunc(ctx, ownerAddress, structType, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []byte) []*v2.Object); ok {
		r0 = returnFunc(ctx, ownerAddress, structType, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []byte) error); ok {
		r1 = returnFunc(ctx, ownerAddress, structType, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_ReadFilterOwnedObjectIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFilterOwnedObjectIds'
type MockSuiPTBClient_ReadFilterOwnedObjectIds_Call struct {
	*mock.Call
}

// ReadFilterOwnedObjectIds is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerAddress string
//   - structType string
//   - cursor []byte
func (_e *MockSuiPTBClient_Expecter) ReadFilterOwnedObjectIds(ctx interface{}, ownerAddress interface{}, structType interface{}, cursor interface{}) *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call {
	return &MockSuiPTBClient_ReadFilterOwnedObjectIds_Call{Call: _e.mock.On("ReadFilterOwnedObjectIds", ctx, ownerAddress, structType, cursor)}
}

func (_c *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call) Run(run func(ctx context.Context, ownerAddress string, structType string, cursor []byte)) *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []byte
		if args[3] != nil {
			arg3 = args[3].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call) Return(objects []*v2.Object, err error) *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call) RunAndReturn(run func(ctx context.Context, ownerAddress string, structType string, cursor []byte) ([]*v2.Object, error)) *MockSuiPTBClient_ReadFilterOwnedObjectIds_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFunction provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) ReadFunction(ctx context.Context, packageId string, module string, function string, args []any, argTypes []string, typeArgs []string) ([]any, error) {
	ret := _mock.Called(ctx, packageId, module, function, args, argTypes, typeArgs)

	if len(ret) == 0 {
		panic("no return value specified for ReadFunction")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []any, []string, []string) ([]any, error)); ok {
		return returnFunc(ctx, packageId, module, function, args, argTypes, typeArgs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []any, []string, []string) []any); ok {
		r0 = returnFunc(ctx, packageId, module, function, args, argTypes, typeArgs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, []any, []string, []string) error); ok {
		r1 = returnFunc(ctx, packageId, module, function, args, argTypes, typeArgs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_ReadFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFunction'
type MockSuiPTBClient_ReadFunction_Call struct {
	*mock.Call
}

// ReadFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - packageId string
//   - module string
//   - function string
//   - args []any
//   - argTypes []string
//   - typeArgs []string
func (_e *MockSuiPTBClient_Expecter) ReadFunction(ctx interface{}, packageId interface{}, module interface{}, function interface{}, args interface{}, argTypes interface{}, typeArgs interface{}) *MockSuiPTBClient_ReadFunction_Call {
	return &MockSuiPTBClient_ReadFunction_Call{Call: _e.mock.On("ReadFunction", ctx, packageId, module, function, args, argTypes, typeArgs)}
}

func (_c *MockSuiPTBClient_ReadFunction_Call) Run(run func(ctx context.Context, packageId string, module string, function string, args []any, argTypes []string, typeArgs []string)) *MockSuiPTBClient_ReadFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []any
		if args[4] != nil {
			arg4 = args[4].([]any)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		var arg6 []string
		if args[6] != nil {
			arg6 = args[6].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_ReadFunction_Call) Return(vs []any, err error) *MockSuiPTBClient_ReadFunction_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockSuiPTBClient_ReadFunction_Call) RunAndReturn(run func(ctx context.Context, packageId string, module string, function string, args []any, argTypes []string, typeArgs []string) ([]any, error)) *MockSuiPTBClient_ReadFunction_Call {
	_c.Call.Return(run)
	return _c
}

// ReadObjectId provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) ReadObjectId(ctx context.Context, objectId string) (*v2.Object, error) {
	ret := _mock.Called(ctx, objectId)

	if len(ret) == 0 {
		panic("no return value specified for ReadObjectId")
	}

	var r0 *v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*v2.Object, error)); ok {
		return returnFunc(ctx, objectId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *v2.Object); ok {
		r0 = returnFunc(ctx, objectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, objectId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_ReadObjectId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadObjectId'
type MockSuiPTBClient_ReadObjectId_Call struct {
	*mock.Call
}

// ReadObjectId is a helper method to define mock.On call
//   - ctx context.Context
//   - objectId string
func (_e *MockSuiPTBClient_Expecter) ReadObjectId(ctx interface{}, objectId interface{}) *MockSuiPTBClient_ReadObjectId_Call {
	return &MockSuiPTBClient_ReadObjectId_Call{Call: _e.mock.On("ReadObjectId", ctx, objectId)}
}

func (_c *MockSuiPTBClient_ReadObjectId_Call) Run(run func(ctx context.Context, objectId string)) *MockSuiPTBClient_ReadObjectId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_ReadObjectId_Call) Return(object *v2.Object, err error) *MockSuiPTBClient_ReadObjectId_Call {
	_c.Call.Return(object, err)
	return _c
}

func (_c *MockSuiPTBClient_ReadObjectId_Call) RunAndReturn(run func(ctx context.Context, objectId string) (*v2.Object, error)) *MockSuiPTBClient_ReadObjectId_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOwnedObjects provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) ReadOwnedObjects(ctx context.Context, ownerAddress string, cursor []byte) ([]*v2.Object, error) {
	ret := _mock.Called(ctx, ownerAddress, cursor)

	if len(ret) == 0 {
		panic("no return value specified for ReadOwnedObjects")
	}

	var r0 []*v2.Object
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) ([]*v2.Object, error)); ok {
		return returnFunc(ctx, ownerAddress, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) []*v2.Object); ok {
		r0 = returnFunc(ctx, ownerAddress, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v2.Object)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, ownerAddress, cursor)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_ReadOwnedObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadOwnedObjects'
type MockSuiPTBClient_ReadOwnedObjects_Call struct {
	*mock.Call
}

// ReadOwnedObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - ownerAddress string
//   - cursor []byte
func (_e *MockSuiPTBClient_Expecter) ReadOwnedObjects(ctx interface{}, ownerAddress interface{}, cursor interface{}) *MockSuiPTBClient_ReadOwnedObjects_Call {
	return &MockSuiPTBClient_ReadOwnedObjects_Call{Call: _e.mock.On("ReadOwnedObjects", ctx, ownerAddress, cursor)}
}

func (_c *MockSuiPTBClient_ReadOwnedObjects_Call) Run(run func(ctx context.Context, ownerAddress string, cursor []byte)) *MockSuiPTBClient_ReadOwnedObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_ReadOwnedObjects_Call) Return(objects []*v2.Object, err error) *MockSuiPTBClient_ReadOwnedObjects_Call {
	_c.Call.Return(objects, err)
	return _c
}

func (_c *MockSuiPTBClient_ReadOwnedObjects_Call) RunAndReturn(run func(ctx context.Context, ownerAddress string, cursor []byte) ([]*v2.Object, error)) *MockSuiPTBClient_ReadOwnedObjects_Call {
	_c.Call.Return(run)
	return _c
}

// SendTransaction provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) SendTransaction(ctx context.Context, execRequest *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error) {
	ret := _mock.Called(ctx, execRequest)

	if len(ret) == 0 {
		panic("no return value specified for SendTransaction")
	}

	var r0 *v2.ExecuteTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error)); ok {
		return returnFunc(ctx, execRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v2.ExecuteTransactionRequest) *v2.ExecuteTransactionResponse); ok {
		r0 = returnFunc(ctx, execRequest)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ExecuteTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v2.ExecuteTransactionRequest) error); ok {
		r1 = returnFunc(ctx, execRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_SendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTransaction'
type MockSuiPTBClient_SendTransaction_Call struct {
	*mock.Call
}

// SendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - execRequest *v2.ExecuteTransactionRequest
func (_e *MockSuiPTBClient_Expecter) SendTransaction(ctx interface{}, execRequest interface{}) *MockSuiPTBClient_SendTransaction_Call {
	return &MockSuiPTBClient_SendTransaction_Call{Call: _e.mock.On("SendTransaction", ctx, execRequest)}
}

func (_c *MockSuiPTBClient_SendTransaction_Call) Run(run func(ctx context.Context, execRequest *v2.ExecuteTransactionRequest)) *MockSuiPTBClient_SendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v2.ExecuteTransactionRequest
		if args[1] != nil {
			arg1 = args[1].(*v2.ExecuteTransactionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_SendTransaction_Call) Return(executeTransactionResponse *v2.ExecuteTransactionResponse, err error) *MockSuiPTBClient_SendTransaction_Call {
	_c.Call.Return(executeTransactionResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_SendTransaction_Call) RunAndReturn(run func(ctx context.Context, execRequest *v2.ExecuteTransactionRequest) (*v2.ExecuteTransactionResponse, error)) *MockSuiPTBClient_SendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SetCachedValue provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) SetCachedValue(key string, value any) {
	_mock.Called(key, value)
	return
}

// MockSuiPTBClient_SetCachedValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCachedValue'
type MockSuiPTBClient_SetCachedValue_Call struct {
	*mock.Call
}

// SetCachedValue is a helper method to define mock.On call
//   - key string
//   - value any
func (_e *MockSuiPTBClient_Expecter) SetCachedValue(key interface{}, value interface{}) *MockSuiPTBClient_SetCachedValue_Call {
	return &MockSuiPTBClient_SetCachedValue_Call{Call: _e.mock.On("SetCachedValue", key, value)}
}

func (_c *MockSuiPTBClient_SetCachedValue_Call) Run(run func(key string, value any)) *MockSuiPTBClient_SetCachedValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_SetCachedValue_Call) Return() *MockSuiPTBClient_SetCachedValue_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSuiPTBClient_SetCachedValue_Call) RunAndReturn(run func(key string, value any)) *MockSuiPTBClient_SetCachedValue_Call {
	_c.Run(run)
	return _c
}

// SetCachedValues provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) SetCachedValues(keyValues map[string]any) {
	_mock.Called(keyValues)
	return
}

// MockSuiPTBClient_SetCachedValues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetCachedValues'
type MockSuiPTBClient_SetCachedValues_Call struct {
	*mock.Call
}

// SetCachedValues is a helper method to define mock.On call
//   - keyValues map[string]any
func (_e *MockSuiPTBClient_Expecter) SetCachedValues(keyValues interface{}) *MockSuiPTBClient_SetCachedValues_Call {
	return &MockSuiPTBClient_SetCachedValues_Call{Call: _e.mock.On("SetCachedValues", keyValues)}
}

func (_c *MockSuiPTBClient_SetCachedValues_Call) Run(run func(keyValues map[string]any)) *MockSuiPTBClient_SetCachedValues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]any
		if args[0] != nil {
			arg0 = args[0].(map[string]any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_SetCachedValues_Call) Return() *MockSuiPTBClient_SetCachedValues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSuiPTBClient_SetCachedValues_Call) RunAndReturn(run func(keyValues map[string]any)) *MockSuiPTBClient_SetCachedValues_Call {
	_c.Run(run)
	return _c
}

// SignAndSendTransaction provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) SignAndSendTransaction(ctx context.Context, txBytesRaw string, signerPublicKey []byte) (*v2.ExecuteTransactionResponse, error) {
	ret := _mock.Called(ctx, txBytesRaw, signerPublicKey)

	if len(ret) == 0 {
		panic("no return value specified for SignAndSendTransaction")
	}

	var r0 *v2.ExecuteTransactionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) (*v2.ExecuteTransactionResponse, error)); ok {
		return returnFunc(ctx, txBytesRaw, signerPublicKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []byte) *v2.ExecuteTransactionResponse); ok {
		r0 = returnFunc(ctx, txBytesRaw, signerPublicKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.ExecuteTransactionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = returnFunc(ctx, txBytesRaw, signerPublicKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_SignAndSendTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignAndSendTransaction'
type MockSuiPTBClient_SignAndSendTransaction_Call struct {
	*mock.Call
}

// SignAndSendTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txBytesRaw string
//   - signerPublicKey []byte
func (_e *MockSuiPTBClient_Expecter) SignAndSendTransaction(ctx interface{}, txBytesRaw interface{}, signerPublicKey interface{}) *MockSuiPTBClient_SignAndSendTransaction_Call {
	return &MockSuiPTBClient_SignAndSendTransaction_Call{Call: _e.mock.On("SignAndSendTransaction", ctx, txBytesRaw, signerPublicKey)}
}

func (_c *MockSuiPTBClient_SignAndSendTransaction_Call) Run(run func(ctx context.Context, txBytesRaw string, signerPublicKey []byte)) *MockSuiPTBClient_SignAndSendTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_SignAndSendTransaction_Call) Return(executeTransactionResponse *v2.ExecuteTransactionResponse, err error) *MockSuiPTBClient_SignAndSendTransaction_Call {
	_c.Call.Return(executeTransactionResponse, err)
	return _c
}

func (_c *MockSuiPTBClient_SignAndSendTransaction_Call) RunAndReturn(run func(ctx context.Context, txBytesRaw string, signerPublicKey []byte) (*v2.ExecuteTransactionResponse, error)) *MockSuiPTBClient_SignAndSendTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// SimulatePTB provides a mock function for the type MockSuiPTBClient
func (_mock *MockSuiPTBClient) SimulatePTB(ctx context.Context, bcsBytes []byte) ([]any, error) {
	ret := _mock.Called(ctx, bcsBytes)

	if len(ret) == 0 {
		panic("no return value specified for SimulatePTB")
	}

	var r0 []any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) ([]any, error)); ok {
		return returnFunc(ctx, bcsBytes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []byte) []any); ok {
		r0 = returnFunc(ctx, bcsBytes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = returnFunc(ctx, bcsBytes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSuiPTBClient_SimulatePTB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SimulatePTB'
type MockSuiPTBClient_SimulatePTB_Call struct {
	*mock.Call
}

// SimulatePTB is a helper method to define mock.On call
//   - ctx context.Context
//   - bcsBytes []byte
func (_e *MockSuiPTBClient_Expecter) SimulatePTB(ctx interface{}, bcsBytes interface{}) *MockSuiPTBClient_SimulatePTB_Call {
	return &MockSuiPTBClient_SimulatePTB_Call{Call: _e.mock.On("SimulatePTB", ctx, bcsBytes)}
}

func (_c *MockSuiPTBClient_SimulatePTB_Call) Run(run func(ctx context.Context, bcsBytes []byte)) *MockSuiPTBClient_SimulatePTB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSuiPTBClient_SimulatePTB_Call) Return(vs []any, err error) *MockSuiPTBClient_SimulatePTB_Call {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *MockSuiPTBClient_SimulatePTB_Call) RunAndReturn(run func(ctx context.Context, bcsBytes []byte) ([]any, error)) *MockSuiPTBClient_SimulatePTB_Call {
	_c.Call.Return(run)
	return _c
}
