// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analyzer

import (
	"github.com/ethereum/go-ethereum/accounts/abi"
	"github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEVMABIRegistry creates a new instance of MockEVMABIRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEVMABIRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEVMABIRegistry {
	mock := &MockEVMABIRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEVMABIRegistry is an autogenerated mock type for the EVMABIRegistry type
type MockEVMABIRegistry struct {
	mock.Mock
}

type MockEVMABIRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEVMABIRegistry) EXPECT() *MockEVMABIRegistry_Expecter {
	return &MockEVMABIRegistry_Expecter{mock: &_m.Mock}
}

// AddABI provides a mock function for the type MockEVMABIRegistry
func (_mock *MockEVMABIRegistry) AddABI(contractType deployment.TypeAndVersion, abi string) error {
	ret := _mock.Called(contractType, abi)

	if len(ret) == 0 {
		panic("no return value specified for AddABI")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(deployment.TypeAndVersion, string) error); ok {
		r0 = returnFunc(contractType, abi)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEVMABIRegistry_AddABI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddABI'
type MockEVMABIRegistry_AddABI_Call struct {
	*mock.Call
}

// AddABI is a helper method to define mock.On call
//   - contractType deployment.TypeAndVersion
//   - abi string
func (_e *MockEVMABIRegistry_Expecter) AddABI(contractType interface{}, abi interface{}) *MockEVMABIRegistry_AddABI_Call {
	return &MockEVMABIRegistry_AddABI_Call{Call: _e.mock.On("AddABI", contractType, abi)}
}

func (_c *MockEVMABIRegistry_AddABI_Call) Run(run func(contractType deployment.TypeAndVersion, abi string)) *MockEVMABIRegistry_AddABI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 deployment.TypeAndVersion
		if args[0] != nil {
			arg0 = args[0].(deployment.TypeAndVersion)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMABIRegistry_AddABI_Call) Return(err error) *MockEVMABIRegistry_AddABI_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEVMABIRegistry_AddABI_Call) RunAndReturn(run func(contractType deployment.TypeAndVersion, abi string) error) *MockEVMABIRegistry_AddABI_Call {
	_c.Call.Return(run)
	return _c
}

// GetABIByAddress provides a mock function for the type MockEVMABIRegistry
func (_mock *MockEVMABIRegistry) GetABIByAddress(chainSelector uint64, address string) (*abi.ABI, string, error) {
	ret := _mock.Called(chainSelector, address)

	if len(ret) == 0 {
		panic("no return value specified for GetABIByAddress")
	}

	var r0 *abi.ABI
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) (*abi.ABI, string, error)); ok {
		return returnFunc(chainSelector, address)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *abi.ABI); ok {
		r0 = returnFunc(chainSelector, address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*abi.ABI)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, string) string); ok {
		r1 = returnFunc(chainSelector, address)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, string) error); ok {
		r2 = returnFunc(chainSelector, address)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEVMABIRegistry_GetABIByAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetABIByAddress'
type MockEVMABIRegistry_GetABIByAddress_Call struct {
	*mock.Call
}

// GetABIByAddress is a helper method to define mock.On call
//   - chainSelector uint64
//   - address string
func (_e *MockEVMABIRegistry_Expecter) GetABIByAddress(chainSelector interface{}, address interface{}) *MockEVMABIRegistry_GetABIByAddress_Call {
	return &MockEVMABIRegistry_GetABIByAddress_Call{Call: _e.mock.On("GetABIByAddress", chainSelector, address)}
}

func (_c *MockEVMABIRegistry_GetABIByAddress_Call) Run(run func(chainSelector uint64, address string)) *MockEVMABIRegistry_GetABIByAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEVMABIRegistry_GetABIByAddress_Call) Return(aBI *abi.ABI, s string, err error) *MockEVMABIRegistry_GetABIByAddress_Call {
	_c.Call.Return(aBI, s, err)
	return _c
}

func (_c *MockEVMABIRegistry_GetABIByAddress_Call) RunAndReturn(run func(chainSelector uint64, address string) (*abi.ABI, string, error)) *MockEVMABIRegistry_GetABIByAddress_Call {
	_c.Call.Return(run)
	return _c
}

// GetABIByType provides a mock function for the type MockEVMABIRegistry
func (_mock *MockEVMABIRegistry) GetABIByType(typeAndVersion deployment.TypeAndVersion) (*abi.ABI, string, error) {
	ret := _mock.Called(typeAndVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetABIByType")
	}

	var r0 *abi.ABI
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(deployment.TypeAndVersion) (*abi.ABI, string, error)); ok {
		return returnFunc(typeAndVersion)
	}
	if returnFunc, ok := ret.Get(0).(func(deployment.TypeAndVersion) *abi.ABI); ok {
		r0 = returnFunc(typeAndVersion)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*abi.ABI)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(deployment.TypeAndVersion) string); ok {
		r1 = returnFunc(typeAndVersion)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(deployment.TypeAndVersion) error); ok {
		r2 = returnFunc(typeAndVersion)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEVMABIRegistry_GetABIByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetABIByType'
type MockEVMABIRegistry_GetABIByType_Call struct {
	*mock.Call
}

// GetABIByType is a helper method to define mock.On call
//   - typeAndVersion deployment.TypeAndVersion
func (_e *MockEVMABIRegistry_Expecter) GetABIByType(typeAndVersion interface{}) *MockEVMABIRegistry_GetABIByType_Call {
	return &MockEVMABIRegistry_GetABIByType_Call{Call: _e.mock.On("GetABIByType", typeAndVersion)}
}

func (_c *MockEVMABIRegistry_GetABIByType_Call) Run(run func(typeAndVersion deployment.TypeAndVersion)) *MockEVMABIRegistry_GetABIByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 deployment.TypeAndVersion
		if args[0] != nil {
			arg0 = args[0].(deployment.TypeAndVersion)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEVMABIRegistry_GetABIByType_Call) Return(aBI *abi.ABI, s string, err error) *MockEVMABIRegistry_GetABIByType_Call {
	_c.Call.Return(aBI, s, err)
	return _c
}

func (_c *MockEVMABIRegistry_GetABIByType_Call) RunAndReturn(run func(typeAndVersion deployment.TypeAndVersion) (*abi.ABI, string, error)) *MockEVMABIRegistry_GetABIByType_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllABIs provides a mock function for the type MockEVMABIRegistry
func (_mock *MockEVMABIRegistry) GetAllABIs() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllABIs")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockEVMABIRegistry_GetAllABIs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllABIs'
type MockEVMABIRegistry_GetAllABIs_Call struct {
	*mock.Call
}

// GetAllABIs is a helper method to define mock.On call
func (_e *MockEVMABIRegistry_Expecter) GetAllABIs() *MockEVMABIRegistry_GetAllABIs_Call {
	return &MockEVMABIRegistry_GetAllABIs_Call{Call: _e.mock.On("GetAllABIs")}
}

func (_c *MockEVMABIRegistry_GetAllABIs_Call) Run(run func()) *MockEVMABIRegistry_GetAllABIs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEVMABIRegistry_GetAllABIs_Call) Return(stringToString map[string]string) *MockEVMABIRegistry_GetAllABIs_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockEVMABIRegistry_GetAllABIs_Call) RunAndReturn(run func() map[string]string) *MockEVMABIRegistry_GetAllABIs_Call {
	_c.Call.Return(run)
	return _c
}
