// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package analyzer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProposalContext creates a new instance of MockProposalContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProposalContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProposalContext {
	mock := &MockProposalContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProposalContext is an autogenerated mock type for the ProposalContext type
type MockProposalContext struct {
	mock.Mock
}

type MockProposalContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProposalContext) EXPECT() *MockProposalContext_Expecter {
	return &MockProposalContext_Expecter{mock: &_m.Mock}
}

// FieldsContext provides a mock function for the type MockProposalContext
func (_mock *MockProposalContext) FieldsContext(chainSelector uint64) *FieldContext {
	ret := _mock.Called(chainSelector)

	if len(ret) == 0 {
		panic("no return value specified for FieldsContext")
	}

	var r0 *FieldContext
	if returnFunc, ok := ret.Get(0).(func(uint64) *FieldContext); ok {
		r0 = returnFunc(chainSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FieldContext)
		}
	}
	return r0
}

// MockProposalContext_FieldsContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FieldsContext'
type MockProposalContext_FieldsContext_Call struct {
	*mock.Call
}

// FieldsContext is a helper method to define mock.On call
//   - chainSelector uint64
func (_e *MockProposalContext_Expecter) FieldsContext(chainSelector interface{}) *MockProposalContext_FieldsContext_Call {
	return &MockProposalContext_FieldsContext_Call{Call: _e.mock.On("FieldsContext", chainSelector)}
}

func (_c *MockProposalContext_FieldsContext_Call) Run(run func(chainSelector uint64)) *MockProposalContext_FieldsContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProposalContext_FieldsContext_Call) Return(fieldContext *FieldContext) *MockProposalContext_FieldsContext_Call {
	_c.Call.Return(fieldContext)
	return _c
}

func (_c *MockProposalContext_FieldsContext_Call) RunAndReturn(run func(chainSelector uint64) *FieldContext) *MockProposalContext_FieldsContext_Call {
	_c.Call.Return(run)
	return _c
}

// GetEVMRegistry provides a mock function for the type MockProposalContext
func (_mock *MockProposalContext) GetEVMRegistry() EVMABIRegistry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEVMRegistry")
	}

	var r0 EVMABIRegistry
	if returnFunc, ok := ret.Get(0).(func() EVMABIRegistry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(EVMABIRegistry)
		}
	}
	return r0
}

// MockProposalContext_GetEVMRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEVMRegistry'
type MockProposalContext_GetEVMRegistry_Call struct {
	*mock.Call
}

// GetEVMRegistry is a helper method to define mock.On call
func (_e *MockProposalContext_Expecter) GetEVMRegistry() *MockProposalContext_GetEVMRegistry_Call {
	return &MockProposalContext_GetEVMRegistry_Call{Call: _e.mock.On("GetEVMRegistry")}
}

func (_c *MockProposalContext_GetEVMRegistry_Call) Run(run func()) *MockProposalContext_GetEVMRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProposalContext_GetEVMRegistry_Call) Return(eVMABIRegistry EVMABIRegistry) *MockProposalContext_GetEVMRegistry_Call {
	_c.Call.Return(eVMABIRegistry)
	return _c
}

func (_c *MockProposalContext_GetEVMRegistry_Call) RunAndReturn(run func() EVMABIRegistry) *MockProposalContext_GetEVMRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// GetRenderer provides a mock function for the type MockProposalContext
func (_mock *MockProposalContext) GetRenderer() Renderer {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRenderer")
	}

	var r0 Renderer
	if returnFunc, ok := ret.Get(0).(func() Renderer); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Renderer)
		}
	}
	return r0
}

// MockProposalContext_GetRenderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRenderer'
type MockProposalContext_GetRenderer_Call struct {
	*mock.Call
}

// GetRenderer is a helper method to define mock.On call
func (_e *MockProposalContext_Expecter) GetRenderer() *MockProposalContext_GetRenderer_Call {
	return &MockProposalContext_GetRenderer_Call{Call: _e.mock.On("GetRenderer")}
}

func (_c *MockProposalContext_GetRenderer_Call) Run(run func()) *MockProposalContext_GetRenderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProposalContext_GetRenderer_Call) Return(renderer Renderer) *MockProposalContext_GetRenderer_Call {
	_c.Call.Return(renderer)
	return _c
}

func (_c *MockProposalContext_GetRenderer_Call) RunAndReturn(run func() Renderer) *MockProposalContext_GetRenderer_Call {
	_c.Call.Return(run)
	return _c
}

// GetSolanaDecoderRegistry provides a mock function for the type MockProposalContext
func (_mock *MockProposalContext) GetSolanaDecoderRegistry() SolanaDecoderRegistry {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSolanaDecoderRegistry")
	}

	var r0 SolanaDecoderRegistry
	if returnFunc, ok := ret.Get(0).(func() SolanaDecoderRegistry); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SolanaDecoderRegistry)
		}
	}
	return r0
}

// MockProposalContext_GetSolanaDecoderRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSolanaDecoderRegistry'
type MockProposalContext_GetSolanaDecoderRegistry_Call struct {
	*mock.Call
}

// GetSolanaDecoderRegistry is a helper method to define mock.On call
func (_e *MockProposalContext_Expecter) GetSolanaDecoderRegistry() *MockProposalContext_GetSolanaDecoderRegistry_Call {
	return &MockProposalContext_GetSolanaDecoderRegistry_Call{Call: _e.mock.On("GetSolanaDecoderRegistry")}
}

func (_c *MockProposalContext_GetSolanaDecoderRegistry_Call) Run(run func()) *MockProposalContext_GetSolanaDecoderRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProposalContext_GetSolanaDecoderRegistry_Call) Return(solanaDecoderRegistry SolanaDecoderRegistry) *MockProposalContext_GetSolanaDecoderRegistry_Call {
	_c.Call.Return(solanaDecoderRegistry)
	return _c
}

func (_c *MockProposalContext_GetSolanaDecoderRegistry_Call) RunAndReturn(run func() SolanaDecoderRegistry) *MockProposalContext_GetSolanaDecoderRegistry_Call {
	_c.Call.Return(run)
	return _c
}

// SetRenderer provides a mock function for the type MockProposalContext
func (_mock *MockProposalContext) SetRenderer(renderer Renderer) {
	_mock.Called(renderer)
	return
}

// MockProposalContext_SetRenderer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRenderer'
type MockProposalContext_SetRenderer_Call struct {
	*mock.Call
}

// SetRenderer is a helper method to define mock.On call
//   - renderer Renderer
func (_e *MockProposalContext_Expecter) SetRenderer(renderer interface{}) *MockProposalContext_SetRenderer_Call {
	return &MockProposalContext_SetRenderer_Call{Call: _e.mock.On("SetRenderer", renderer)}
}

func (_c *MockProposalContext_SetRenderer_Call) Run(run func(renderer Renderer)) *MockProposalContext_SetRenderer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Renderer
		if args[0] != nil {
			arg0 = args[0].(Renderer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProposalContext_SetRenderer_Call) Return() *MockProposalContext_SetRenderer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProposalContext_SetRenderer_Call) RunAndReturn(run func(renderer Renderer)) *MockProposalContext_SetRenderer_Call {
	_c.Run(run)
	return _c
}
