name: push-tag-release-operations-gen

on:
  push:
    tags:
      - tools/operations-gen/v*

jobs:
  cicd-publish-release-operations-gen:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: cicd-publish-release-operations-gen
        uses: smartcontractkit/.github/actions/cicd-build-publish-artifacts-go@4475ad7c475bacb1aefeccb132645149201ababd # cicd-build-publish-artifacts-go/0.7.0
        with:
          # general inputs
          app-name: operations-gen
          publish: "false" # do not publish docker image to ECR
          update-git-tag: "false"
          # goreleaser inputs
          goreleaser-args: "--config tools/operations-gen/.goreleaser.yml"
          goreleaser-version: '~> v2'
          goreleaser-dist: goreleaser-pro
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
