name: push-main

on:
  push:
    branches:
      - main

jobs:
  cache-gomod:
    name: Cache Go modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 1 # fetch only the latest commit
      - name: Cache Go modules
        uses: smartcontractkit/.github/actions/setup-golang@dcdc10badaa0702553d4aa2c8311b4239b48be2c # setup-golang@v0.3.2
        with:
          use-go-cache: true # this will setup the go cache
          only-modules: true
      - name: Run go mod download
        run: go mod download

  cd-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: cd-release
        uses: smartcontractkit/.github/actions/cicd-changesets@eeb76b5870e3c17856d5a60fd064a053c023b5f5 # cicd-changesets@1.0.0
        with:
          # general inputs
          git-user: app-token-issuer-infra-releng[bot]
          git-email: app-token-issuer-infra-releng[bot]@users.noreply.github.com
          # aws inputs
          aws-region: ${{ secrets.AWS_REGION }}
          aws-role-arn: ${{ secrets.GATI_AWS_ROLE_CI_CHANGESET_TOKEN_ISSUER_ROLE_ARN }}
          aws-lambda-url: ${{ secrets.GATI_LAMBDA_ENGOPS_URL }}
