name: push-tag-release

on:
  push:
    tags:
      - v*

jobs:
  cicd-publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: cicd-publish-release
        uses: smartcontractkit/.github/actions/cicd-build-publish-artifacts-go@b37583d758e3992e0d5bfdb5a36ca243ce53ff59 # cicd-build-publish-artifacts-go@0.4.0
        with:
          # general inputs
          app-name: chainlink-deployments-framework
          publish: "false" # do not publish docker image to ECR
          update-git-tag: "true"
          # goreleaser inputs
          goreleaser-args: "--config .goreleaser.yml"
          goreleaser-version: '~> v2'
          goreleaser-dist: goreleaser-pro
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}

# todo: enable once i have the secret setup (pending security ticket)
#      - name: Set tag for Slack notification
#        run: echo "TAG=${{ github.ref_name }}" >> "$GITHUB_ENV"
#        shell: bash
#
#      - name: Notify Slack
#        uses: smartcontractkit/.github/actions/slack-notify-git-ref@eeb76b5870e3c17856d5a60fd064a053c023b5f5 # slack-notify-git-ref@1.0.0
#        with:
#          slack-channel-id: ${{ secrets.SLACK_CHANNEL_CLDF}}
#          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN_RELENG }} # Releng Bot
#          git-ref: ${{ env.TAG }}
#          git-ref-type: tag
#          changelog-url: 'https://github.com/${{ github.repository }}/releases/tag/${{ env.TAG }}'
