name: push-tag-release

on:
  push:
    tags:
      - v*

jobs:
  cicd-publish-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      actions: read
    steps:
      - name: cicd-publish-release
        uses: smartcontractkit/.github/actions/cicd-build-publish-artifacts-go@e44d530ffc401f7571874c189f06f87fed524a70 # cicd-build-publish-artifacts-go@0.4.0
        with:
          # general inputs
          app-name: chainlink-deployments-framework
          publish: "false" # do not publish docker image to ECR
          update-git-tag: "true"
          # goreleaser inputs
          goreleaser-args: "--config .goreleaser.yml"
          goreleaser-version: '~> v2'
          goreleaser-dist: goreleaser-pro
          goreleaser-key: ${{ secrets.GORELEASER_KEY }}
